### DISCUSSION TITLE
how to define environment variables into config.yml?

### DISCUSSION THREAD

**Discussion by the-prodigy** [requarks/wiki#2847] [Help / Questions] [answered]
I wanted to read env variables from a .env file to config.yml, so I can deploy it to multiple environments, but how do I do it?

I'm working on linux ubuntu.

**Comment by NGPixel** [comment, marked as answer]
You can use `$(ENV_NAME)` in your config.yml to have it replaced at runtime.

**Reply by the-prodigy** [reply]
does not work.

**Reply by mattpr** [reply]
> You can use `$(ENV_NAME)` in your config.yml to have it replaced at runtime.

This was in the legacy docs (https://docs-legacy.requarks.io/wiki/install/configuration) but I can't find any reference to using environment variables in the 2.x docs.  I've resorted to searching the source for `process.env` under a given release tag.

There are some places where specific values are invoked specifically.  Examples...

- Set port: https://github.com/Requarks/wiki/blob/2.5.170/server/core/config.js#L56
- Set custom config file/location: https://github.com/Requarks/wiki/blob/2.5.170/server/core/config.js#L25
- set DB connection URL: https://github.com/Requarks/wiki/blob/2.5.170/server/core/db.js#L32

...and a more general mechanism.
https://github.com/Requarks/wiki/blob/2.5.170/server/helpers/config.js#L18

When provisioning this to our own servers it is much easier to utilize standard ENV in our systemd unit than messing around with maintaining and deploying a customized yaml file.  So it would be great to have a listing of supported ENV on the docs so I know whether I can count on this across releases or not.

**Reply by NGPixel** [reply]
@mattpr Consider using docker deployment in order to use ENV only.

**Reply by mattpr** [reply]
So I guess your answer implies that that using `$(ENV_NAME)` (as described here https://docs-legacy.requarks.io/wiki/install/configuration) will not be a viable long-term option for using ENV over a config file?

I did see this page: https://docs.requarks.io/install/docker

We aren't using docker. We have scripted provisioning on top of minimized linux images.  Deploying postgres/nginx and wiki.js is trivial for us...except for the config.  The config is also trivial if we resort to maintaining a yaml config template for wiki.js, but it would be nice to know if there was still a valid (undocumented in v2) option to use ENV instead.

**Reply by NGPixel** [reply]
If you mean using a custom config.yml file with $(ENV_NAME) in place of values, yes this is still supported and will still be going forward.

If you don't want to use a config.yml altogether, then docker is the recommended solution.

**Reply by mattpr** [reply]
> If you mean using a custom config.yml file with $(ENV_NAME) in place of values, yes this is still supported and will still be going forward.

Actually I didn't mean that.  But that solves my problem.  I misunderstood how the `$(ENV_NAME)` was supposed to work as I only came across this on the legacy wiki.  Re-reading this, I now understand this is referring to variable interpolation within the yaml.  Cool.  Re-reading your first answer on this issue, you are saying the same thing...I don't know why it didn't click until now.  Sorry.

Is this feature documented anywhere on the current wiki/docs?  I couldn't find anything about this outside of the single sentence on the legacy wiki.

Appreciate you taking time to reply.  Thanks!

**Reply by NGPixel** [reply]
It is indeed missing from the 2.x docs, I just added a section detailing its usage:
https://docs.requarks.io/en/install/config#env-variables-interpolation

**Reply by mattpr** [reply]
> It is indeed missing from the 2.x docs, I just added a section detailing its usage:

Hey, that's great and very helpful.  Appreciate it.

**Reply by mattpr** [reply]
One more little thing.  It looks like I can use env var `CONFIG_FILE` to specify custom config file name/location.  Either relative to `WIKI.ROOTPATH` or as absolute path.  This is quite useful for provisioning where the config file may be deployed separately from the tarball.  

https://github.com/Requarks/wiki/blob/2.5.170/server/core/config.js#L25

I didn't find this in the general documentation.  Well that's not entirely true...  

- I found it in the release notes for 2.0.0 (https://docs.requarks.io/releases#minor-improvements-5) 
- and it is mentioned on the Docker page (https://docs.requarks.io/install/docker#alternative-mount-the-config-file)
 
...but not mentioned elsewhere as a general option for non-Docker deployment cases.

**Reply by NGPixel** [reply]
CONFIG_FILE is really meant for docker installation, because of the possible volume mounting options. It can however be used for any purpose, docker or not.

**Reply by mattpr** [reply]
Okay.  I'm using this in my non-docker deployment (because config file is deployed separately from the wiki.js tarball) and it works great and is very useful. I hope you keep it generally available and not just under docker environment.  Thanks!

**Reply by the-prodigy** [reply]
@mattpr @NGPixel 

We use Elastic Beanstalk for deploying wiki.js, hence we **highly** need  **.env file** or **environment variables**, instead of specifing it in a **static** config.yml file. 
When using a .env file | environment variables like process.env.* for all type of wiki.js configurations like database, we and all other developers would be able to deploy different environments like prod, dev, test etc. 

But for now, I have no idea to deploy multiple environments of wiki.js due to an static config.yml with static data in it.

As I already mentioned, specifing environment variables within the config.yml file, **didnt work even one time for us**.

**Reply by mattpr** [reply]
> As I already mentioned, specifing environment variables within the config.yml file, **didnt work even one time for us**.

Configuring wiki.js with ENV works fine.  If you are having trouble the problem might be somewhere else or (like me) misunderstanding how the config file loads env.

### Here is our production config file for wiki.js...

```yaml
#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full documentation + examples:
# https://docs.requarks.io/install

# ---------------------------------------------------------------------
# Port the server should listen to
# ---------------------------------------------------------------------

port: $(APP_PORT)

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Supported Database Engines:
# - postgres = PostgreSQL 9.5 or later
# - mysql = MySQL 8.0 or later (5.7.8 partially supported, refer to docs)
# - mariadb = MariaDB 10.2.7 or later
# - mssql = MS SQL Server 2012 or later
# - sqlite = SQLite 3.9 or later

db:
  type: postgres

  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: $(DB_HOST)
  port: $(DB_PORT)
  user: $(DB_USER)
  pass: $(DB_PASS)
  db: $(DB_NAME)
  ssl: false

  # Optional - PostgreSQL / MySQL / MariaDB only:
  # -> Uncomment lines you need below and set `auto` to false
  # -> Full list of accepted options: https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options
  sslOptions:
    auto: true
    # rejectUnauthorized: false
    # ca: path/to/ca.crt
    # cert: path/to/cert.crt
    # key: path/to/key.pem
    # pfx: path/to/cert.pfx
    # passphrase: xyz123

  # SQLite only:
  storage: path/to/database.sqlite

#######################################################################
# ADVANCED OPTIONS                                                    #
#######################################################################
# Do not change unless you know what you are doing!

# ---------------------------------------------------------------------
# SSL/TLS Settings
# ---------------------------------------------------------------------
# Consider using a reverse proxy (e.g. nginx) if you require more
# advanced options than those provided below.

ssl:
  enabled: false
  port: 3443

  # Provider to use, possible values: custom, letsencrypt
  provider: custom

  # ++++++ For custom only ++++++
  # Certificate format, either 'pem' or 'pfx':
  format: pem
  # Using PEM format:
  key: path/to/key.pem
  cert: path/to/cert.pem
  # Using PFX format:
  pfx: path/to/cert.pfx
  # Passphrase when using encrypted PEM / PFX keys (default: null):
  passphrase: null
  # Diffie Hellman parameters, with key length being greater or equal
  # to 1024 bits (default: null):
  dhparam: null

  # ++++++ For letsencrypt only ++++++
  domain: wiki.yourdomain.com
  subscriberEmail: admin@example.com

# ---------------------------------------------------------------------
# Database Pool Options
# ---------------------------------------------------------------------
# Refer to https://github.com/vincit/tarn.js for all possible options

pool:
  # min: 2
  # max: 10

# ---------------------------------------------------------------------
# IP address the server should listen to
# ---------------------------------------------------------------------
# Leave 0.0.0.0 for all interfaces

bindIP: 0.0.0.0

# ---------------------------------------------------------------------
# Log Level
# ---------------------------------------------------------------------
# Possible values: error, warn, info (default), verbose, debug, silly

logLevel: info

# ---------------------------------------------------------------------
# Offline Mode
# ---------------------------------------------------------------------
# If your server cannot access the internet. Set to true and manually
# download the offline files for sideloading.

offline: false

# ---------------------------------------------------------------------
# High-Availability
# ---------------------------------------------------------------------
# Set to true if you have multiple concurrent instances running off the
# same DB (e.g. Kubernetes pods / load balanced instances). Leave false
# otherwise. You MUST be using PostgreSQL to use this feature.

ha: false

# ---------------------------------------------------------------------
# Data Path
# ---------------------------------------------------------------------
# Writeable data path used for cache and temporary user uploads.
dataPath: $(DATA_DIR)
```

We deploy that config alongside (but separately) from the wiki.js tarball.

### ...and an extract from the systemd unit that runs wiki.js....

**Of note: ** we tell wiki.js which config.yml to use (ours) via ENV.  We also pass other relevant env to wiki.js (note the ENV names match what is in the config.yml).

```
#...
Environment=NODE_ENV=production CONFIG_FILE=/opt/wiki-js/config.yml APP_PORT=3333 DB_HOST=localhost DB_PORT=5432 DB_USER=wikijs DB_PASS=<redacted> DB_NAME=wikijs DATA_DIR=/opt/wiki-js/data
WorkingDirectory=/opt/wiki-js/current
ExecStart=/opt/nodejs/current/bin/node /opt/wiki-js/current/server/index.js
#...
```

We do SSL termination on nginx side, so the wiki.js config is mostly: db, where to store data and where to find config file.
