### DISCUSSION TITLE
Wiki.JS via Docker - Can't generate Let's encrypt certificate

### DISCUSSION THREAD

**Discussion by charlietangocharlie** [requarks/wiki#2893] [Help / Questions]
HI everyone, don't know if it's the best place to ask my question but I try :
I'm having issues enabling HTTPS on a fresh wiki.js on docker hosted on qnap  NAS. I did follow the doc but it fails.
The docker logs are pretty clear but I cannot find any solution
the logs are :

> 2021-01-06T18:08:15.033Z [MASTER] info: =======================================                                                                                                                         
> 2021-01-06T18:08:15.039Z [MASTER] info: = Wiki.js 2.5.170 =====================                                                                                                                         
> 2021-01-06T18:08:15.039Z [MASTER] info: =======================================                                                                                                                         
> 2021-01-06T18:08:15.040Z [MASTER] info: Initializing...                                                                                                                                                 
> 2021-01-06T18:08:16.386Z [MASTER] info: Using database driver mysql2 for mariadb [ OK ]                                                                                                                 
> 2021-01-06T18:08:16.398Z [MASTER] info: Connecting to database...                                                                                                                                       
> 2021-01-06T18:08:16.482Z [MASTER] info: Database Connection Successful [ OK ]                                                                                                                           
> 2021-01-06T18:08:17.624Z [MASTER] warn: Mail is not setup! Please set the configuration in the administration area!                                                                                     
> 2021-01-06T18:08:17.853Z [MASTER] info: Loading GraphQL Schema...                                                                                                                                       
> 2021-01-06T18:08:19.173Z [MASTER] info: GraphQL Schema: [ OK ]                                                                                                                                          
> 2021-01-06T18:08:19.800Z [MASTER] info: HTTP Server on port: [ 3000 ]                                                                                                                                   
> 2021-01-06T18:08:19.851Z [MASTER] info: (LETSENCRYPT) Initializing Let's Encrypt client...                                                                                                              
> 2021-01-06T18:08:19.903Z [MASTER] info: HTTP Server: [ RUNNING ]                                                                                                                                        
> 2021-01-06T18:08:20.686Z [MASTER] info: (LETSENCRYPT) Generating server keypairs...                                                                                                                     
> 2021-01-06T18:08:20.914Z [MASTER] info: (LETSENCRYPT) Server keypairs generated successfully [ OK ]                                                                                                     
> 2021-01-06T18:08:20.914Z [MASTER] info: (LETSENCRYPT) Generating certificate signing request (CSR)...                                                                                                   
> 2021-01-06T18:08:20.932Z [MASTER] info: (LETSENCRYPT) CSR generated successfully [ OK ]                                                                                                                 
> 2021-01-06T18:08:20.933Z [MASTER] info: (LETSENCRYPT) Requesting certificate from Let's Encrypt...                                                                                                      
> 2021-01-06T18:08:20.944Z [MASTER] info: (LETSENCRYPT) Setting HTTP challenge for mouahahah.myqnapcloud.com: [ READY ]                                                                                   
> 2021-01-06T18:08:20.945Z [MASTER] info: (LETSENCRYPT) Waiting for challenge to complete...                                                                                                              
> 2021-01-06T18:08:26.039Z [MASTER] info: (LETSENCRYPT) Removing HTTP challenge: [ OK ]                                                                                                                   
> 2021-01-06T18:08:26.040Z [MASTER] info: (LETSENCRYPT) Removing HTTP challenge: [ OK ]                                                                                                                   
> 2021-01-06T18:08:26.041Z [MASTER] warn: (LETSENCRYPT) Error: self signed certificate in certificate chain                                                                                               
> 2021-01-06T18:08:26.041Z [MASTER] error: self signed certificate in certificate chain   

the docker config file is :
```
version: "3"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mouahahah
      MYSQL_DATABASE: wiki
      MYSQL_USER: mouahahah
      MYSQL_PASSWORD: mouahahah
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: mariadb
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: mouahahah
      DB_PASS: mouahahah
      DB_NAME: wiki
      #LETSENCRYPT_DOMAIN: mouahahah.myqnapcloud.com
      #SSL_ACTIVE: 1
    restart: unless-stopped
    ports:
      - "3333:3000"
      - "3334:3443"
volumes:
  db-data:
```
