### DISCUSSION TITLE
Issue with connecting to database in docker

### DISCUSSION THREAD

**Discussion by limpep** [requarks/wiki#2987] [Help / Questions] [answered]
**Describe the bug**
I am having a issue where the app is failing to connect to the database within the container on Raspberry 4. 

```
2021-01-29T18:55:29.308Z [MASTER] info: =======================================
2021-01-29T18:55:29.313Z [MASTER] info: = Wiki.js 2.5.170 =====================
2021-01-29T18:55:29.314Z [MASTER] info: =======================================
2021-01-29T18:55:29.314Z [MASTER] info: Initializing...
2021-01-29T18:55:30.781Z [MASTER] info: Using database driver pg for postgres [ OK ]
2021-01-29T18:55:30.803Z [MASTER] info: Connecting to database...
2021-01-29T18:55:30.843Z [MASTER] error: Database Connection Error: ENOTFOUND undefined:undefined
2021-01-29T18:55:30.844Z [MASTER] warn: Will retry in 3 seconds... [Attempt 1 of 10]
2021-01-29T18:55:33.848Z [MASTER] info: Connecting to database...
2021-01-29T18:55:33.855Z [MASTER] error: Database Connection Error: ENOTFOUND undefined:undefined
```

Here is my docker-compose.yml

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
```
Here is 

```

  `.::///+:/-.        --///+//-:``    pi@raspberrypi
 `+oooooooooooo:   `+oooooooooooo:    --------------
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv7l
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi 4 Model B Rev 1.4
   `:oooooooo+``    `.oooooooo+-      Kernel: 5.4.83-v7l+
     `:++ooo/.        :+ooo+/.`       Uptime: 38 mins
        ...`  `.----.` ``..           Packages: 1879 (dpkg)
     .::::-``:::::::::.`-:::-`        Shell: bash 5.0.3
    -:::-`   .:::::::-`  `-:::-       Terminal: /dev/pts/0
   `::.  `.--.`  `` `.---.``.::`      CPU: BCM2711 (4) @ 1.500GHz
       .::::::::`  -::::::::` `       Memory: 919MiB / 7874MiB
 .::` .:::::::::- `::::::::::``::.
-:::` ::::::::::.  ::::::::::.`:::-
::::  -::::::::.   `-::::::::  ::::
-::-   .-:::-.``....``.-::-.   -::-
 .. ``       .::::::::.     `..`..
   -:::-`   -::::::::::`  .:::::`
   :::::::` -::::::::::` :::::::.
   .:::::::  -::::::::. ::::::::
    `-:::::`   ..--.`   ::::::.
      `...`  `...--..`  `...`
            .::::::::::
             `.-::::-`

```

here id docker version

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:18:13 2020
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:48 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
