### DISCUSSION TITLE
Letsencrypt Pre-Flight 404

### DISCUSSION THREAD

**Discussion by breaker-of-stone** [requarks/wiki#3209] [Help / Questions] [answered]
The Letsencrypt pre-flight curl fetch gets a 404, and I notice that the quoted curl omits the port (:3000).

1.  Wiki.js working normally on default port.  No reverse proxy, wiki.js connecting directly to the port.
2. Modified config.yml to require Letsencrypt as follows:

```
# ---------------------------------------------------------------------
# Port the server should listen to
# ---------------------------------------------------------------------

port: 3000

# ---------------------------------------------------------------------
# SSL/TLS Settings
# ---------------------------------------------------------------------
# Consider using a reverse proxy (e.g. nginx) if you require more
# advanced options than those provided below.

ssl:
  enabled: true
  port: 3443
  provider: letsencrypt

  # ++++++ For letsencrypt only ++++++
  domain: wiki.noisebin.org
  subscriberEmail: admin@noisebin.org

#   # Provider to use, possible values: custom, letsencrypt
#   provider: custom
# 
#   # ++++++ For custom only ++++++
#   # Certificate format, either 'pem' or 'pfx':
#   format: pem
#   # Using PEM format:
#   key: path/to/key.pem
#   cert: path/to/cert.pem
#   # Using PFX format:
#   pfx: path/to/cert.pfx
#   # Passphrase when using encrypted PEM / PFX keys (default: null):
#   passphrase: null
#   # Diffie Hellman parameters, with key length being greater or equal
#   # to 1024 bits (default: null):
#   dhparam: null
```

### Result:

```
2021-03-13T07:28:41.479Z [MASTER] warn: (LETSENCRYPT) Error: Error: Failed HTTP-01 Pre-Flight / Dry Run.
curl 'http://wiki.noisebin.org/.well-known/acme-challenge/test-2d1300ab355ba41aac2cb2c1b3790db6-0'
Expected: 'test-2d1300ab355ba41aac2cb2c1b3790db6-0.EvusP9a9zkFE3M3-_bM2eBpdLWV8SxdBPVEev0M76ok'
Got: '<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
'

```
Should there be a :3000 in that curl request?

How?
