### DISCUSSION TITLE
Error uploading a file

### DISCUSSION THREAD

**Discussion by dan-burt** [requarks/wiki#3259] [Error / Bug Report]
**Question**
Deploying in a localhost Docker instance. Container is deployed. Initial setup completes. When creating first page, I try to upload and use an image. I get "An unexpected error occurred".

```
version: "3"
services:
  wiki:
    image: requarks/wiki:2
    environment:
      DB_TYPE: mysql
      DB_HOST: localserver.local
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: pass
      DB_NAME: database
      VIRTUAL_HOST: wiki.domain.com
      LETSENCRYPT_HOST: wiki.domain.com
      LETSENCRYPT_EMAIL: user@domain.com
    volumes:
      - ./data:/data
    restart: unless-stopped
    ports:
      - "3000:3000"

```

I had to enable the Local Storage option. I have tried putting values in the "Path" variable, including the above bind volume, none seem to work.

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: requarks/wiki:2
Database engine: mysql 5.7

**Comment by Smankusors** [comment]
are you trying to upload file inside folder?

**Comment by dan-burt** [comment]
In the page editor, tap the Insert Media button. New UI appears, drop and drop my JPG file, progresses to 100% then errors

Thanks

Dan

**Comment by Smankusors** [comment]
hmm this error is not really user friendly 💭 

please open the console tab from your browser DevTools (press F12 or Ctrl+Shift+I). Then reproduce your error, and then post your screenshot here.

**Comment by FelixSFD** [comment]
I'm having the same issue in the non-Docker installation (Version 2.5.170)

The developer tools show this error 500 for the POST-request to `https://wiki/u`

> Oops, something went wrong...Too many files

The POST-Body is:

```
------WebKitFormBoundaryoWSYZXq8XPhb1YzJ
Content-Disposition: form-data; name="mediaUpload"

{"folderId":52}
------WebKitFormBoundaryoWSYZXq8XPhb1YzJ
Content-Disposition: form-data; name="mediaUpload"; filename="myfile.pdf"
Content-Type: application/pdf


------WebKitFormBoundaryoWSYZXq8XPhb1YzJ--
```


According to my config.yml, I can upload up to 20 files at once. However, even one small file does not work.

```
# ---------------------------------------------------------------------
# Upload Limits
# ---------------------------------------------------------------------
# If you're using a reverse-proxy in front of Wiki.js, you must also
# change your proxy upload limits!

uploads:
  # Maximum upload size in bytes per file (default: 5242880 (5 MB))
  maxFileSize: 5368709120
  # Maximum file uploads per request (default: 20)
  maxFiles: 20
```
