### DISCUSSION TITLE
Kroki and PlantUML not rendering (Docker)

### DISCUSSION THREAD

**Discussion by ghost** [requarks/wiki#3275] [Error / Bug Report]
**Question**
I have setup wiki.js in a docker-compose file along with kroki and plantuml servers.

When I visit the kroki and plantuml servers directly in my browser I can see their interfaces, so I know they are running.

I have enabled both kroki and plantuml in the settings and entered the docker hostnames and port numbers.
`http://kroki:3001`
`http://plantuml:3002`

When I try to add an example kroki or plantuml diagram (pasted directly from their own examples) neither one renders properly. I just get a "broken image" in the rendered output.

I can't even seem to get the public kroki/plantuml servers to render.

Is this a bug in wiki.js or a misconfiguration on my part?

```
services:
  wiki-db:
    container_name: wiki-db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./data/wiki/postgres:/var/lib/postgresql/data
    dns: 8.8.8.8

  wiki:
    container_name: wiki
    image: requarks/wiki:2
    depends_on:
      - wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3000:3000"
    dns: 8.8.8.8

  kroki:
    container_name: kroki
    image: yuzutech/kroki
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
    ports:
      - "3001:8000"

  blockdiag:
    container_name: kroki-blockdiag
    image: yuzutech/kroki-blockdiag
    expose:
      - "8001"

  mermaid:
    container_name: kroki-mermaid
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"

  bpmn:
    container_name: kroki-bpmn
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"

  plantuml:
    container_name: plantuml
    image: plantuml/plantuml-server:jetty
    ports:
      - "3002:8080"
```

**Host Info (please complete the following information):**
OS: Docker Container (Linux)
Wiki.js version: 2.5.170
Database engine: PostgreSQL 13.1

**Comment by MLukman** [comment]
For containers to refer to each other by their names like `http://kroki:3001` and `http://plantuml:3002` they need to belong to at least one shared user-defined bridge network (the default bridge network does not count). Plus, they refer by the container ports, not the host-mapped ports. So in your case, kroki is at `http://kroki:8000` and plantuml is at `http://plantuml:8080`

Refer step/point 5 in this page: https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks.

**Comment by ghost** [comment]
@MLukman thanks for that. I have added the bridged network and now diagrams are rendering when I save the page.

Now it is just the preview panel when editing that is refusing to render diagrams. Is that normal?

**Comment by despens** [comment]
@gambcl: The markdown editor is not producing the same results as the renderer in many other respects, so it is probably true for kroki, too.

Could you post your docker-compose.yml configuration that made kroki work for you? I did add all contrainers into a shared network, and can get a response from `docker-compose exec wiki curl http://kroki:8000`, but a `kroki` block in my markdown will always just generates `uml diagram`.

**Comment by ghost** [comment]
@despens This is the file I am using, hope it helps:

```
version: '3'

services:
  wiki-db:
    container_name: wiki-db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./data/wiki/postgres:/var/lib/postgresql/data
    dns: 8.8.8.8
    networks:
      - wikijs-net

  wiki:
    container_name: wiki
    image: requarks/wiki:2
    depends_on:
      - wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3000:3000"
    dns: 8.8.8.8
    networks:
      - wikijs-net

  kroki:
    container_name: kroki
    image: yuzutech/kroki
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
    ports:
      - "3001:8000"
    networks:
      - wikijs-net

  blockdiag:
    container_name: kroki-blockdiag
    image: yuzutech/kroki-blockdiag
    expose:
      - "8001"
    networks:
      - wikijs-net

  mermaid:
    container_name: kroki-mermaid
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
    networks:
      - wikijs-net

  bpmn:
    container_name: kroki-bpmn
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"
    networks:
      - wikijs-net

  plantuml:
    container_name: plantuml
    image: plantuml/plantuml-server:jetty
    ports:
      - "3002:8080"
    networks:
      - wikijs-net

networks:
  wikijs-net:
    driver: bridge
```
