### DISCUSSION TITLE
how to set proxy in helm chart

### DISCUSSION THREAD

**Discussion by Hokwang** [requarks/wiki#3292] [Error / Bug Report]
**Describe the bug**

Hi,
I installed wiki.js on kubernetes cluster using helm chart.
here's an error message in log.

```
2020-12-08T03:01:49.437Z [MASTER] warn: request to https://graph.requarks.io failed, reason: connect ETIMEDOUT 172.67.69.86:443
2020-12-08T03:02:07.868Z [MASTER] error: Fetching latest updates from Graph endpoint: [ FAILED ]
2020-12-08T03:02:07.868Z [MASTER] error: request to https://graph.requarks.io failed, reason: connect ETIMEDOUT 104.26.14.122:443
2020-12-08T03:02:07.868Z [MASTER] warn: request to https://graph.requarks.io failed, reason: connect ETIMEDOUT 172.67.69.86:443
2020-12-08T03:02:07.869Z [MASTER] error: Syncing locales with Graph endpoint: [ FAILED ]
2020-12-08T03:02:07.869Z [MASTER] error: request to https://graph.requarks.io failed, reason: connect ETIMEDOUT 104.26.15.122:443
```

I am in corporate proxy. I need to set env like 'http_proxy' or java option for proxy `-Dhttp.proxyHost`.
But there's nothing to do this in helm chart.

Please make helm chart first-class citizen of your deployment solutions.

**Comment by wjkw1** [comment]
Hi @Hokwang 

I got the container working through a proxy by changing the helm chart files, see below. This will set the containers env variables for HTTP_PROXY & HTTPS_PROXY if you provide a value in the values.yaml file only. If the values are omitted then no proxy will be used.

I can confirm internet access using curl to grab a websites headers: `curl -I https://google.com`

# Config to add helm chart files
**values.yaml**
*Add these to the end of the file*
```yaml
### REST OF CONFIG ABOVE ^^ ###
## httpProxy is used for configuring http proxy env variables
## httpsProxy is used for configuring https proxy env variables
##
httpProxy: http://your_proxy_here
httpsProxy: http://your_proxy_here
```

**templates/deployment.yaml**
*Under the chart name environment where there is the database env details*

```yaml
    containers:                                    
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.imagePullPolicy }}
          env:
### COPY FROM LINE BELOW ###
          {{- if .Values.httpProxy }}
            - name: HTTP_PROXY
              value: {{ .Values.httpProxy }}
          {{- end }}
          {{- if .Values.httpsProxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.httpsProxy }}
          {{- end }}
### COPY TO LINE ABOVE
```

# Locale issue still persisting after net access confirmed
However, after changing these files the locales still fail to download with the same error. Working on finding a way around this now.

I am able to grab the files using curl so might be able to add a helm command, see below.

``` bash
mkdir data/sideload

curl https://raw.githubusercontent.com/Requarks/wiki-localization/master/locales.json > data/sideload/locale.json

curl https://raw.githubusercontent.com/Requarks/wiki-localization/master/en.json > data/sideload/en.json
```

It is said on many other issues that simply restarting the container worked as the files were downloaded. In my case, when the container is re-deployed it starts from scratch so I don't believe this will work.

More info here: https://docs.requarks.io/s/en/install/sideload
