### DISCUSSION TITLE
Moving the panel to the other side

### DISCUSSION THREAD

**Discussion by Scrik** [requarks/wiki#3390] [Help / Questions]
**Question**
Can this panel be moved to the right side? And how to do it?
![image](https://user-images.githubusercontent.com/5807097/84764759-e353bf00-afd6-11ea-91cb-b89597030ff7.png)

**Host Info (please complete the following information):**
OS: Centos 7
Wiki.js version: Stable 2.4.107
Database engine: postgres 11

**Comment by Smankusors** [comment]
currently, no.

but, you can inject your own CSS rules via theme menu

**Comment by Scrik** [comment]
Can you tell me how to do this through CSS?

**Comment by Scrik** [comment]
please, help

**Comment by RunningIkkyu** [comment]
@Scrik  Hi Scrik, inject css code works for me. 

# Solution 

Just copy the blow code to Admin → Theme →  CSS Inject. and Apply.

```css
.container > .layout.row {
    flex-flow: row-reverse;
}

.page-col-content.is-page-header.offset-lg-3.offset-xl-2.col.pl-4 {
    margin-left: auto;
}

.v-application .grey--text.text--darken-3 {
    color: #505050!important;
    caret-color: #424242!important;
}
```

# Explaination

Reverse the left and right part.

```css
.container > .layout.row {
    flex-flow: row-reverse;
}
```

After revert these two part, The titile looks not good, so I adjust the title.

```css
.page-col-content.is-page-header.offset-lg-3.offset-xl-2.col.pl-4 {
    margin-left: auto;
}
```

Also making a slight change on the color of the title.

```css
.v-application .grey--text.text--darken-3 {
    color: #505050!important;
    caret-color: #424242!important;
}
```

Hope this will help you.
