### DISCUSSION TITLE
Problem setting up wiki.js with docker

### DISCUSSION THREAD

**Discussion by hsteininger** [requarks/wiki#3401] [Help / Questions]
**Question**
Hi,

when trying to setup wiki.js in docker, with docker-compose. 
After launching the containers i get this in my logs:

```
2020-07-07T07:13:50.069Z [MASTER] error: Syncing locales with Graph endpoint: [ FAILED ]
2020-07-07T07:13:50.070Z [MASTER] error: request to https://graph.requarks.io failed, reason: getaddrinfo EAI_AGAIN graph.requarks.io
2020-07-07T07:13:50.071Z [MASTER] error: Fetching latest updates from Graph endpoint: [ FAILED ]
2020-07-07T07:13:50.072Z [MASTER] error: request to https://graph.requarks.io failed, reason: getaddrinfo EAI_AGAIN graph.requarks.io
```

and also all of the field.titles seem not to work (see [Image](https://imgur.com/a/ufEzict))

we have a proxy in here and i added the proxy settings to the docker daemon, which works well with other containers.
also setting the proxy in the docker-compose as environment doesn't help. 

maybe someone could shed some light on me what i'm doing wrong?

Thanks in Advance.

**Host Info (please complete the following information):**
OS: [Ubuntu 18.04.4 LTS, Docker version 19.03.6, build 369ce74a3c]
Wiki.js version: [Wiki.js 2.4.107]
Database engine: [postgres:11-alpine]

**Comment by Smankusors** [comment]
Hmm so your network require proxy to access internet? How do you setting proxy in docker-compose btw?

Alternatively, you might want to enable offline mode in Wiki.js

**Reply by mweitner** [reply]
I have similar issue when installing Wiki.js at DigitalOcean as droplet which is actually docker image running on an Ubuntu 20 LTS machine. Log shows following error:
```
2022-03-14T10:29:38.981Z [MASTER] info: Fetching latest updates from Graph endpoint...
2022-03-14T10:29:39.057Z [MASTER] info: Purging orphaned upload files: [ COMPLETED ]
2022-03-14T10:29:39.098Z [MASTER] error: Syncing locales with Graph endpoint: [ FAILED ]
2022-03-14T10:29:39.102Z [MASTER] error: Network request failed with status 403 - "Forbidden"
2022-03-14T10:29:39.114Z [MASTER] error: Fetching latest updates from Graph endpoint: [ FAILED ]
2022-03-14T10:29:39.114Z [MASTER] error: Network request failed with status 403 - "Forbidden"
```
Wiki.js: 2.5.276

Wiki UI shows following error:
```
[GraphQL error]: Message: Invalid locale or namespace, Location: [object Object], Path: localization,translations
(anonymous) @ app.js?1645408589:19
```
thx in advance

**Reply by evle** [reply]
same issue +1, any advice ?   thx in advance
<img width="372" alt="image" src="https://user-images.githubusercontent.com/3981092/173625471-0d86c632-d40e-4e6c-b693-73acad2853f1.png">

**Reply by ja0nz** [reply]
Same👆

**Reply by mike-lloyd03** [reply]
I'm having this same problem when deploying with Docker on my home server. My network does not require any special proxy to access the inernet.

Additionally, the UI appears to be showing component IDs instead of title text.

![image](https://user-images.githubusercontent.com/49411532/198108795-aa5152a2-6368-4894-a045-810409b1f439.png)

My docker compose:
```yaml
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: "${DB_PASS}"
      DB_NAME: wikijs
    restart: unless-stopped
    ports:
      - "8084:3000"

volumes:
  db-data:
```

**Comment by mike-lloyd03** [comment]
Got it figured out. I am also running tailscale on this host and it apparently messes with your `/etc/resolve.conf` file. To fix the problem, I added the Cloudflare DNS to `/etc/docker/daemon.json`:

```json
{
    "dns": ["1.1.1.1"]
}
```

And restarted the Docker daemon (`systemctl restart docker`)

**Reply by ffy8206** [reply]
having the same problem, and it doesn't work either even setting up the DNS
Is there any other suggestions?

**Reply by ItsJustRuby** [reply]
In case you are using docker-compose, you could also try specifying a DNS per application container, as in...

```
  wiki:
    image: ghcr.io/requarks/wiki:2
    dns: 1.1.1.1
```

I am running multiple applications on the same host, and found this more reliable than editing `/etc/docker/daemon.json`.

**Reply by mike-lloyd03** [reply]
Awesome. Didn't know you could set DNS per project. Thanks!

**Reply by kacperknapik** [reply]
Adding `dns` property to my `docker-compose.yml` helped with the missing translations. Thanks a lot

NOTE: I'm using pihole on my home server where wiki was installed via docker-compose, so this might be the issue

**Reply by gfournel** [reply]
Hi guys, adding dns in the docker-compose.yml didn't help for me.
I may have to set up a proxy to access to Internet, but do you think : 

```dockerfile
wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: xxx
      DB_PASS: xxx
      DB_NAME: xx
      HTTP_PROXY: http://PROXY_HOST:$PROXY_PORT
      HTTPS_PROXY: https://PROXY_HOST:$PROXY_PORT
``` 
can be relevant?

**Comment by brian-zzy** [comment]
same problem!!!
![image](https://user-images.githubusercontent.com/75214243/234825215-068ba5f5-4db3-41a1-ad99-2ad764545316.png)

https://docs.requarks.io/en/install/sideload

**Reply by ELC3K** [reply]
[Offline mode](https://docs.requarks.io/install/config#offline-mode) needs [sideloading](https://docs.requarks.io/install/sideload)

for compose : 
- add wiki-localization git submodule https://github.com/requarks/wiki-localization.git  
- mount wiki-localization to /wiki/data/sideload
- download and modify [config.yml:124](https://github.com/requarks/wiki/blob/main/config.sample.yml#L124) `offline: true`
- mount config.yml to /wiki/config.yml

**Reply by gerab** [reply]
do not "download and modify [config.yml:124] offline: true"

take your current config from docker's console with cat /wiki/config.yml, create a copy on host and add offline: $(OFFLINE), map host's config to docker. Then modify env variables by adding OFFLINE: true.

should be smthng like:

```
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: letsencrypt
  domain: $(LETSENCRYPT_DOMAIN)
  subscriberEmail: $(LETSENCRYPT_EMAIL)
logLevel: $(LOG_LEVEL:info)
logFormat: $(LOG_FORMAT:default)
offline: $(OFFLINE)
ha: $(HA_ACTIVE)%         
```
