### DISCUSSION TITLE
Tag counter in administration navigation seems to be broken

### DISCUSSION THREAD

**Discussion by renekaesler** [requarks/wiki#3493] [Error / Bug Report]
**Describe the bug**
When accessing the administration overview, the tag counter (badge behind the *tags* item)  does not show the correct number of available tags. In my case I only have **one** tag but the counter shows **two**.

**To Reproduce**
1. Setup Wiki.js based on the given docker-compose example
2. Create an administrator account by the installation wizzard
3. Create a first wiki page, but name the path `/trading`
4. Tag this page with `trading`
5. Create a second wiki page by using the path `/home`
6. Tag this page with `wiki overview`
7. Change the default locale to `german`
8. Logout & Login
9. Creating a new homepage by using the path `/home`
10. Tag this page with `overview`
11. Delete all `en` locale pages 

**Expected behavior**
The counter should only show the number of available tags

**Screenshots**
![locale-german](https://user-images.githubusercontent.com/13448180/95397861-99d00c80-0904-11eb-87a5-e243b0bdc6d3.png)
![pages-overview](https://user-images.githubusercontent.com/13448180/95397874-9e94c080-0904-11eb-8005-c0bed10a0cf1.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.159
 - Database engine: postgres:11-alpine

**Additional context**
Docker Compose Relevant Entries
```
version: '3'

services:
  wiki:
    image: requarks/wiki:2
    depends_on:
      - wikidb
    environment:
      - "DB_TYPE=postgres"
      - "DB_HOST=wikidb"
      - "DB_PORT=5432"
      - "DB_USER=${WIKI_DB_USER}"
      - "DB_PASS=${WIKI_DB_PASS}"
      - "DB_NAME=${WIKI_DB_NAME}"
    restart: unless-stopped
  wikidb:
    image: postgres:11-alpine
    environment:
      - "POSTGRES_DB=${WIKI_DB_NAME}"
      - "POSTGRES_PASSWORD=${WIKI_DB_PASS}"
      - "POSTGRES_USER=${WIKI_DB_USER}"
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - wikidb:/var/lib/postgresql/data
volumes:
  wikidb:
```
