### DISCUSSION TITLE
LDAP connections fails with StartTLS

### DISCUSSION THREAD

**Discussion by Angelin01** [requarks/wiki#3599] [Error / Bug Report]
**Describe the bug**
When attempting to connect to an LDAP that enforces StartTLS, the connection simply fails with "confidentiality required".
It seems turning on TLS on the admin options only tries to make the client use a certificate, which should be completely unnecessary (and will cause an error only in the logs if you leave the certificate path empty), but it does not attempt to use StartTLS when connecting to the server. Even so, giving the client a certificate and enabling TLS will still fail with the same error.

In fact, I suggest the options are expanded: one should be able to select whether to use the older LDAPS or the newer StartTLS, and a secondary option for client certificates, which in many cases are unnecessary. My LDAP server has them set as "allow", other applications can successfully connect without a problem.

**To Reproduce**
1. Log in as a administrator
2. Go to the Authorization admin page
3. Fill out the LDAP section
4. Try to log in as a LDAP user
5. Fail with "confidentiality required"

**Expected behavior**
The LDAP user successfully logs in

**Screenshots**
The LDAP configuration, note that the client cert is snake-oil, but this should not matter.
![image](https://user-images.githubusercontent.com/17818024/89040780-ac353500-d31a-11ea-8156-07fa73d88915.png)

The error in question:
![image](https://user-images.githubusercontent.com/17818024/89040887-d38c0200-d31a-11ea-932a-ca52af3e2391.png)

**Host Info (please complete the following information):**
 - OS: Docker with Docker-Compose
 - Wiki.js version: 2.4.107
 - Database engine: Postgres 13-alpine

**Additional context**
A snippet of my docker-compose file, for reference:

```yml
  openldap:
    image: '${OPENLDAP_VERSION}'
    container_name: openldap
    hostname: '${LDAP_HOSTNAME}'
    command: ['--copy-service']
    restart: unless-stopped
    networks:
      ldap_in:
        aliases:
          - '${LDAP_HOSTNAME}.${COMMON_DOMAIN}'
    environment:
      LDAP_TLS: 'true'
      LDAP_TLS_CRT_FILENAME: 'fullchain1.pem'
      LDAP_TLS_KEY_FILENAME: 'privkey1.pem'
      LDAP_TLS_CA_CRT_FILENAME: 'fullchain1.pem'
      LDAP_TLS_ENFORCE: 'true'
      LDAP_ORGANISATION: '**REDACTED**'
      LDAP_DOMAIN: '${COMMON_DOMAIN}'
      LDAP_BASE_DN: '${BASE_LDAP_DN}'
      LDAP_ADMIN_PASSWORD: '${LDAP_ADMIN_PWD}'
      LDAP_TLS_CIPHER_SUITE: 'NORMAL'
      LDAP_TLS_VERIFY_CLIENT: 'allow'
      LDAP_RFC2307BIS_SCHEMA: 'true'
    volumes:
      - ldap_db_volume:/var/lib/ldap
      - ldap_config_volume:/etc/ldap/slapd.d
      - ./ldap/access.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/access.ldif:ro
      - '${CERT_DIR}:/container/service/slapd/assets/certs:ro'
    ports:
      - "389:389"

  wiki_db:
    image: postgres:13-alpine
    container_name: wiki_db
    networks:
      - wiki_db
    logging:
      driver: "none"
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    volumes:
      - wiki_db_data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:latest
    container_name: wiki
    hostname: wiki
    restart: unless-stopped
    networks:
      - wiki_db
      - nginx_in
      - ldap_in
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki_db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki

      VIRTUAL_HOST: 'wiki.${COMMON_DOMAIN}'
      VIRTUAL_PORT: 3000
    depends_on:
      - wiki_db
```

The LDAP logs show the failed connection:
```
openldap | 5f241acc conn=1012 fd=12 ACCEPT from IP=172.22.0.4:39394 (IP=0.0.0.0:389)
openldap | 5f241acc conn=1012 op=0 BIND dn="cn=observer,dc=**REDACTED**,dc=com" method=128
openldap | 5f241acc conn=1012 op=0 RESULT tag=97 err=13 text=confidentiality required
openldap | 5f241acc conn=1012 op=1 UNBIND
openldap | 5f241acc conn=1012 fd=12 closed
```

The WikiJS logs show nothing special aside from the failed connection, even with the LDAP debug flag on.
They do show the "failed to open" error when not providing any client certificate.

--

Addendum:
Disabling "use TLS" and pointing the server to `ldaps://ldap.mydomain.com:636` works fully.
