### DISCUSSION TITLE
Import GIT storage form v.1 error

### DISCUSSION THREAD

**Discussion by ilyamochalov** [requarks/wiki#3706] [Error / Bug Report]
**Import GIT storage form v.1**
I am upgrading from v1 to v2. Am using using `utilities` -> `Import from v1.x` importing my GitHub repository (a big one around 400mb with assets and `.git`). At  the modal window view
```
Importing from Wiki.js 1.x... 
please wait
``` 
after 4 minutes I have an error. In browser dev tools I see that request to `/graphql ` has time outed. 

**To Reproduce**
1. Install `wikijs` v2 with docker-compose file from https://docs.requarks.io/install/docker
2. Create an admin user
3. In the `UI -> Settings ->utilities -> Import from v1.x ` choose `Import from git connection` (leave `users` migration unchecked)
3. Input ssh-key, git URL (repo from old v1 `git@github.com:name:repo.git`; repo should be large), default user and email, data folder
4. Click `Start Import`

**Expected behavior**
- Install wiki js v2
- Started GIT data storage migration `utilities` -> `Import from v1.x` and depending on size of the repo it does the migration without timeouts from the web UI side 

**Host Info (please complete the following information):**
 - OS: Mac OS, Docker
- Browser: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Docker-compoer:
 ```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
        - wiki-data:/wiki

volumes:
  db-data:
  wiki-data:
```
