### DISCUSSION TITLE
using file for db pass in config.yml

### DISCUSSION THREAD

**Discussion by vwlau** [requarks/wiki#3920] [Help / Questions]
I followed the "Install on Ubuntu 18.04 / 20.04 LTS" guide which set up the PostgreSQL db using a password stored in a file /etc/wiki/.db-secret . 

Now, I'm trying to use a configuration file to run the docker container but haven't figured out how to give the db password via config.yml .

Here is what I tried in the config.yaml

```
db:
  type: postgres

  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: localhost
  port: 5432
  user: wiki
  pass: /etc/wiki/.db-secret
  db: wiki
  ssl: false
```
Here is the command I'm starting my docker container with

`docker run -d -p 3000:3000 -p 3443:3443 -h wiki --network=wikinet --name wiki --restart unless-stopped -e UPGRADE_COMPANION=1 -v /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro -v ~/wiki/config.yml:/wiki/config.yml requarks/wiki:2`
