### DISCUSSION TITLE
Login: An unexpected error occurred.

### DISCUSSION THREAD

**Discussion by talesam** [requarks/wiki#4139] [Error / Bug Report]
Once I have done the installation, the following screen appears:
![Captura de tela de 2021-06-26 00-23-23](https://user-images.githubusercontent.com/981368/123500514-fb601480-d614-11eb-93ef-9c4051446c9b.png)

#### docker-compose.yml

```
version: "3.9"
services:

   db:
      image: postgres:11-alpine
      container_name: wiki_db
      environment:
         POSTGRES_DB: wiki
         POSTGRES_PASSWORD: password
         POSTGRES_USER: wikijs
      logging:
         driver: "none"
      restart: unless-stopped
      volumes:
         - ./volumes/db-data:/var/lib/postgresql/data

   wiki:
      image: requarks/wiki:2.5
      container_name: wiki
      depends_on:
         - db
      environment:
         DB_TYPE: postgres
         DB_HOST: db
         DB_PORT: 5432
         DB_USER: wikijs
         DB_PASS: password
         DB_NAME: wiki
      restart: unless-stopped
      expose:
         - "3000"

networks:
   default:
      external:
         name: nginxproxymanager_default
```

#### docker-compose up -d

```
[tales@t4l35 Wiki.js]$ docker-compose up -d
Pulling wiki (requarks/wiki:2.5)...
2.5: Pulling from requarks/wiki
9b794450f7b6: Pull complete
8a7c7cc6b1b5: Pull complete
18a11c341c94: Pull complete
39d3ce655894: Pull complete
f8d13de11cbb: Pull complete
4f4fb700ef54: Pull complete
7e1afe4260b7: Pull complete
10204f4acbf4: Pull complete
d8034c388ae0: Pull complete
406ff80a275b: Pull complete
ab61ed7a3d8a: Pull complete
30e27a4f6c07: Pull complete
ac7f20c066ea: Pull complete
Digest: sha256:ede7a9c09e0e99771e469f06c78ec42fea0e415f68b5663e06ada24a83737676
Status: Downloaded newer image for requarks/wiki:2.5
Creating wiki_db ... done
Creating wiki    ... done
```

#### docker-compose ps

```
[tales@t4l35 Wiki.js]$ docker-compose ps
 Name                Command               State         Ports       
---------------------------------------------------------------------
wiki      docker-entrypoint.sh node  ...   Up      3000/tcp, 3443/tcp
wiki_db   docker-entrypoint.sh postgres    Up      5432/tcp   
```

#### docker-compose logs

```
[tales@t4l35 Wiki.js]$ docker-compose logs
Attaching to wiki, wiki_db
wiki    | Loading configuration from /wiki/config.yml... OK
wiki    | 2021-06-26T03:11:29.678Z [MASTER] info: =======================================
wiki    | 2021-06-26T03:11:29.681Z [MASTER] info: = Wiki.js 2.5.201 =====================
wiki    | 2021-06-26T03:11:29.681Z [MASTER] info: =======================================
wiki    | 2021-06-26T03:11:29.681Z [MASTER] info: Initializing...
wiki    | 2021-06-26T03:11:30.386Z [MASTER] info: Using database driver pg for postgres [ OK ]
wiki    | 2021-06-26T03:11:30.391Z [MASTER] info: Connecting to database...
wiki    | 2021-06-26T03:11:30.402Z [MASTER] error: Database Connection Error: ECONNREFUSED 192.168.16.7:5432
wiki    | 2021-06-26T03:11:30.403Z [MASTER] warn: Will retry in 3 seconds... [Attempt 1 of 10]
wiki    | 2021-06-26T03:11:33.407Z [MASTER] info: Connecting to database...
wiki    | 2021-06-26T03:11:33.410Z [MASTER] error: Database Connection Error: ECONNREFUSED 192.168.16.7:5432
wiki    | 2021-06-26T03:11:33.410Z [MASTER] warn: Will retry in 3 seconds... [Attempt 2 of 10]
wiki    | 2021-06-26T03:11:36.414Z [MASTER] info: Connecting to database...
wiki    | 2021-06-26T03:11:36.417Z [MASTER] error: Database Connection Error: ECONNREFUSED 192.168.16.7:5432
wiki    | 2021-06-26T03:11:36.417Z [MASTER] warn: Will retry in 3 seconds... [Attempt 3 of 10]
wiki    | 2021-06-26T03:11:39.419Z [MASTER] info: Connecting to database...
wiki    | 2021-06-26T03:11:39.439Z [MASTER] info: Database Connection Successful [ OK ]
wiki    | 2021-06-26T03:11:39.814Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
wiki    | 2021-06-26T03:11:39.815Z [MASTER] info: Starting setup wizard...
wiki    | 2021-06-26T03:11:39.990Z [MASTER] info: Starting HTTP server on port 3000...
wiki    | 2021-06-26T03:11:39.990Z [MASTER] info: HTTP Server on port: [ 3000 ]
wiki    | 2021-06-26T03:11:39.994Z [MASTER] info: HTTP Server: [ RUNNING ]
wiki    | 2021-06-26T03:11:39.995Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
wiki    | 2021-06-26T03:11:39.995Z [MASTER] info: 
wiki    | 2021-06-26T03:11:39.995Z [MASTER] info: Browse to http://YOUR-SERVER-IP:3000/ to complete setup!
wiki    | 2021-06-26T03:11:39.995Z [MASTER] info: 
wiki    | 2021-06-26T03:11:39.995Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
```
