### DISCUSSION TITLE
SSL will not work, server never loads with no errors

### DISCUSSION THREAD

**Discussion by 6XGate** [requarks/wiki#4168] [Error / Bug Report]
I'm attempting to use WikiJS in docker using a custom SSL certificate-key pair. The server never starts on the SSL port.

The container log just shows:
```
Loading configuration from /wiki/config.yml... OK
DB_PASS_FILE is defined. Will use secret from file.
[MASTER] info: =======================================
[MASTER] info: = Wiki.js 2.5.201 =====================
[MASTER] info: =======================================
[MASTER] info: Initializing...
[MASTER] info: Using database driver mysql2 for mysql [ OK ]
[MASTER] info: Connecting to database...
[MASTER] info: Database Connection Successful [ OK ]
[MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
[MASTER] info: Starting setup wizard...
[MASTER] info: Starting HTTP server on port 3000...
[MASTER] info: HTTP Server on port: [ 3000 ]
[MASTER] info: HTTP Server: [ RUNNING ]
[MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
[MASTER] info: 
[MASTER] info: Browse to http://YOUR-SERVER-IP:3000/ to complete setup!
[MASTER] info: 
[MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
```
My config file is as follows:
```
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: custom
  format: pem
  key: $(SSL_KEY_FILE)
  cert: $(SSL_CERT_FILE)
logLevel: info
ha: $(HA_ACTIVE)
```

I do have the appropirate variables set as follows:

DB_HOST | wikidb
-- | --
DB_NAME | wiki
DB_PASS_FILE | /run/secrets/my_sql_pwd
DB_PORT | 3306
DB_TYPE | mysql
DB_USER | wiki
NODE_VERSION | 14.16.0
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SSL_ACTIVE | true
SSL_CERT_FILE | /wiki/certs/localplex.crt
SSL_KEY_FILE | /wiki/certs/localplex.key
YARN_VERSION | 1.22.5
