### DISCUSSION TITLE
helm chart - Wrong value mapping from 'values.yaml' file to 'deployment.yaml' for imagePullPolicy

### DISCUSSION THREAD

**Discussion by wjkw1** [requarks/wiki#4231] [Error / Bug Report]
# Problem
The mapping between [values.yaml](https://github.com/Requarks/wiki/blob/dev/dev/helm/values.yaml) file and [templates/deployment.yaml](https://github.com/Requarks/wiki/blob/dev/dev/helm/templates/deployment.yaml) file do not match for **imagePullPolicy**. Values file uses pullPolicy, whilst Deployment file uses imagePullPolicy.

This means that if we update the pull policy in the **values.yaml** file it will never actually update the **deployment.yaml** file, thus continue using the default value of **IfNotPresent**

## Example of error:

https://github.com/Requarks/wiki/blob/dev/dev/helm/values.yaml
https://github.com/Requarks/wiki/blob/4b354c5347d13e53f5c0e683aaec411b4a1d89dd/dev/helm/values.yaml#L9
```yaml
image:
  repository: requarks/wiki
  pullPolicy: IfNotPresent
```

https://github.com/Requarks/wiki/blob/4b354c5347d13e53f5c0e683aaec411b4a1d89dd/dev/helm/templates/deployment.yaml#L29

```yaml
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.imagePullPolicy }}
```

----

# Fix
Update values.yaml file to below:

https://github.com/Requarks/wiki/blob/dev/dev/helm/values.yaml
```yaml
image:
  repository: requarks/wiki
  imagePullPolicy: IfNotPresent
```
