### DISCUSSION TITLE
warn: (LETSENCRYPT) Error: self signed certificate

### DISCUSSION THREAD

**Discussion by Sleevezipper87** [requarks/wiki#4234] [Error / Bug Report] [answered]
Hi!

I'm running Wiki JS using docker-compose and this works great. I'm using the following docker-compose.yml:

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: [redacted]
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: [redacted]
      DB_NAME: wiki
      SSL_ACTIVE: 0
      LETSENCRYPT_DOMAIN: [redacted]
      LETSENCRYPT_EMAIL: [redacted]
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3443:3443"

volumes:
  db-data:
```
I want to enable SSL so I have opened the needed ports and set `SSL_ACTIVE` to `1`. After running `docker-compose up` I now get the following output:

```
wiki_1  | Loading configuration from /wiki/config.yml... OK
wiki_1  | 2021-07-23T15:52:07.935Z [MASTER] info: =======================================
wiki_1  | 2021-07-23T15:52:07.937Z [MASTER] info: = Wiki.js 2.5.201 =====================
wiki_1  | 2021-07-23T15:52:07.937Z [MASTER] info: =======================================
wiki_1  | 2021-07-23T15:52:07.938Z [MASTER] info: Initializing...
wiki_1  | 2021-07-23T15:52:08.633Z [MASTER] info: Using database driver pg for postgres [ OK ]
wiki_1  | 2021-07-23T15:52:08.638Z [MASTER] info: Connecting to database...
wiki_1  | 2021-07-23T15:52:08.662Z [MASTER] info: Database Connection Successful [ OK ]
wiki_1  | 2021-07-23T15:52:09.371Z [MASTER] warn: Mail is not setup! Please set the configuration in the administration area!
wiki_1  | 2021-07-23T15:52:09.487Z [MASTER] info: Loading GraphQL Schema...
wiki_1  | 2021-07-23T15:52:10.285Z [MASTER] info: GraphQL Schema: [ OK ]
wiki_1  | 2021-07-23T15:52:10.578Z [MASTER] info: HTTP Server on port: [ 3000 ]
wiki_1  | 2021-07-23T15:52:10.624Z [MASTER] info: (LETSENCRYPT) Initializing Let's Encrypt client...
wiki_1  | 2021-07-23T15:52:10.648Z [MASTER] info: HTTP Server: [ RUNNING ]
wiki_1  | 2021-07-23T15:52:11.197Z [MASTER] info: (LETSENCRYPT) Generating server keypairs...
wiki_1  | 2021-07-23T15:52:11.360Z [MASTER] info: (LETSENCRYPT) Server keypairs generated successfully [ OK ]
wiki_1  | 2021-07-23T15:52:11.360Z [MASTER] info: (LETSENCRYPT) Generating certificate signing request (CSR)...
wiki_1  | 2021-07-23T15:52:11.368Z [MASTER] info: (LETSENCRYPT) CSR generated successfully [ OK ]
wiki_1  | 2021-07-23T15:52:11.368Z [MASTER] info: (LETSENCRYPT) Requesting certificate from Let's Encrypt...
wiki_1  | 2021-07-23T15:52:11.373Z [MASTER] info: (LETSENCRYPT) Setting HTTP challenge for [redacted]: [ READY ]
wiki_1  | 2021-07-23T15:52:11.374Z [MASTER] info: (LETSENCRYPT) Waiting for challenge to complete...
wiki_1  | 2021-07-23T15:52:16.622Z [MASTER] info: (LETSENCRYPT) Removing HTTP challenge: [ OK ]
wiki_1  | 2021-07-23T15:52:16.622Z [MASTER] info: (LETSENCRYPT) Removing HTTP challenge: [ OK ]
wiki_1  | 2021-07-23T15:52:16.622Z [MASTER] warn: (LETSENCRYPT) Error: self signed certificate
wiki_1  | 2021-07-23T15:52:16.623Z [MASTER] error: self signed certificate

```
After this it just exits and restarts.

This error makes no sense to me and I'm not able to Google my way out of it. Any ideas?
