### DISCUSSION TITLE
got dependency error after docker build

### DISCUSSION THREAD

**Discussion by mostafa8026** [requarks/wiki#4249] [Error / Bug Report] [answered]
I'm using dev/build/Dockerfile to build the project with this command:

```
at the root:
$ docker build . -t cnpr/wiki:latest -f dev/build/Dockerfile
```

build was successful, but after running the container it says:

```
Starting postgres ... done
Starting wiki     ... done
Attaching to postgres, wiki
postgres    |
postgres    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres    |
postgres    | 2021-07-27 04:47:24.551 GMT [1] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres    | 2021-07-27 04:47:24.551 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres    | 2021-07-27 04:47:24.551 GMT [1] LOG:  listening on IPv6 address "::", port 5432
postgres    | 2021-07-27 04:47:24.557 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres    | 2021-07-27 04:47:24.565 GMT [27] LOG:  database system was shut down at 2021-07-27 04:24:23 GMT
postgres    | 2021-07-27 04:47:24.575 GMT [1] LOG:  database system is ready to accept connections
wiki        | Loading configuration from /wiki/config.yml... OK
wiki        | 2021-07-27T04:47:24.713Z [MASTER] info: =======================================
wiki        | 2021-07-27T04:47:24.715Z [MASTER] info: = Wiki.js 2.0.0 =======================
wiki        | 2021-07-27T04:47:24.715Z [MASTER] info: =======================================
wiki        | 2021-07-27T04:47:24.715Z [MASTER] info: Initializing...
wiki        | 2021-07-27T04:47:25.090Z [MASTER] info: Using database driver pg for postgres [ OK ]
wiki        | 2021-07-27T04:47:25.093Z [MASTER] info: Connecting to database...
wiki        | 2021-07-27T04:47:25.123Z [MASTER] info: Database Connection Successful [ OK ]
wiki        | 2021-07-27T04:47:25.503Z [MASTER] warn: Mail is not setup! Please set the configuration in the administration area!
wiki        | 2021-07-27T04:47:25.505Z [MASTER] error: Cannot find module 'graphql-upload'
wiki        | Require stack:
wiki        | - /wiki/server/middlewares/upload.js
wiki        | - /wiki/node_modules/auto-load/lib/index.js
wiki        | - /wiki/server/core/db.js
wiki        | - /wiki/server/core/kernel.js
wiki        | - /wiki/server/index.js
```

my docker-compose:

```
version: '2'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pAsWoRd
    networks:
      - chapyar
  wiki:
    image: cnpr/wiki
    container_name: wiki
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: pAsWoRd
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "8030:3000"
    networks:
      - chapyar
networks:
  chapyar:
    external:
      name: chapyar
```
