### DISCUSSION TITLE
Can I change the sidebar size?

### DISCUSSION THREAD

**Discussion by theoratkin** [requarks/wiki#4507] [Help / Questions]
I tried to increase the sidebar width with the following CSS override:

```css
.v-navigation-drawer {
  width: 400px!important
}
```

But then it overlaps the page content.

And if I change the padding of the page so it doesn't overlap:

```css
.v-main {
  padding: 64px 0 0 400px!important
}
```

Then the editor is moved to the right as well.

Is there any way to change the sidebar size without breaking anything?
