### DISCUSSION TITLE
Can't install using Play With Docker

### DISCUSSION THREAD

**Discussion by shimizurei** [requarks/wiki#4741] [Help / Questions]
Please delete this discussion. This might be an issue with Play With Docker itself.

---

~How to recreate my scenario:~

~1. Open [Play With Docker](https://labs.play-with-docker.com) and log in with docker account
2. Create an instance
3. Type `mkdir data && touch docker-compose.yml` into terminal
4. Click editor and click `docker-compose.yml` file
4. Copy and paste `docker-compose.yml` data into created file
5. Go back to main screen terminal
6. Type `docker-compose up -d`
7. Port number (`80`) pops up next to words "OPEN PORT"
8. Click it.
9. [My issue] The site never loads~

~#### Docker-Compose File I'm Using~

```
~version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
```

~#### PWD-specific Docker-Compose File~

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /root/data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
```

~Also ran the following as well `docker logs root_db_1` and `docker logs root_wiki_1`:~

![Screenshot 2021-11-29 21 16 27](https://user-images.githubusercontent.com/3500094/143975821-33f28c8a-86a2-4036-8638-b26a28cbe0ef.png)

~I am unsure as to how to proceed. I use PWD to test every Dockerized program I'm interested in, from Mediawiki to WordPress to even Portainer itself. I have gotten all the aforementioned to work before, but not Wiki.js :(~
