### DISCUSSION TITLE
502 Bad Gateway - NGINX Reverse Proxy Manager + docker-compose (networks) on Linode

### DISCUSSION THREAD

**Discussion by Vinestou** [requarks/wiki#4746] [Help / Questions] [answered]
Hi guys,

I'm getting a 502 Bad Gateway when trying access wiki.js trough NGINX Proxy Manager in docker. Its running on a linode Ubuntu installation and im using docker networks to connect the container to the reverse proxy.

My compose-file:

```yaml
version: "3"
services:

  db:
    image: postgres:11-alpine
    container_name: wikijs_db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: XXXXXXXXXXX
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - default

  wiki:
    image: requarks/wiki:2
    container_name: wikijs
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: XXXXXXXXXXX
      DB_NAME: wiki
    restart: unless-stopped
    networks:
      - default
      - docker-npm

networks:
  default:
  docker-npm:
    external: true

```
Normally when adding the 'networks:' part tot the compose file I can add a proxy host to NGINX Proxy Manager with the container name and port 80 (http) and it works fine. The http port for wiki.js seems to be 3000 but I then get the 502 when I try to access it. See image below, all other host work and accessible trough the sub.domain

![nginx](https://user-images.githubusercontent.com/52471580/144326394-344696b4-ca54-49bb-9aa9-e6dbc66b065d.JPG)

Any tips on how to fix this?
