### DISCUSSION TITLE
Cannot mount nfs share from TrueNAS

### DISCUSSION THREAD

**Discussion by bitshiftnetau** [requarks/wiki#4761] [Error / Bug Report] [answered]
I am using the following docker-compose file:

```
version: '2'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: <pass>
      POSTGRES_USER: <user>
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: <user>
      DB_PASS: <pass>
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3030:3000"

volumes:
  db-data:
    driver_opts:
      type: nfs
      o: addr=10.0.20.90
      device: :/mnt/Media/nfs/wikijs/postgresql_data_db
```

And all I get is the following error:

```
Deployment error
failed to deploy a stack: Volume "wikijs_db-data" Creating Volume "wikijs_db-data" Created Container wikijs-db-1 Creating Error response from daemon: failed to chmod on /var/lib/docker/volumes/wikijs_db-data/_data: chmod /var/lib/docker/volumes/wikijs_db-data/_data: operation not permitted : exit status 1
```

My NFS share has the following options set:

- Enable NFSv4
- NFSv3 owership model for NFSv4
- Allow non-root mount
- /mnt/Media/nfs -alldirs -maproot="root":"wheel" -network ....

It should be noted that this NFS share works just fine with a non-stack docker-compose file, tested with Organizr. 

How do I add NFS share to this docker stack?

EDIT: I have since learnt that I'm trying to share postgresql over NFS which is a no-no, however I still wish to have my content backed up to TrueNAS. Surely this is possible and not at all edge-case, please advise.
