### DISCUSSION TITLE
Can't connect postgres after upgrade v14 (SCRAM password)

### DISCUSSION THREAD

**Discussion by dcpc007** [requarks/wiki#4773] [Help / Questions]
Hi, 

i have a wikijs in docker-compose.
I made the postgres upgrade until v14.
Locally all is good, and i can connect to the db internally

But wiki instance can't connect due to a SCRAM sha-256 mismatch if i understand.
I'm really not an expert on pgsql, and i didn't find special coniguration on the doc that seems to be related.
Any idea please ?

The docker-compose file (only data is midified)
```
version: "3"
services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: the_password
      POSTGRES_USER: wikijs
     logging:
        driver: "none"
    volumes:
      - '/srv/wikijs_v2/postgresql/data:/var/lib/postgresql/data'
#    networks:
#      - wikinet

  wiki:
    image: requarks/wiki:2
    restart: always
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: the_password
      DB_NAME: wiki
    volumes:
      - '/srv/wikijs_v2/keys:/srv/keys'
#    networks:
#      - wikinet
    ports:
      - "3000:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example

#networks:
#  wikinet:

volumes:
  db-data:
```

Any new method to write the password (like put an encoded version ?)
