### DISCUSSION TITLE
Helm install expects explicit password secret even when postgresqlPassword populated

### DISCUSSION THREAD

**Discussion by khetho** [requarks/wiki#4828] [Error / Bug Report]
I am installing wiki.js using helm. My helm configuration file is

```yaml
ingress:
  enabled: false
postgresql:
  enabled: false
  postgresqlDatabase: wikijs
  postgresqlUser: wikijs
  postgresqlHost: "wikijs.domain.com"
  postgresqlPassword: "password"
  postgresqlPort: 5432
```
The helm installation using the below command is successful
```
helm install wikijs -f wikijs-values.yaml requarks/wiki
```
However the pod refuses to come up with a Container Creation error highlighting that the secret wikijs could not be found. On manually creating the wikijs secret as per below I can however get the pod up and running.

```
kubectl create secret generic wikijs --from-literal=postgresql-password=password
```

My expectation was that if the password is explicitly provided in the helm configuration file, the chart would either use the value as specified therein or create the secret initially itself. However this seems to not be happening.

Here are the chart details after manually creating the secret.

```
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
wikijs  wiki            1               2021-12-26 13:47:08.714000529 +0000 UTC deployed        wiki-2.2.11     latest
```
