### DISCUSSION TITLE
Upload Not Completing

### DISCUSSION THREAD

**Discussion by ddlidded** [requarks/wiki#4830] [Error / Bug Report]
When uploading an image-based asset through the browse -> upload method, it gets to 100% but does not complete and does not get uploaded successfully.

When checking my application logs, this is a message that is displayed:
warn: Cannot read properties of undefined (reading 'toLowerCase')

If it helps, this issue was not occurring a day or two ago and was working fine.

Thanks in advance guys!

**Comment by ddlidded** [comment]
Now I am receiving the message "Error during upload"

**Reply by sanjibm** [reply]
Facing the exact same issue. 

There must be an easy way to enable more detailed logging to see whats going on.
Using docker compose following installation instructions from: 
https://docs.requarks.io/install/docker

Using this docker compose file:
```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:1.8
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "8085:3000"
    volumes:
      - /share/Document/wiki/config:/config
      - /share/Document/wiki/data:/data
      - /share/Document/wiki/backups:/backups

volumes:
  db-data:
```
