### DISCUSSION TITLE
tree navigation root name

### DISCUSSION THREAD

**Discussion by terafirmanz** [requarks/wiki#4888] [Error / Bug Report]
was wondering about the display name for root but not enough to open an issue or feature request.

When navigating via the tree view '/ sidebar.root' is confusing for non-technical people this should read simply '/' or  '/ Home' or whatever the name of the main default home page is.

**Comment by peteruithoven** [comment]
I've been bothered by this as well.

Where this line comes from:
https://github.com/requarks/wiki/blob/main/client/themes/default/components/nav-sidebar.vue#L225

I've installed the wiki follwing the [dev guide](https://docs.requarks.io/dev) and adding a `en.yml` to `server/locales/` with:
``` yml
common:
  sidebar.root: Home
```
It seems to try to use the translation when I save changes to this file:
```
2022-05-25T11:42:41.973Z [JOB] info: Rebuilding page tree: [ COMPLETED ]
2022-05-25T11:42:42.026Z [MASTER] info: Pulled latest locale updates for English from Graph endpoint: [ COMPLETED ]
2022-05-25T11:42:42.028Z [MASTER] info: Loaded dev locales from en.yml
2022-05-25T11:42:42.028Z [MASTER] info: Syncing locales with Graph endpoint: [ COMPLETED ]
```

But this doesn't seem to help.

**Reply by peteruithoven** [reply]
When I try adding some logging to the mounted handler I see:
```
this.$t('common:sidebar.root'):  sidebar.root
```
Which makes me thing the key is somehow not being found.

**Reply by peteruithoven** [reply]
Ah, when I request it after a delay it is available and contains: "(root)".

**Reply by peteruithoven** [reply]
Opened pull request: https://github.com/requarks/wiki/pull/5333

**Comment by j-tai** [comment]
Since the PR is not merged yet, you can use this hack to fix it on your instance:

```css
nav div.v-list.v-sheet.primary > div:first-child[style] > .v-list-item__title {
  visibility: hidden;
  position: relative
}
nav div.v-list.v-sheet.primary > div:first-child[style] > .v-list-item__title::after {
  content: '/ (root)';
  visibility: visible;
  display: block;
  position: absolute;
  top: 0
}
```

Add that code to Administration > Theme > CSS Override.
