### DISCUSSION TITLE
[Docker] Wiki doesn't update config when env vars change

### DISCUSSION THREAD

**Discussion by filcuk** [requarks/wiki#5004] [Error / Bug Report] [answered]
I've found that upon updating `DB_HOST`, wiki couldn't connect to the database.
It turns out that `config/config.yml` contained the old `DB_HOST` value.
It worked fine once I updated config.yml manually.

I'm not sure if this is intended, but I havnen't found anything mentioned in documentation.

**Comment by NGPixel** [comment, marked as answer]
Did you restart the container after making the change? There's no need to hardcode any value in config.yml

**Reply by filcuk** [reply]
I did restart a few times, as I wasn't sure what the issue was at first.
Wiki was failing to connect until the host name in config was updated manually (& restarted).

I have just tested this again on `linuxserver/wikijs:2.5.275`:
1. Stop wiki
2. Remove `wiki-db` container
3. Change `wiki-db` to `wiki-db1` in compose (incl. vars etc.)
4. `docker-compose -up`

Wiki log:
```
2022-02-20T06:29:43.836Z [MASTER] info: =======================================
2022-02-20T06:29:43.839Z [MASTER] info: = Wiki.js 2.5.275 =====================
2022-02-20T06:29:43.839Z [MASTER] info: =======================================
2022-02-20T06:29:43.839Z [MASTER] info: Initializing...
2022-02-20T06:29:44.752Z [MASTER] info: Using database driver pg for postgres [ OK ]
2022-02-20T06:29:44.759Z [MASTER] info: Connecting to database...
2022-02-20T06:29:44.773Z [MASTER] error: Database Connection Error: ENOTFOUND undefined:undefined
```

Wiki config:
```yml
db:
  type: postgres

  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: wiki-db
```

.env:
```
WIKI_DB_HOST=wiki-db1
```

docker-compose.yml:
```
wiki:
...
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DB_TYPE=postgres
      - DB_HOST=$WIKI_DB_HOST
      - DB_PORT=$WIKI_DB_PORT
      - DB_USER=$WIKI_DB_USER
      - FILE__DB_PASS=/run/secrets/wiki_db_password
      - DB_NAME=$WIKI_DB_NAME
    volumes:
      - $DOCKERDIR/appdata/wiki/config:/config:rw
      - $DOCKERDIR/appdata/wiki/data:/data:rw
    secrets:
      - wiki_db_password
```

The config file has `-rwxrwxrwx` permissions user & group as specified in env vars.
