### DISCUSSION TITLE
KaTeX matrix not rendering correctly

### DISCUSSION THREAD

**Discussion by Turakar** [requarks/wiki#5030] [Error / Bug Report]
The following matrix, entered in markdown mode, renders incorrectly:

```
$$W = \begin{pmatrix} w_{10} & \cdots & w_{K0} \\ \vdots & \ddots & \vdots \\ w_{1D} & \cdots & w_{KD} \end{pmatrix}$$
```

Namely, like this (both in preview and rendered):

![incorrect rendering with black bars](https://user-images.githubusercontent.com/3958680/154798687-624661cb-448d-4f7e-a8e1-161ff7280309.png)

As a workaround, I can add the following CSS to the page:

```css
.katex .rule {
  border: none;
  background-color: transparent
}
```
