### DISCUSSION TITLE
TOC position on the right side

### DISCUSSION THREAD

**Discussion by luwol03** [requarks/wiki#5171] [Guides]
Hey,

it always looked very bloated if the Table of contents is directly next to the sidebar. I'd love to have the ability to move the TOC to the right, right now. So I decided to build bunch of CSS rules to implement that right now. I now wanted to share that with you.

```css
#app > div.v-application--wrap > main > div > div.container.pl-5.pt-4.container--fluid.grid-list-xl > div {
  flex-direction: row-reverse
}
.v-application--is-ltr .offset-xl-2 {
  margin-left: 0 !important
}
.v-application--is-ltr .offset-lg-3 {
  margin-left: 0 !important
}
```
