### DISCUSSION TITLE
sessionSecret not present in config.yaml in production Dockerfile

### DISCUSSION THREAD

**Discussion by dasantonym** [requarks/wiki#5182] [Error / Bug Report]
I have a running setup on Docker (image `requarks/wiki:2`, just pulled it again and restarted container) and it was working fine until a few days ago I was suddenly faced with the error `secret option required for sessions`.

The `config.yaml` in the container looks like this:

```yaml
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: letsencrypt
  domain: $(LETSENCRYPT_DOMAIN)
  subscriberEmail: $(LETSENCRYPT_EMAIL)
logLevel: $(LOG_LEVEL:info)
logFormat: $(LOG_FORMAT:default)
ha: $(HA_ACTIVE)
```

Same as in the current source at https://github.com/requarks/wiki/blob/main/dev/build/config.yml, but I wonder how this was supposed to work before. Does the secret come from the DB and is mine corrupted somehow? `sessionSecret` is specified as required in the docs.

Before I throw away the data and set the wiki up again, I just wanted to make sure this won't "randomly" happen again later.

Any advice on where to look for more clues?
