### DISCUSSION TITLE
Installation manual for total idiots

### DISCUSSION THREAD

**Discussion by t314r** [requarks/wiki#5384] [Help / Questions] [answered]
First of all a big **thank you** for Wiki.js / Manual that is already written / your additional support.

I went through your [installation manual](https://docs.requarks.io/install), you have prepared for all willing to run your Wiki.js application.

But honestly - it's written for people that have certain degree of computer skills (higher level) and not for **t̶o̶t̶a̶l̶ ̶i̶d̶i̶o̶t̶s̶** the rest of us.
As a complete noob - I am missing **many** informations that will help me with the installation process -preferably [installing on MAC](https://docs.requarks.io/install/macos) (Windows alternatively).

Is there somebody in the community considering to make a step-by-step manual (or youtube video) how to install Wiki.js application locally on your MAC or PC (**not using tools like docker**, **heroku** or **kubernetes**)?

Your feedback is very appreciated. Thank you.

**Comment by anubi** [comment]
So, I would say this...that if you're going to administrate wiki.js even just on your local computer, you should learn a few things, because otherwise you MAY build up a super cool wiki...that you lose forever. You need to learn how to backup and manage your data wisely so you don't lose your wiki after pouring effort into it. Not sure how you can get those technical skills fast, but you should be wary of operating the wiki blind.

And...the *most* braindead way you can achieve wiki.js on a local PC is through docker. Period. If you don't want to use docker for some reason, you need to get more savvy or get a computer that can run docker. -All- you need to do to run it in docker on your local machine is 

A) install docker desktop for windows 
B) register a docker account 
C) create a blank text file called docker-compose.yaml in an empty directory on your desktop called 'wiki'
D) paste the contents under "Using Docker Compose" at https://docs.requarks.io/install/docker into docker-compose.yaml (don't change anything)
E) windows start menu > type in 'cmd.exe'
F) inside the cmd.exe window, type in 'cd C:/users/your user/desktop/wiki' then type 'docker-compose up -d'

You're done. The wiki is running.

**Comment by NGPixel** [comment, marked as answer]
You mention "not using tools like docker", even though Docker makes the whole installation much simpler.

For macOS:

- Install Docker Desktop (https://www.docker.com/products/docker-desktop/)
- Create a folder somewhere and create a file inside named "docker-compose.yaml", paste the following contents:
```yaml
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
```
- From the Terminal, navigate to the folder you created earlier and run the command `docker compose up -d`

You'll now have a wiki running at http://localhost
