### DISCUSSION TITLE
Unknown authentication strategy "jwt" with wiki.js in docker and nginx proxy

### DISCUSSION THREAD

**Discussion by lallish** [requarks/wiki#5409] [Error / Bug Report] [answered]
Hello!

I receive this error page during installation phase right after I've entered admin details, and eventhough troubleshooting tells you just to reload the site when `Unknown authentication strategy "jwt"` occurs, reloading does not solve the issue.

![tempsnip](https://user-images.githubusercontent.com/3920385/173820887-2d7f9695-6484-4dc3-a445-f84bbf177edb.png)

I run wiki.js 2.5 in docker on an arm64 machine pointed at RDS database in AWS.

wiki config.yml:
```
port: 8443

db:
  type: mysql

  host: <snipped>
  port: 3306
  user: <snipped>
  pass: <snipped>
  db: <snipped>
  ssl: false

ssl:
  enabled: true
  port: 8443
  provider: letsencrypt
  format: pem
  key: /etc/letsencrypt/live/<snipped>/privkey.pem
  cert: /etc/letsencrypt/live/<snipped>/cert.pem
  dhparam: null
  domain: <snipped>.cloud
  subscriberEmail: <snipped>

pool:
  # min: 2
  # max: 10
bindIP: 0.0.0.0
logLevel: info
logFormat: default
offline: false
ha: false
dataPath: ./data
bodyParserLimit: 5mb
```

Start command:
`sudo docker run -d -p 8443:8443 --name wiki --restart always -v /etc/wiki/config.yml:/wiki/config.yml requarks/wiki:2.5`

Nginx.conf:
```
events {
    worker_connections        1024;
}

http {

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name <snipped>.cloud;

        # ssl
        ssl_certificate            /etc/letsencrypt/live/<snipped>.cloud/cert.pem;
        ssl_certificate_key        /etc/letsencrypt/live/<snipped>.cloud/privkey.pem;

        ssl_session_timeout 1d;
        ssl_session_tickets off;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH EDH+aRSA !RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://localhost:8443;
            proxy_set_header X_FORWARDED_PROTO https;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header  X-Url-Scheme $scheme;
        }

        location /.well-known/acme-challenge {
                allow all;
                root /var/www/certbot/;
        }
    }

    server {
        listen 80;
        # listen [::]:80;
        server_name <snipped>.cloud;

        location /.well-known/acme-challenge {
                allow all;
                root /var/www/certbot/;
        }

        return 301 https://$host$request_uri;
    }
}
```

Any ideas why this error blocks me from entering the wiki?
