### DISCUSSION TITLE
File Upload fails though file size is way below configured file size limit

### DISCUSSION THREAD

**Discussion by ascheucher** [requarks/wiki#5419] [Error / Bug Report]
Hello,

first: thanks for sharing this great tool as open source!

To the problem:
Setup with docker running since months without problem. nginx as reverse proxy in front of the wiki installation.
Uploading media assets works, but not for [this certain PDF file](https://www.canyon.com/on/demandware.static/-/Library-Sites-canyon-shared/default/dw4f0c7fdd/explosiondrawings/2013/nerve/M13-13_BOM_ts.pdf).

I updated the wiki to the latest version and validated it in the Admin / System Info panel to be 2.5.284.

Logfile from nginx:
```
10.116.0.109 - - [21/Jun/2022:15:53:30 +0000] "POST /graphql HTTP/1.1" 200 915 "https://wiki-2.mfg.domain.cc/e/en/vehicles/canyon-fully-neu" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "-"
2022/06/21 15:53:38 [error] 8#8: *1 client intended to send too large body: 2601080 bytes, client: 10.116.0.109, server: wiki-2.mfg.domain.cc, request: "POST /u HTTP/1.1", host: "wiki-2.mfg.domain.cc", referrer: "https://wiki-2.mfg.domain.cc/e/en/vehicles/canyon-fully-neu"
10.116.0.109 - - [21/Jun/2022:15:53:38 +0000] "POST /u HTTP/1.1" 413 585 "https://wiki-2.mfg.domain.cc/e/en/vehicles/canyon-fully-neu" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "-"
```

The configured max file size in Admin / Security / Max Upload Size is: 10485760 bytes

My config.yml:
```
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: letsencrypt
  domain: $(LETSENCRYPT_DOMAIN)
  subscriberEmail: $(LETSENCRYPT_EMAIL)
  logLevel: $(LOG_LEVEL:debug)
logFormat: $(LOG_FORMAT:default)
ha: $(HA_ACTIVE)
```

My docker-compose.yml:
```
version: "3"
services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  # from here: https://medium.com/@TimvanBaarsen/how-to-run-an-elasticsearch-7-x-single-node-cluster-for-local-development-using-docker-compose-2b7ab73d8b82
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: wiki-js-2-elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - wiki-js-2-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: wiki-js-2-kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  db:
    image: postgres:11-alpine
    container_name: wiki-js-2-postgres
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: json-file
    restart: unless-stopped
    volumes:
      - wiki-js-2-db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki-js-2-server
    depends_on:
      - db
      - elasticsearch
    environment:
      LOG_LEVEL: debug
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    volumes:
      - ./config.yml:/wiki/config.yml
      - wiki-js-2-data:/wiki/data
    #ports:
      #- "80:3000"

volumes:
  wiki-js-2-elasticsearch-data:
    external:
      name: wiki-js-2-elasticsearch-data
  wiki-js-2-db-data:
    external:
      name: wiki-js-2-db-data
  wiki-js-2-data:
    external:
      name: wiki-js-2-data

networks:
  default:
    external:
      name: the-docker-net
```

the relevant nginx.conf part:
```
user  nginx;
worker_processes  3;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;



events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    ############################################
    # services to SSL terminate
    ############################################


    # upgrade websocket connections following: https://www.nginx.com/blog/websocket-nginx/
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    ############################################
    # wiki-2 section
    upstream wiki-2-websocket-http {
        # TODO switch back to docker network forwarding
        server wiki-js-2-server:3000;
    }

    server {
        listen 80;
        server_name wiki-2.mfg.domain.cc;
        return 301 https://$server_name$request_uri;
    }

    server {
        listen               443 ssl;
        server_name           wiki-2.mfg.domain.cc;

        ssl_certificate       /etc/letsencrypt/live/wiki-2.mfg.domain.cc/fullchain.pem;
        ssl_certificate_key   /etc/letsencrypt/live/wiki-2.mfg.domain.cc/privkey.pem;
        ssl_protocols         SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers           HIGH:!aNULL:!MD5;
        ssl_session_cache     shared:SSL:2m;

        proxy_connect_timeout       120;
        proxy_send_timeout          120;
        proxy_read_timeout          120;
        send_timeout                120;


        location / {
            proxy_pass http://wiki-2-websocket-http;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
     }
}
```
