### DISCUSSION TITLE
Help importing backup file

### DISCUSSION THREAD

**Discussion by beckyboop123** [requarks/wiki#5688] [Help / Questions]
OS: CentOS 8
Wiki.js version: 2.5.289
Database engine: SQLite 3.38.3

I have a full backup from an old wiki.js instance which is compressed in .gz format. If I expand it its in tar format.

I have attempted to import it into my new wiki.js instance but placing it in /backups and configuring wiki to look at this location as a target in the local file system area. If I then run a full import from that location, nothing appears.

Should my backup file that I am trying to restore be in a different format or not compressed?

This is my Docker settings:
```
wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /etc/wiki:/config
      - /opt/wiki:/data
      - /tmp/wikijs/uploads:/backups
    ports:
      - 3000:3000
    restart: unless-stopped
```
 Is there a better way to restore this backup?
