### DISCUSSION TITLE
How to style lists (`<ul>`)?

### DISCUSSION THREAD

**Discussion by dserodio** [requarks/wiki#5745] [Help / Questions]
Currently, unordered lists uses a small triangle (`▸`) before each element, which reminds me of an icon to expand a section (similar to the `<summary>` tag).
I'd like it the be a "bullet" like `•`, the default for the `list-style-type` CSS property. How can I achieve this? Thanks!

**Comment by bronf** [comment]
I tried various things without success:

- add `list-style-type: square;` or `list-style-type: circle;` to `<ul>` tag
- redefine `li::before { content: "BULLET"; }` but it gets overriden by `theme0.xxxx.css`

**Comment by Ik1497** [comment]
You would need to add this:
```css
.v-main .contents ul:not(.tabset-tabs):not(.contains-task-list)>li:before {
    content: "";
}

.v-main .contents ul:not(.tabset-tabs):not(.contains-task-list) {
    list-style: circle;
}
```
The reason why this below ***won't work*** is because CSS has specificity, so you need to be more/as specific as how the CSS is set in `theme0.xxxx.css`
```css
ul {
    list-style: circle;
}

**Comment by bronf** [comment]
Thank you for your explanation. I managed to get what I wanted with the following code:
```css
.v-main .contents ul:not(.tabset-tabs):not(.contains-task-list) {
    color: #000000;
}
.v-main .contents ul:not(.tabset-tabs):not(.contains-task-list)>li:before {
    content: "◼";
    color: #00a9e0;
}
.v-main .contents ul:not(.tabset-tabs):not(.contains-task-list) ul {
    color: #00a9e0;
}
.v-main .contents ul:not(.tabset-tabs):not(.contains-task-list) ul>li:before {
    content: "▶";
    color: #00a9e0;
}
.v-main .contents ul:not(.tabset-tabs):not(.contains-task-list) ul ul {
    color: #000000;
}
.v-main .contents ul:not(.tabset-tabs):not(.contains-task-list) ul ul>li:before {
    content: "■";
    font-size: 60%;
    color: #000000;
}
```
