### DISCUSSION TITLE
`.v-application .overline` collides with KaTeX `\overline`

### DISCUSSION THREAD

**Discussion by cannorin** [requarks/wiki#5834] [Error / Bug Report] [answered]
KaTeX uses `class="mord overline"` to render `$\overline{..}$`.

However, the inline CSS specifies the followings:

```css
.v-application .overline {
 font-size:.75rem!important;
 font-weight:500;
 letter-spacing:.1666666667em!important;
 line-height:2rem;
 text-transform:uppercase;
 font-family:Roboto,sans-serif!important
}
```

As a result, `$\underline{Foo}, \overline{Bar}$` is rendered like this:

![firefox_aCvRDIYziQ](https://user-images.githubusercontent.com/13620400/201385947-acc6e847-8036-4bf5-bc09-6b10268edc7a.png)

Which should look like the same except for the position of the line.

**Comment by cannorin** [comment, marked as answer]
Also, here is the workaround:

```css
#root .v-application .katex .overline {
  font-family: KaTeX_Main,Times New Roman,serif !important;
  font-size: inherit !important;
  font-weight: normal !important;
  line-height: inherit !important;
  letter-spacing: inherit !important;
  text-transform: none !important;
}
```

Paste this to either `Admin > Site > Theme > Code Injection > CSS Override`, or the page-wide custom CSS.
