### DISCUSSION TITLE
Export with docker ?

### DISCUSSION THREAD

**Discussion by aphshir** [requarks/wiki#5888] [Help / Questions]
Hi ! 
I would like to export the wiki. I'm using docker but I don't see where is the exported data. there is noting in the folder were is docker-compose.yaml. And I'm unable to find the installation folder of wiki.js.
I'm using windows 10. and I ran this docker compose file:

```yml
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
```

any ideas ?
