### DISCUSSION TITLE
Code blocks within blockquote are not displayed correct

### DISCUSSION THREAD

**Discussion by uyu423** [requarks/wiki#5894] [Error / Bug Report]
## Summary

- Hello
- I often write code within blockquotes.
- But, Blocks of code within a blockquote with `.is-info`, `.is-success`, `.is-warning`, and `.is-danger` color schemes do not display correctly.

## Screenshot and markdown

<img width="862" alt="image" src="https://user-images.githubusercontent.com/8033320/204054420-e399d400-369c-4215-bbaa-2528024937dc.png">

```md
> is
> ```
> console.log("can you read this?");
> ```
> default

> is
> ```
> console.log("can you read this?");
> ```
> info
{.is-info}

> is
> ```
> console.log("can you read this?");
> ```
> success
{.is-success}

> is
> ```
> console.log("can you read this?");
> ```
> warning
{.is-warning}

> is
> ```
> console.log("can you read this?");
> ```
> danger
{.is-danger}
```

## interim measures

- Paste the css below in Admin - Themes - Custom CSS.

```css
.v-main .contents blockquote.is-info code {
  background-color: unset;
  color: unset
}
.v-main .contents blockquote.is-warning code {
  background-color: unset;
  color: unset
}
.v-main .contents blockquote.is-success code {
  background-color: unset;
  color: unset
}
.v-main .contents blockquote.is-danger code {
  background-color: unset;
  color: unset
}
```

**Comment by uyu423** [comment]
Pull Request: https://github.com/requarks/wiki/pull/5895

**Comment by Nyxtorm** [comment]
Hi @uyu423,

Thanks for sharing this tip. I propose a small improvement to not include inline code :

```css
.v-main .contents blockquote.is-danger code[class^="language-"] {
  background-color: unset;
  color: unset;
}
.v-main .contents blockquote.is-info code[class^="language-"] {
  background-color: unset;
  color: unset;
}
.v-main .contents blockquote.is-success code[class^="language-"] {
  background-color: unset;
  color: unset;
}
.v-main .contents blockquote.is-warning code[class^="language-"] {
  background-color: unset;
  color: unset;
}
```

Before :

![](https://i.imgur.com/gDv1I59.png)

After :

![](https://i.imgur.com/zpNVYsD.png)
