### DISCUSSION TITLE
Successfull OIDC (Authelia) login results in "Invalid email / username or password"

### DISCUSSION THREAD

**Discussion by foorschtbar** [requarks/wiki#5935] [Error / Bug Report] [answered]
Successfull ODIC logins results in a `Invalid email / username or password.` (HTTP 500) result:

![grafik](https://user-images.githubusercontent.com/10727275/206247952-8362604f-3891-4e45-bdbf-8b75659c9209.png)

I configured OIDC agains Authelia. I checked #5810 and https://github.com/authelia/authelia/issues/3148 but it think its a wiki.js issue.

## My Setup

Wiki.js:
```yml
Type: Generic OpenID Connect / OAuth2
Application Client ID: wikijs
Application Client Secret: XXX
Application Authorization Endpoint URL: https://auth.XXX/api/oidc/authorization
Application Token Endpoint URL: https://auth.XXX/api/oidc/token
User Info Endpoint URL: https://auth.XXX/api/oidc/userinfo
Issuer URL: https://auth.XXX
Field containing the email address: email
Logout URL: https://auth.XXX/logout
```

Authelia:
```yml
[...]
  - id: wikijs  # this should be changed to something more secure
    description: Wiki.js
    secret: XXX
    public: false
    authorization_policy: two_factor
    audience: []
    scopes:
      - openid
      - email
      - profile
    redirect_uris:
      - https://wiki.XXX/login/XXX/callback
    response_modes:
      - form_post
    userinfo_signing_algorithm: none
```

## Logs

In Authelia everything looks good:
```
Authorization Request with id 'XXX' on client with id 'wikijs' is being processed" method=GET path=/api/oidc/authorize [...]
Authorization Request with id 'XXX' on client with id 'wikijs' using consent mode 'explicit' proceeding to generate a new consent session" method=GET path=/api/oidc/authorize [...]
Authorization Request with id 'XXX' on client with id 'wikijs' using consent mode 'explicit' authentication level 'two_factor' is sufficient for client level 'two_factor'" method=GET path=/api/oidc/authorize [...]
Authorization Request with id 'XXX' on client with id 'wikijs' using consent mode 'explicit' is being redirected to 'https://auth.XXX/consent?id=XXX'" method=GET path=/api/oidc/authorize [...]
Authorization Request with id 'XXX' on client with id 'wikijs' is being processed" method=GET path=/api/oidc/authorization [...]
Authorization Request with id 'XXX' on client with id 'wikijs' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization [...]
Access Request with id 'XXX' on client with id 'wikijs' is being processed" method=POST path=/api/oidc/token [...]
Access Request with id 'XXX' on client with id 'wikijs' has successfully been processed" method=POST path=/api/oidc/token [...]
```
Other OIDC logins agains Authelia works fine.
