### DISCUSSION TITLE
first impression: a butterfly with 80% cpu load

### DISCUSSION THREAD

**Discussion by milahu** [requarks/wiki#5948] [General]
this css is wasting my cpu

```css
.setup .v-application--wrap:before {
    /* ... */
    background-color: transparent;
    background-image: url(/_assets/svg/motif-grid.svg)!important;
    background-size: 100px;
    background-repeat: repeat;
    /* cpuburn ... */
    animation: bg-anim 100s linear infinite;
}
```

the animation isnt even pretty, its more like a css feature demo
"look what i can do on modern hardware"
