### DISCUSSION TITLE
Incognito TAB undesirable behavior

### DISCUSSION THREAD

**Discussion by jarbelix** [requarks/wiki#5950] [Error / Bug Report] [answered]
I usually use Google Chrome, Brave Browser, Mozilla Firefox in their incognito tabs to validate access to certain sites.

To my surprise on the Wiki that I installed via docker (https://wiki.tiozaodolinux.tk/) when I log in and open an incognito tab and press F5 I am still authenticated with the same user who authenticated previously.

It is VERY undesirable behavior.

The question is: does this anomaly only happen to me?

My configuration:

```
cat docker-compose.yml 

version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3000:3000"
```
