### DISCUSSION TITLE
Can't login - redirect loop to login page

### DISCUSSION THREAD

**Discussion by jeffshead** [requarks/wiki#5962] [Help / Questions] [answered]
I want my wiki to be private so I deactivated the stock allow rule for the guest group as described here: [private wiki](https://docs.requarks.io/en/groups#private-wiki)

Everything was working until I changed the login page background image. Now I keep being redirected back to the login page after entering the correct Admin login credentials. So I am essentially locked out. I'm assuming this is because I neglected to give the guest user group read permission to the new background image???

I installed wiki.js via Portainer (docker-compose) `image: ghcr.io/requarks/wiki:latest`
```yaml
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wikidb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:latest
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: password
      DB_NAME: wikidb
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:      
      - /path/to/favicon.ico:/wiki/assets/favicon.ico
      - /path/to/favicons:/wiki/assets/favicons

volumes:
  db-data:
networks:
  default:
    name: default
    external: true
```

How can I fix this without starting over from scratch?
