### DISCUSSION TITLE
[Locales] [Offline Mode] Weird labels in the form `string.otherstring` using web ui

### DISCUSSION THREAD

**Discussion by HuM4NoiD** [requarks/wiki#5965] [Help / Questions] [answered]
I am running wiki on a docker container on a machine where internet access is blocked.

This will lead to the following error:
```
2022-12-17T15:30:31.821Z [MASTER] error: Syncing locales with Graph endpoint: [ FAILED ]
2022-12-17T15:30:31.821Z [MASTER] error: request to https://graph.requarks.io failed, reason: self signed certificate in certificate chain
2022-12-17T15:30:31.824Z [MASTER] error: Fetching latest updates from Graph endpoint: [ FAILED ]
2022-12-17T15:30:31.824Z [MASTER] error: request to https://graph.requarks.io failed, reason: self signed certificate in certificate chain
```

This may be the cause for the issue that leads to pages showing weird labels/text for buttons/navigation items/input fields in the form `string.otherstring`.

What should I do to fix this?

Docker image requarks/wiki
Docker image version: 2.5

Edit:
I found a [link](https://docs.requarks.io/install/sideload) for sideloading, what should be the mount path for sideload?

**Comment by HuM4NoiD** [comment, marked as answer]
Found a fix:
Copied the config from within a running docker container of [requarks/wiki image](https://hub.docker.com/r/requarks/wiki) which looked like this:
```yaml
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: letsencrypt
  domain: $(LETSENCRYPT_DOMAIN)
  subscriberEmail: $(LETSENCRYPT_EMAIL)
logLevel: $(LOG_LEVEL:info)
logFormat: $(LOG_FORMAT:default)
ha: $(HA_ACTIVE)

# This property was added
offline: true
```

Get the locales from this  [this guide](https://docs.requarks.io/install/sideload)

and place the `locales.json` and required locale files in a suitable path e.g. `path/to/saved/locales/sideload`

then ran the docker container using the command:
```bash
docker run -d --rm --name wiki \
 -e ANY_OTHER_RELEVANT_ENV_VARS=value \
 -v path/to/saved/locales/sideload:/wiki/data/sideload \
 -p 3000:3000 \
 -v path/to/copied/config.yml:/wiki/config.yml \
 requarks/wiki:latest
```
