### DISCUSSION TITLE
HTML Upload Limit and Configurations

### DISCUSSION THREAD

**Discussion by tbonnerctps** [requarks/wiki#5990] [Help / Questions] [answered]
I've attempted to paste a large amount of HTML (9500 lines of code) into the HTML editor to create a page, and received the status code 413 error. The HTML file itself is about 6MB.  Is there an internal limit of sorts regarding HTML upload that I should be aware of? Are there any configuration options that would allow this amount of HTML to be used for a single page? I believe this might be hitting a sort of maximum entry size into PostgreSQL database but am not entirely sure. Any clarification is much appreciated.

**Comment by NGPixel** [comment, marked as answer]
You need to increase the bodyParserLimit value in your config.yml:

https://github.com/requarks/wiki/blob/main/config.sample.yml#L147

**Reply by tbonnerctps** [reply]
Thanks for the reply. My wiki was created point-and-click launching a pre-packaged Docker image that was provided by Digital Ocean, rather than by manually preparing a config.yml file and creating a Docker container from it. Do you happen to know if there is any way, and if so how, I can change the configuration of a pre-built Digital Ocean Wiki.js Docker image?

**Comment by aalbng** [comment]
@NGPixel 
it would be nice if you could add an environment variable for the docker installation.

At the moment i use a workaround to mount my custom "config.yml" into the container with docker-compose.

**_My docker compose section if anybody needs also the workaround_**
```
networks:
  wikijs-net:

services:
  wikijs-web:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs-web
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-postgres-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: xxx
      DB_NAME: wikijs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - wikijs-net
    volumes:
      - ./config.fix.yml:/wiki/config.yml
```

Rename config.fix.yml.txt to config.fix.yml
[config.fix.yml.txt](https://github.com/requarks/wiki/files/12093611/config.fix.yml.txt)
