### DISCUSSION TITLE
Set log level for Kubernetes deployment

### DISCUSSION THREAD

**Discussion by skyreacher** [requarks/wiki#6085] [Help / Questions] [answered]
Hello,

I wanted to further investigate problems with a Wiki.js instance (I've written about the problems in #6064 ), and so I thought it might be a good idea to increase the log level.

The instance has been deployed with Helm into Kubernetes. In the chart's values I didn't find an option to define the log level. I've logged into the pod and inspected the `config.yml` file, it contains this line:

```
logLevel: $(LOG_LEVEL:info)
```

I tried to upgrade the Helm deployment and added `--set LOG_LEVEL=debug` to the `helm upgrade` command, because I thought I could set an environment variable this way. However, it looks like it didn't work - don't know if that's the wrong way or if I did something wrong?

And another question: what does the `:info` part mean?
Is this like: "use the `LOG_LEVEL` environment variable and in case it isn't there, use `info` as default value"?

I also tried to edit `config.yml` directly inside the running pod, but didn't find out how I can restart the Wiki.js service inside the pod, without recreating the pod. When I downscale the deployment to 0 and scale it up again, modifications inside the container are obviously lost and `config.yml` reverts to its default values.

Is there a way to adjust the log level of Wiki.js in Kubernetes deployments?

**Comment by fnafox** [comment, marked as answer]
I suggest creating a configmap from your desired config.yml, e.g.:
`kubectl create configmap wiki-conf --from-file config.yml`

Then edit your helm chart to mount the config:
```yaml
volumeMounts:
     - name: wiki-conf
       mountPath: /wiki/config.yml
       subPath: config.yml

volumes:
   - name: wiki-conf
     configMap:
        name: wiki-conf
        items:
          - key: config.yml
            path: config.yml
```

That way you can adjust your configmap as needed by editing the configmap and restarting the deployment.
`kubectl edit configmap wiki-conf`
`kubectl rollout restart deployment wiki`
