### DISCUSSION TITLE
Media query per page handling

### DISCUSSION THREAD

**Discussion by ayoahha** [requarks/wiki#6099] [Help / Questions] [answered]
Hi the team,
i have searched on many discussions, but not found any answer to my concerns.
I am facing a problem with iframes, and have several questions...

Version : 2.5.295.
Docker(Linux)

1. Why you do "not recommend" activating this feature exactly (in HMTL rendering, security part) ? 
**is this due to security issue ?**
**Which security issue exactly ?**

2. I am currently trying to handle iframes for _peertube_ videos (not youtube, vimeo etc.), with a **responsive** feature... 
I tried this code within "style" part of the page parameters, with a class in the iframe tag `class="frame-style"` :
```css
.frame-style {
	@media (min-width: 1000px) {
	  width: 560px;
	  height: 315px;
	}
}
```
The result is a CSS modified (??) as is :
```css
.frame-style {
    height: 315px;
}
```
**Is this possible to handle media queries in wikijs ?**
And how can i handle this with iframes on peertube videos ?

Many many thanks for your help :+1:
