### DISCUSSION TITLE
Inserted pictures start returning a 500 after a while

### DISCUSSION THREAD

**Discussion by AuspeXeu** [requarks/wiki#6157] [Error / Bug Report] [answered]
I have yet to find a way to reproduce this, but we had this now during multiple occasions, that images would disappear and we would have to re-upload them. From the flog I can only find this:

```
2023-02-13T13:38:53.197Z [MASTER] info: Purging orphaned upload files...
2023-02-13T13:38:53.201Z [MASTER] info: Purging orphaned upload files: [ COMPLETED ]
2023-02-13T13:45:06.408Z [MASTER] error: path must be absolute or specify root to res.sendFile
2023-02-13T13:45:06.767Z [MASTER] error: path must be absolute or specify root to res.sendFile
2023-02-13T13:45:34.242Z [MASTER] error: path must be absolute or specify root to res.sendFile
2023-02-13T13:45:35.973Z [MASTER] error: path must be absolute or specify root to res.sendFile
2023-02-13T13:45:36.791Z [MASTER] error: path must be absolute or specify root to res.sendFile
2023-02-13T13:45:42.342Z [MASTER] error: path must be absolute or specify root to res.sendFile
```

![image](https://user-images.githubusercontent.com/2115696/218475222-3ac021e1-aae5-473d-a59d-e40b2eaa262d.png)

**Comment by jhgarrison** [comment]
I'm also seeing this.  Almost all of my images links are broken and will work after I re-upload them.  The images are physically present in `/var/wiki`.

I tried turning up logLevel to "debug" and then to "silly" but it produced no additional information other than 

    2023-03-21T21:45:30.625Z [MASTER] error: path must be absolute or specify root to res.sendFile

for every image request.

In my case I'm running wiki.js behind an nginx reverse proxy, but since the images DO work for a time I'm guessing that's not part of the problem.  The corresponding log entry in nginx for these requests looks like this:

    24.21.xxx.xxx- - [21/Mar/2023:14:45:30 -0700] "GET /form011.png HTTP/1.1" 500 21 "https://[redacted]" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0" "-"

I really need suggestions on how to debug/fix this.  I can't re-upload dozens of images every few days.

Additional Info:

- I've tried restarting wiki.js and nginx, with no improvement
- If I re-insert an image into a page, both the old and new insertions now display the image.
- Looking at the "assets" table in psql I don't see any difference between images that are working and ones that are not working.  In the output below, `form002.png` was just re-uploaded, and is currently working; `form004.png` is not working.

```
 id |  filename   |                   hash                   | ext  | kind  |   mime    | fileSize | metadata |        createdAt         |        updatedAt         | folderId | authorId
----+-------------+------------------------------------------+------+-------+-----------+----------+----------+--------------------------+--------------------------+----------+----------
 29 | form004.png | d1709e81d31160a4a148b87757956d580ee3e1ac | .png | image | image/png |    16802 |          | 2023-02-28T23:32:50.261Z | 2023-03-10T19:13:07.659Z |          |        1
 27 | form002.png | 3c758355ab0faf4102bc9ea45b7d1b9c80c590fc | .png | image | image/png |    75167 |          | 2023-02-28T23:32:47.716Z | 2023-03-21T22:14:46.485Z |          |        1
```

**Comment by rvk7895** [comment]
Has there been any progress towards a solution for this problem?

**Comment by AuspeXeu** [comment]
Keeps happening, makes the wiki unusable, really!

![image](https://github.com/requarks/wiki/assets/2115696/3b613f31-03d3-4f38-ad2a-78fb16a9be50)

**Comment by NGPixel** [comment, marked as answer]
Use a valid path in for the `dataPath` property in your config.yml file. Use an absolute path if your setup is non-standard.

A combination of that value with the current process working folder produces an invalid path, which results in this error.

**Reply by AuspeXeu** [reply]
What do you mean by non standard setup? I am using the official docker image.

I am logging L203 in assets.js and get the following:

![image](https://github.com/requarks/wiki/assets/2115696/7f30fe49-bb21-494a-b85a-ec5bb74d9371)

**Reply by NGPixel** [reply]
Are you mounting your own config.yml? That path is definitely not the default docker image value.

**Reply by AuspeXeu** [reply]
```
  wiki:
    image: requarks/wiki:2.5.299
    container_name: wiki
    environment:
      DB_TYPE: postgres
      DB_HOST: wikiDB
      DB_PORT: 5432
      DB_USER: XXXXX
      DB_PASS: YYYYY
      DB_NAME: wiki
    depends_on:
      - wikiDB
    networks:
      - wiki-tier
    restart: "unless-stopped"
```

**Reply by AuspeXeu** [reply]
form inside the container after docker exec -it wiki bash
```
4eb0dad7ab70:/wiki$ cat config.yml
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: letsencrypt
  domain: $(LETSENCRYPT_DOMAIN)
  subscriberEmail: $(LETSENCRYPT_EMAIL)
logLevel: $(LOG_LEVEL:info)
logFormat: $(LOG_FORMAT:default)
ha: $(HA_ACTIVE)
4eb0dad7ab70:/wiki$
```
