### DISCUSSION TITLE
While installing wiki, setup is stuckked at - Purging orphaned upload files..

### DISCUSSION THREAD

**Discussion by Utsaww** [requarks/wiki#6209] [Help / Questions]
I am trying to install a wiki on the server which is Rocky-Linux-9 (rhel centos fedora), every time I am trying to start setup it will looping around `Purging orphaned upload files. `  even I have waited for 12 hours but that process going on and on.. what should I do?

I am using Nodejs 16.18.1 and the rest system info is below.

![image](https://user-images.githubusercontent.com/81962784/221357877-2b87edbe-b631-4a55-8828-8620fb54208e.png)

**Comment by NGPixel** [comment]
Please post the logs.

**Reply by Utsaww** [reply]
Logs for the server - 

![image](https://user-images.githubusercontent.com/81962784/221406348-9aef4fd5-6c42-4676-8dfa-831168e267c2.png)


and logs which s showing on the screen while installing the system it stuck at this point and repeats  this line `Purging orphaned files..`-

![image](https://user-images.githubusercontent.com/81962784/221406411-4977a7c1-f7e2-4876-941a-d8a5f78daa68.png)

**Reply by NGPixel** [reply]
There's nothing wrong in the logs you posted...?

Purging orphaned files is a regular scheduled task.

Not sure what you're referring to when saying "installing". The logs show it's already installed and running normally...

**Reply by Utsaww** [reply]
I really don't know why but - **what I did is I added MySQL connection in `config.yml` and run the command `node server`** and this happened I literally waited 12 hours and today 6 hours and after every 15-20  minutes it shows `Purging orphaned files`, is there a way to uninstall it totally and reinstall it, in a manner that there are no files left in a root or any directory so that I can start a fresh installation?

**Reply by NGPixel** [reply]
This is a server process, it's supposed to run indefinitely... It won't end until you manually kill the process.

Have you tried loading the website? (localhost:3333 according to your logs)

Everything you posted so far is working as expected. I think you just misunderstand how server processes work.

**Reply by Utsaww** [reply]
Not working, I have tried localhost:3333 but no response, I have pasted my config file too, it has MySQL database config which is hosted on a different network and I can see clearly connection is successful in the log with MySQL database.
 Also, I have not seen this - `Wait until you are invited to open the setup page in your browser.` as stated in the [documentation](https://docs.requarks.io/install/linux) - 
and also did not Complete the setup wizard to finish the installation.
 

```
port: 3333

db:
  type: mysql

  host: w988.kasserver.com
  port: 3306
  user: user
  pass: password
  db: d03b5ca2
  ssl: false

 
  sslOptions:
    auto: true
 
 
  schema: public

  storage: path/to/database.sqlite
 

ssl:
  enabled: false
  port: 3443

 
  provider: custom
 
  format: pem
 
  key: path/to/key.pem
  cert: path/to/cert.pem
 
  pfx: path/to/cert.pfx
 
  passphrase: null
 
  dhparam: null
 
 
pool:
 
bindIP: 0.0.0.0

logLevel: info

logFormat: default

offline: false

ha: false

dataPath: ./data
bodyParserLimit: 5mb
```
