### DISCUSSION TITLE
SSL stopped working

### DISCUSSION THREAD

**Discussion by federico-razzoli** [requarks/wiki#6290] [Help / Questions]
I configured WikiJS to use SSL with a Let's Encrypt certificate. Everything worked perfectly, until some days ago. But then, it stopped working. Now Chrome reports that the connection is not secure.

I checked Administration -> SSL and everything seems OK. "Certificate Status" reports OK, and actually I know that the certificate didn't expire. I tried to renew it anyway, but nothing changed.

What can I do?

**Comment by federico-razzoli** [comment]
Let me add a screenshot of the SSL configuration page.
<img width="1422" alt="Screenshot 2023-03-23 at 18 01 07" src="https://user-images.githubusercontent.com/497022/227303371-4d8cf8a6-78f4-45ac-9e11-80d4282902c0.png">

**Comment by federico-razzoli** [comment]
And in the configuration file I have these lines:

```
ssl:
  enabled: true
  port: 443

  # Provider to use, possible values: custom, letsencrypt
  provider: letsencrypt
  domain: REDACTED
  subscriberEmail: REDACTED
```
