### DISCUSSION TITLE
Instana Integration

### DISCUSSION THREAD

**Discussion by YunusEmreAlps** [requarks/wiki#6336] [Help / Questions]
Hello,

I hope you're well and everything is good with you.

I want to add Instana monitoring like analytics. Right now I added but I can't test this tool.

**code.yml**
```
head: |
  <script type="text/javascript">
    var sdkInstance="appInsightsSDK";
    window[sdkInstance]="appInsights";
    var aiName=window[sdkInstance],aisdk=window[aiName]||function(e){
      instana({
        agentHost: "{{agentHost}}",
        agentPort: "{{agentPort}}",
        serviceName: "{{serviceName}}"
      });
    };
  </script>
```

**definition.yml**
```
key: instana
title: Instana
description: Instana is a performance monitoring and observability platform for applications and infrastructure.
author: TT
logo: https://avatars.githubusercontent.com/u/5128994?s=200&v=4
website: https://www.instana.com/
isAvailable: true
props:
  agentHost:
    type: String
    title: Agent Host
    hint: The hostname or IP address of the Instana agent
    order: 1
  agentPort:
    type: Number
    title: Agent Port
    hint: The port number on which the Instana agent is listening
    order: 2
  serviceName:
    type: String
    title: Service Name
    hint: The name of the service or application being monitored
    order: 3
```
![Adsız](https://user-images.githubusercontent.com/44679555/230905699-2b054854-d2f1-4f16-8a60-fe47d02d758e.png)

I added but I can't get data. How can I test this? Can anybody guide me?

Thank you very much.
Best regards,
