### DISCUSSION TITLE
Config file problem when creating a docker instance with docker compose

### DISCUSSION THREAD

**Discussion by EHRETic** [requarks/wiki#6401] [Help / Questions] [answered]
Hi there,

In order to migrate my "fat" Wiki JS installation to a dockerized one, I'm doing some tests but I can't get my docker compose file to get the config.yml I put on the container's volume

```
version: "3.9"

services:
  wiki:
    image: requarks/wiki:2
    container_name: wikijs-test

    restart: unless-stopped

    environment:
        CONFIG_FILE: /wiki/config.yml

    volumes:
        - data:/wiki/data/content:/content
        - data:/config/config.yml:/wiki/config.yml

networks:
    default:
        external: true
        name: mymacvlannet

volumes:
    data:
```

I get the following logs (meaning in my opinion it's not finding the file at all...):

```
Loading configuration from /wiki/config.yml... OK
2023-05-03T17:30:41.047Z [MASTER] info: =======================================
2023-05-03T17:30:41.053Z [MASTER] info: = Wiki.js 2.5.298 =====================
2023-05-03T17:30:41.054Z [MASTER] info: =======================================
2023-05-03T17:30:41.054Z [MASTER] info: Initializing...
2023-05-03T17:30:41.811Z [MASTER] error: Invalid DB Type
Loading configuration from /wiki/config.yml... OK
2023-05-03T17:30:43.571Z [MASTER] info: =======================================
2023-05-03T17:30:43.576Z [MASTER] info: = Wiki.js 2.5.298 =====================
2023-05-03T17:30:43.577Z [MASTER] info: =======================================
2023-05-03T17:30:43.577Z [MASTER] info: Initializing...
2023-05-03T17:30:44.395Z [MASTER] error: Invalid DB Type

and it restarting all over again...
```

The following configuration works (I can get my initial login), but I want to use a config file for several reasons (including custom SSL certs)

```
version: "3.9"
services:
  wiki:
    image: requarks/wiki:2
    container_name: wikijs-test

    environment:
        DB_TYPE: postgres
        DB_HOST: postgresserverip
        DB_PORT: 5432
        DB_USER: wikijs-test
        DB_PASS: wikijsrocks
        DB_NAME: wikijs-test
        SSL_ACTIVE: true
    restart: unless-stopped
    ports:
      - "80:3000"

networks:
    default:
        external: true
        name: mymacvlannet

volumes:
    data:
```

Any clue where I did a mistake?

The path of config file is /config/config.yml in the container volume.
I'm using Portainer to deploy the stack/docker compose file.

PS: I'm new to docker so it can be a simple mistake... I'm still learning 😉

**Comment by iazz-code** [comment]
Hi,

i would assume that there is a wrong entry in your config.yml-File regarding the DB_Type.

It must match with the installed type, presumably "postgres"

Can you post your config.yml-file?

**Comment by EHRETic** [comment]
Hi,

Yes sure, here it is:
```

#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full documentation + examples:
# https://docs.requarks.io/install

# ---------------------------------------------------------------------
# Port the server should listen to
# ---------------------------------------------------------------------

port: 80

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Supported Database Engines:
# - postgres = PostgreSQL 9.5 or later
# - mysql = MySQL 8.0 or later (5.7.8 partially supported, refer to docs)
# - mariadb = MariaDB 10.2.7 or later
# - mssql = MS SQL Server 2012 or later
# - sqlite = SQLite 3.9 or later

db:
  type: postgres

  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: postgresserverip
  port: 5432
  user: wikijs-test
  pass: wikijsrocks
  db: wikijs-test
  ssl: false

  # Optional - PostgreSQL / MySQL / MariaDB only:
  # -> Uncomment lines you need below and set `auto` to false
  # -> Full list of accepted options: https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options
  sslOptions:
    auto: true
    # rejectUnauthorized: false
    # ca: path/to/ca.crt
    # cert: path/to/cert.crt
    # key: path/to/key.pem
    # pfx: path/to/cert.pfx
    # passphrase: xyz123

  # SQLite only:
  storage: path/to/database.sqlite

#######################################################################
# ADVANCED OPTIONS                                                    #
#######################################################################
# Do not change unless you know what you are doing!

# ---------------------------------------------------------------------
# SSL/TLS Settings
# ---------------------------------------------------------------------
# Consider using a reverse proxy (e.g. nginx) if you require more
# advanced options than those provided below.

ssl:
  enabled: false
  port: 443

  # Provider to use, possible values: custom, letsencrypt
  provider: custom

  # ++++++ For custom only ++++++
  # Certificate format, either 'pem' or 'pfx':
  format: pem
  # Using PEM format:
  key: path/to/key.pem
  cert: path/to/cert.pem
  # Using PFX format:
  pfx: path/to/cert.pfx
  # Passphrase when using encrypted PEM / PFX keys (default: null):
  passphrase: null
  # Diffie Hellman parameters, with key length being greater or equal
  # to 1024 bits (default: null):
  dhparam: null

  # ++++++ For letsencrypt only ++++++
  domain: wiki.yourdomain.com
  subscriberEmail: admin@example.com

# ---------------------------------------------------------------------
# Database Pool Options
# ---------------------------------------------------------------------
# Refer to https://github.com/vincit/tarn.js for all possible options

pool:
  # min: 2
  # max: 10

# ---------------------------------------------------------------------
# IP address the server should listen to
# ---------------------------------------------------------------------
# Leave 0.0.0.0 for all interfaces

bindIP: 0.0.0.0

# ---------------------------------------------------------------------
# Log Level
# ---------------------------------------------------------------------
# Possible values: error, warn, info (default), verbose, debug, silly

logLevel: verbose

# ---------------------------------------------------------------------
# Offline Mode
# ---------------------------------------------------------------------
# If your server cannot access the internet. Set to true and manually
# download the offline files for sideloading.

offline: false

# ---------------------------------------------------------------------
# High-Availability
# ---------------------------------------------------------------------
# Set to true if you have multiple concurrent instances running off the
# same DB (e.g. Kubernetes pods / load balanced instances). Leave false
# otherwise. You MUST be using PostgreSQL to use this feature.

ha: false

# ---------------------------------------------------------------------
# Data Path
# ---------------------------------------------------------------------
# Writeable data path used for cache and temporary user uploads.
dataPath: ./data

```

But moving/renaming the file didn't change the output of wrong database type. If I put the following, the container starts anyway and gives the same DB type error message (and I know this path is completely wrong 😁) :
```
...
    volumes:
        - data:/wiki/data/content:/content
        - data:/config123456/config.yml:/wiki123456/config.yml
...
```

Any clue? (that is why I know it can't find my file in the first place)

**Comment by iazz-code** [comment]
I would try
...
    volumes:
      - /wiki/data/content:/content
      - /config123456/config.yml:/wiki123456/config_TEST.yml

volumes:
  wiki:
... 

After that i would look up for the container ID (docker ps) and log into the container to check if or where the config-test-file is stored (docker exec -it <CONTAINER_ID> /bin/bash)

Hope that helps a bit.

**Reply by EHRETic** [reply]
> After that i would look up for the container ID (docker ps) and log into the container to check if or where the config-test-file is stored (docker exec -it <CONTAINER_ID> /bin/bash)

The problem is that the container keeps restarting, making the login impossible. 😑

**Comment by EHRETic** [comment, marked as answer]
Hi,

I could get it to work (after a lot of combinations/tries and some tutorials about docker volumes.
So it seems that I can't map a subfolder of a named volume (maybe it is possible but I didn't find the syntax)

Also : within the wikiJS container, the default config file is in the folder **/wiki/config.yml** (the one with environnement variables)
This surely made the troubleshooting harder as this one was the "fallback" file with all variables to NULL, making the logs with the wrong DB type.

My working YAML file will setup 2 different volumes (one for the content, otherwise it maps a temporary volume, which I don't like) and one for the config file + later the certificates/key files.

I choose to map the config volume WITHIN the docker wiki folder, so everything is there if I connect in the container.

```
version: "3.9"

services:
  wiki:
    image: requarks/wiki:2
    container_name: wikijs-test

    restart: unless-stopped
    
    volumes:
        - data:/wiki/data/content
        - config:/wiki/config

    networks:
        default:
            ipv4_address: containerip

    environment:
        CONFIG_FILE: /wiki/config/config.yml

networks:
    default:
        external: true
        name: mymacvlannet

volumes:
    data:
    config:
```

Learning docker is one thing but I need to learn how all the containers I want tu run behave too, quite a tricky thing! 😊
So if anybody can give me the solution to map subfolders within a single volume, I'll love it!
