### DISCUSSION TITLE
Wiki.js shows blank setup page

### DISCUSSION THREAD

**Discussion by Skyslycer** [requarks/wiki#6470] [Help / Questions]
I just set up a Wiki.js instance using docker-compose and NGINX as a reverse proxy. When going to the site `https://wiki.mysite.com`, the title and favicon get loaded, but the page just stays blank. It seems like the JS isn't replacing the setup component, and I have tried it on multiple browsers on multiple devices and it doesn't work. Couldn't find anything sadly. (The js files get supplied)

EDIT: It doesn't work on Firefox or Chrome on Windows 11, but it works on Android 13 in Firefox.

Here are my configurations, thanks in advance!

Errors in console.
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("default-src").
```

Currently running:
```
Ubuntu 22.04.2 LTS
Docker 24.0.2
Docker Compose 2.18.1
NGINX 1.18.0
```

My docker-compose.yml:
```
version: "3"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "127.0.0.1:14080:3000"

volumes:
  db-data:
```

nginx configuration:
```
server {
  server_name wiki.mysite.com;

  listen [::]:443 ssl; # managed by Certbot
  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/wiki.mysite.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/wiki.mysite.com/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_connect_timeout                 90;
    proxy_send_timeout                    90;
    proxy_read_timeout                    90;
    proxy_buffering off;
    proxy_cache_valid 200 30m;
    proxy_cache_valid 404 1m;
    
    client_max_body_size                  10m;
    client_body_buffer_size               128k;

    proxy_pass http://127.0.0.1:14080;
  }

  include nginxconfig.io/security.conf;
}
server {
  if ($host = wiki.mysite.com) {
      return 301 https://$host$request_uri;
  } # managed by Certbot

  listen 80;
  listen [::]:80;
  server_name wiki.mysite.com;
  return 301 https://$host$request_uri;
}
```
