### DISCUSSION TITLE
Spinning circle for the guest user

### DISCUSSION THREAD

**Discussion by Arian-D** [requarks/wiki#6538] [Error / Bug Report]
I have an ec2 instance hosting wikijs using docker compose with the following definition
```yml
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: *****************
      DB_NAME: wiki
    restart: unless-stopped
    expose:
      - 3000

  caddy:
    image: caddy
    depends_on:
      - wiki
    restart: unless-stopped
    command: caddy reverse-proxy --from https://${public_url}:443 --to http://wiki:3000
    ports:
      - "80:80"
      - "443:443"


volumes:
  db-data:
```
Everything seems fine. Logged in users are able to see public and private pages fine, but for public-facing pages that are read by the guest user, there's a spinning circle next to the login button at the top right
![image](https://github.com/requarks/wiki/assets/40076285/d1b803c0-7ad7-4853-a90b-ac0318de5cea)
I can provide any more information/context if needed.
