### DISCUSSION TITLE
The same login/password works in Firefox, but doesn't work in Chrome

### DISCUSSION THREAD

**Discussion by malordin** [requarks/wiki#6619] [Error / Bug Report] [answered]
Hi all, the essence of the problem from the thread title, I noticed a strange feature that my account only works in firefox browser. 

There can't be an error because I copy the login and password and paste them into the login forms. I have even tried changing my account password but the problem persists, I can log in with the new password in firefox but still can't log in with it in google chrome. 

I would think that the problem is somewhere with my browser in google chrome or with cookies, but I created another account with admin permissions and it suddenly works in google chrome! 

I tried to find logs where the login error would be written, but didn't figure out how to do that. I have the installation via docker, here is my docker-compose file:

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "2500:3000"

volumes:
  db-data:
```

Everything is completely standard. I'd be happy to provide more information if you can tell me how to provide it to debug the problem. Thanks, I'll look forward to hearing back from you.
