### DISCUSSION TITLE
Can't sync with Github as a storage

### DISCUSSION THREAD

**Discussion by Artyshot** [requarks/wiki#6655] [Help / Questions] [answered]
Hi there !

First time I call for help on Github but I'm really stuck.

I try in vain to synchronize wikijs with a private github repo without success.

Here's my configuration:

OS: Docker (Portainer on OpenMediaVault Proxmox hypervisor)
Wiki.js version: 2.5.300
Wiki.js behind nginx Proxy Manager (lxc)

And my docker compose in Portainer:

```yaml
version: '3'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: <DBname>
      POSTGRES_PASSWORD: <Password>
      POSTGRES_USER: <InTrouble>
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /shared/path/wikijs/data:/var/lib/postgresql/data
      
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: <InTrouble>
      DB_PASS: <Password>
      DB_NAME: <DBname>
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: "node"
    volumes:
      - /shared/path/wikijs/data/wikijs/secure/:/wiki/data/secure/

volumes:
  db-data:
```

## The problem

![Git_prob_1](https://github.com/requarks/wiki/assets/120382168/62e2b7d4-8125-4e0d-96ef-fddface405c9)

The admin page for setting up the storage

![Git_prob_2](https://github.com/requarks/wiki/assets/120382168/309c3ca1-47fb-4cab-a2e8-1240190c1edb)

So what I did so far, everything ikwtif did in that thread : https://github.com/requarks/wiki/discussions/3231

I tried to 

- Change to "Absolute Path" setting
- Recreate the repo and generate a new key (puttygen) + rename it in .pub
- Kill the Docker container and recreate it (without delete postgres) 
- Check if the owner of the secure/ folder is "node"

![Git_prob_3](https://github.com/requarks/wiki/assets/120382168/88f15dbe-bef7-470b-b8f1-e97593224d0b)

I also looked at the configuration files for the wiki container's ssh service, but not knowing enough about it, I didn't take the risk to edit something.

And finally, I created a key file git-ssh.pem with the root user of the container in an another folder (/wiki) and tried that

```bash
# Inside the Wiki.js container
cd /path/in/container/to/ssh/key
echo "-----BEGIN RSA PRIVATE KEY-----
<private key content>
-----END RSA PRIVATE KEY-----" > git-ssh.pem

chmod 600 git-ssh.pem

ssh -i git-ssh.pem git@github.com
```

Last thing I did was to make a 'git init' directly in /data/repo but all I had was a "Permission Denied"

And that's it, now I'm stuck and don't know what to do next. Just for information, I tried WikiJs 3 months ago just for fun and the GitHub storage worked. And I didn't change the server since this try.

Thank you in advance for your answers.

Regards.
