### DISCUSSION TITLE
Session Issue - Users finding themselves logged on as other users occaisionally

### DISCUSSION THREAD

**Discussion by jaypoc** [requarks/wiki#6822] [Help / Questions] [answered]
I have been experiencing a strange issue related to the active sessions in Wiki.js. Sometimes the Wiki.js site will log me in as another user without notice.

I use the company's LDAP server to authenticate and this works well. I can use Wiki.js as myself for a while without issue. At some point (the actual timing or cause is currently unknown), wiki.js winds up being logged in as another user. I typically catch this when I post or  update a page and see that the post was Last Modified by someone else. Then I click the account icon at the top right and see that I'm logged in as that person. 

My team does not share PCs, so I know they never logged in to my system. The rest of my team has mentioned that they experienced this as well occasionally.

Any thoughts why this could be happening, or what I should look for?

Running Wiki.js 2.5.300
Windows 2019 / IIS 10 (Reverse Proxying to local port)
Running Wiki.js via nssm-2-24
Running Node v18.18.0

**Comment by FirefoxNL** [comment]
I am having the same issue, but we are using local database authentication.
First I thought it was an issue with one user so I recreated that user but now even guests (customers) are finding themselves logged in all of a sudden, being able to edit pages, see internal documentation and even edit user profile settings.

Like you said, everyone has their own laptop and people do not log in on other people's computers.
Also that it's now happening with customers who don't have any login credentials is quite worrisome.

My configuration:
- Wiki.Js version 2.5.299
- Running in docker compose, managed with portainer
- Hosted on an Ubuntu 22.04.2 LTS VM with 3 CPU, 4 GB RAM
- Reverse Proxied through IIS 10 on a Windows Server 2019 VM
- Node version 16.20.0
- Postgres 15

Docker compose file:
```
version: "3"
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: xxx
      POSTGRES_PASSWORD: xxx
      POSTGRES_USER: xxx
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: xxx
      DB_PASS: xxx
      DB_NAME: xxx
    restart: unless-stopped
    volumes:
      - /WIKI/assets/favicon.ico:/wiki/assets/favicon.ico
      - /WIKI/assets/favicons:/wiki/assets/favicons

    ports:
      - "3000:3000"

volumes:
  db-data:
```

Reverse Proxy settings:
![image](https://github.com/requarks/wiki/assets/74513001/c7fd4ecb-be82-4da3-96bb-da1df88b56f7)

If more info is needed, let me know.
