### DISCUSSION TITLE
Wiki.js 3 (alpha) with Docker and SSL/HTTPS

### DISCUSSION THREAD

**Discussion by justinmassiot** [requarks/wiki#6916] [Help / Questions]
Hello,

As I know Wiki.js 3.x is an Alpha version, I don't particularly expect support.
So I just have one question: **is what I encounter a known behavior?**
Details follow.

-----

I'm currently installing the Alpha build (latest from 2024-01-02, not sure where I can catch the build number) of Wiki.js 3.x branch while waiting for the future stable release.
The server runs Ubuntu 22.04.

I first installed Docker, then the following guides were my source of inspiration:

- https://docs.requarks.io/install/ubuntu
- https://docs.requarks.io/install/docker
- https://next.js.wiki/docs/install/platform/docker

I have the latest stable release of PostgreSQL: 16.1
I can now access my wiki from a web browser and everything is apparently working!

-----

Then I wanted to enable HTTPS with Let's Encrypt just [like the guide describes](https://docs.requarks.io/install/ubuntu#automatic-https-with-lets-encrypt-optional), but this doesn't seem that simple...

Here is what I set **specifically for HTTPS** in my docker-compose file:
```yaml
  wiki:
    environment:
      HTTPS_ENABLE: true
      HTTPS_PORT: 3443
      HTTPS_PROVIDER: letsencrypt
      HTTPS_LE_DOMAIN: <my.hostname.tld>
      HTTPS_LE_EMAIL: <me>@<my.hostname.tld>
    ports:
      - "443:3443"
```

Trying to connect to the HTTPS website gives a `PR_END_OF_FILE_ERROR`.
Now accessing Wiki.js in HTTP, I can't find an "SSL" section in the Administration section. Don't know if this is expected.

Here is the wiki's `config.yml` obtained with `sudo docker compose exec wiki cat /wiki/config.yml`:
```yaml
port: 3000
bindIP: 0.0.0.0
db:
  host: '$(DB_HOST)'
  port: $(DB_PORT:5432)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: letsencrypt
  domain: $(LETSENCRYPT_DOMAIN)
  subscriberEmail: $(LETSENCRYPT_EMAIL)
logLevel: $(LOG_LEVEL:info)
logFormat: $(LOG_FORMAT:default)
```

I see that it expects a `$SSL_ACTIVE` variable that I haven't set!
Confirmed with `sudo docker compose exec wiki /usr/bin/env`:
```sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=5f2b8a13fa3f
TERM=xterm
ADMIN_EMAIL=<me>@<my.hostname.tld>
DB_USER=wikijs
HTTPS_LE_EMAIL=<me>@<my.hostname.tld>
DB_PASS=<db_pass>
DB_NAME=wiki
HTTPS_ENABLE=true
ADMIN_PASS=<password>
HTTPS_LE_DOMAIN=<my.hostname.tld>
HTTPS_PORT=3443
DB_HOST=db
HTTPS_PROVIDER=letsencrypt
NODE_VERSION=20.9.0
YARN_VERSION=1.22.19
NODE_ENV=production
HOME=/home/node
```

So... I have set one in my docker-compose file!
But now my service doesn't start at all 😞.
```
docker-wikijs-wiki-1  | 2024-01-02T20:03:05.896Z [06580834b3] error: ReferenceError: require is not defined
docker-wikijs-wiki-1  |     at Object.initHTTPS (file:///wiki/server/core/servers.mjs:67:7)
docker-wikijs-wiki-1  |     at Module.init (file:///wiki/server/web.mjs:45:24)
docker-wikijs-wiki-1  |     at async Object.bootWeb (file:///wiki/server/core/kernel.mjs:63:7)
```

Is this expected?
