### DISCUSSION TITLE
/merged/wiki/config.yml was removed automatically after container restart

### DISCUSSION THREAD

**Discussion by botapony** [requarks/wiki#6922] [Help / Questions]
Hi, guys! I have installed wikijs using https://docs.requarks.io/install/ubuntu guide, and on ubuntu server changed /var/lib/docker/overlay2/d88a0f5a3c9028a5516f809662705ba43e6798e265f45923b2148ba0811e3b20/merged/wiki/config.yml to this:

```
port: 80
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: true
  port: *443*
  provider: custom

  format: pem
  key: path/to/key.pem #wrote my path to key 
  cert: path/to/cert.pem #and cert also
  passphrase: null
  dhparam: null
```

using this documentation https://docs.requarks.io/install/config HTTPS custom certificate. Then i restarted each container with these commands: 
```
docker start db
docker start wiki
docker start wiki-update-companion
```

unfortunately, my web interface is down after restart and this file /var/lib/docker/overlay2/d88a0f5a3c9028a5516f809662705ba43e6798e265f45923b2148ba0811e3b20/merged/wiki/config.yml was removed suddenly and cannot find and locate it. All my configurations with ssl are saved within this file. how to enable web interface of Wiki js again?
