### DISCUSSION TITLE
tls with private certificates not working

### DISCUSSION THREAD

**Discussion by Torkolis** [requarks/wiki#6933] [Help / Questions]
Hi, I am not able to configure tls (https) currently, it just does not work!

here is my config.yml:

```
port: 3000

db:
  type: mariadb
  host: host.home.net
  port: 3306
  user: ####
  pass: ####
  db: ####
  ssl: true
  sslOptions:
    auto: false
    ca: /wiki/certificates/ca.cer

ssl:
  enabled: true
  port: 3443
  provider: custom
  format: pem
  key: /wiki/certificates/server-key.pem
  cert: /wiki/certificates/server-cert.pem
  passphrase: null
  dhparam: null

```

connection to database works, but there is just no hint on why the wiki won't use tls, here is the logs:

```
docker compose logs -f
wiki-wikijs-1  | Loading configuration from /wiki/config.yml... OK
wiki-wikijs-1  | 2024-01-12T12:32:28.913Z [MASTER] info: =======================================
wiki-wikijs-1  | 2024-01-12T12:32:28.915Z [MASTER] info: = Wiki.js 2.5.300 =====================
wiki-wikijs-1  | 2024-01-12T12:32:28.915Z [MASTER] info: =======================================
wiki-wikijs-1  | 2024-01-12T12:32:28.915Z [MASTER] info: Initializing...
wiki-wikijs-1  | 2024-01-12T12:32:29.369Z [MASTER] info: Using database driver mysql2 for mariadb [ OK ]
wiki-wikijs-1  | 2024-01-12T12:32:29.376Z [MASTER] info: Connecting to database...
wiki-wikijs-1  | 2024-01-12T12:32:29.448Z [MASTER] info: Database Connection Successful [ OK ]
wiki-wikijs-1  | 2024-01-12T12:32:29.487Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
wiki-wikijs-1  | 2024-01-12T12:32:29.487Z [MASTER] info: Starting setup wizard...
wiki-wikijs-1  | 2024-01-12T12:32:29.621Z [MASTER] info: Starting HTTP server on port 3000...
wiki-wikijs-1  | 2024-01-12T12:32:29.622Z [MASTER] info: HTTP Server on port: [ 3000 ]
wiki-wikijs-1  | 2024-01-12T12:32:29.625Z [MASTER] info: HTTP Server: [ RUNNING ]
wiki-wikijs-1  | 2024-01-12T12:32:29.625Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
wiki-wikijs-1  | 2024-01-12T12:32:29.625Z [MASTER] info:
wiki-wikijs-1  | 2024-01-12T12:32:29.625Z [MASTER] info: Browse to http://YOUR-SERVER-IP:3000/ to complete setup!
wiki-wikijs-1  | 2024-01-12T12:32:29.625Z [MASTER] info:
wiki-wikijs-1  | 2024-01-12T12:32:29.626Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
```

inspecting the ports in the container shows that only Port 3000 is active:

``` 
netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:33419        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      1/node
udp        0      0 127.0.0.11:58574        0.0.0.0:*                           -
```

Here is the docker-compose.yml file:

```
services:
  wikijs:
    image: ghcr.io/requarks/wiki:2
    restart: always
    ports:
      - 443:3443
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
      - type: bind
        source: ./conf/config.yml
        target: /wiki/config.yml
      - type: bind
        source: /opt/wiki/certificates
        target: /wiki/certificates

volumes:
  data:
```
please help
