### DISCUSSION TITLE
Install WikiJS with Helm and enable SSL for PostgreSQL

### DISCUSSION THREAD

**Discussion by P2W2** [requarks/wiki#6947] [Help / Questions]
Hello,I am a little confused how to enable ssl with the Helm chart.

Steps I used to create the ca file:

```
openssl req -new -x509 -sha256 -days 365 -key ca.key -out ca.crt
cat ca.key > server.pem
cat ca.crt >> server.pem
kctl apply -f wikijs-ca-configmap.yml             

```
I'm not sure what type of certificate is required (.pem, .crt etc.)?

The wikijs-ca-configmap.yml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca
  namespace: wikijs
data:
  certs.pem: |-
    -----BEGIN PRIVATE KEY-----
    -----END CERTIFICATE-----
```

​

The Helm chart:

```
volumeMounts:
  - name: ca
    mountPath: /cas.pem
    subPath: certs.pem

volumes:
  - name: ca
    configMap:
      name: ca
...
postgresql:
  ## Use the PostgreSQL chart dependency.
  ## Set to false if bringing your own PostgreSQL, and set secret value postgresql-uri.
  ##
  enabled: true
  ## ssl enforce SSL communication with PostgresSQL
  ## Default to false
  ##
  ssl: true
  ## ca Certificate of Authority
  ## Default to empty, point to location of CA
  ##
  ca: "/cas.pem"
...

```
I get the following error: "Database Connection Error: The server does not support SSL connections"

How do I activate SSL on the Database site?

I am grateful for any kind of help!
