### DISCUSSION TITLE
Deployment successful but data/sideload folder absent

### DISCUSSION THREAD

**Discussion by schmittvictor** [requarks/wiki#6997] [Error / Bug Report]
Hello,

I am trying to install wikijs on rk2 cluster.

I cant get the locales working.

The /wiki/data/sideload folder is not present in the wiki container even tho the sideload container succeeded.

Is there any fix ?

Here is my values.yaml

```
affinity: {}
fullnameOverride: ''
image:
  imagePullPolicy: IfNotPresent
  repository: docker-repo.xxxxx.com:18440/requarks/wiki
imagePullSecrets: []
ingress:
  annotations: {}
  className: ''
  enabled: true
  hosts:
    - host: wiki.xxxx.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
livenessProbe:
  httpGet:
    path: /healthz
    port: http
nameOverride: ''
nodeSelector: {}
podSecurityContext: {}
postgresql:
  enabled: true
  fullnameOverride: ''
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 8Gi
  postgresqlDatabase: wiki
  postgresqlUser: postgres
  replication:
    enabled: false
  image:
    registry: docker-repo.xxxxxxx.com:18440
  volumePermissions:
    image:
      registry: docker-repo.xxxxxxx.com:18440
readinessProbe:
  httpGet:
    path: /healthz
    port: http
replicaCount: 1
resources: {}
revisionHistoryLimit: 10
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: null
sideload:
  enabled: true
  env:
    - name: HTTPS_PROXY
      value: http://xxxx:xxxxxx@xxxxxxx:8080
  repoURL: https://github.com/Requarks/wiki-localization
startupProbe:
  failureThreshold: 60
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 15
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5
tolerations: []
volumeMounts: []
volumes: []
````
