### DISCUSSION TITLE
podman start of `ghcr.io/requarks/wiki:2` fails with `Error: Cannot find module '/wiki/start'`

### DISCUSSION THREAD

**Discussion by col-panic** [requarks/wiki#7048] [Error / Bug Report]
Starting the following `docker-compose.yml` file with `podman-compose up` 
```
services:
  wikijs:
    image: ghcr.io/requarks/wiki:2
    restart: unless-stopped
    export:
      - 3000
    command:
      - start
    networks:
      - backend
    mem_limit: 512M
    memswap_limit: 512M
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=dbname
      - DB_USER=wikijs
      - DB_PASS=pass
```

results in the following start-up with fail exit

```
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module '/wiki/start'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.19.0
<SOME TIME PASSES>
exit code: 1
```
