### DISCUSSION TITLE
Container not honoring port mapping

### DISCUSSION THREAD

**Discussion by git-n-pissed** [requarks/wiki#7056] [Help / Questions]
My compose file. Note that volumes are commented out because I was debugging and going scorched Earth between each run:

```
networks:
  docker_net:
    external: true
services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: wikijs_db
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: password
    logging:
      driver: 'none'
    restart: always
#    volumes:
#      - ./wikijs/db_data/:/var/lib/postgresql/data/
    networks:
      - docker_net
  wiki:
    image: requarks/wiki:2.5.301
    container_name: wikijs
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: wikijs
      DB_USER: wikijs
      DB_PASS: password
    restart: always
    ports:
      - '8080:3000'
    networks:
      - docker_net
 ```

I've got multiple subdomains running behind a reverse proxy.  In this example I want `wikijs` to respond to port 8080 as the configuration shows, but the container only responds to port 3000.  Strangely, with this configuration I can change my reverse proxy from 8080 to 3000 and get wikijs to pull up in a browser, which doesn't seem like it should be possible.  Entering into the container and running `curl localhost:3000` and `curl localhost:8080` confirms that the former responds, and the latter does not.
