### DISCUSSION TITLE
How do I create backups in Local File System?

### DISCUSSION THREAD

**Discussion by Loweredgames** [requarks/wiki#7097] [Help / Questions] [answered]
Hi, I'm new, I tried to create a backup with the "Local File System" option, I put the destination folder but nothing happens. Why? I use docker.

what I want is to create a backup of everything the server (wiki.js) contains in a folder (my wiki).

**Comment by fnafox** [comment]
if you're running in a docker container then "local file system" refers to the container's filesystem, not the host.
you could mount a directory and then point your local fs backups there by adding the mount argument to the docker command like this:
here `/var/backup/wiki` on the host will be mounted to `/mnt` on the container, then you can point local fs backups to `/mnt`.
```bash
docker run -d \
        -p 8080:3000 \
        --name wiki \
        --restart unless-stopped \
        --mount type=bind,source=/var/backup/wiki,target=/mnt \
        ghcr.io/requarks/wiki:2
```
if you use docker compose then that would look like this:
```yaml
version: "3"
services:
  wiki:
      volumes:
       - type: bind
         source: /var/backup/wiki
         target: /mnt
```

**Reply by Loweredgames** [reply]
I use docker-compose but I followed the tutorial wiki.js and now it looks like this:
where should I put it? under volume?

_version: "3"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
volumes:
  db-data:_

**Reply by fnafox** [reply]
It would look like this. Also, please make sure you create the folder on your host first: `mkdir -p /var/backup/wiki`
```yaml
version: "3"
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: /var/backup/wiki
        target: /mnt

volumes:
  db-data:
```
