### DISCUSSION TITLE
File list in editor does not render correctly

### DISCUSSION THREAD

**Discussion by b90g** [requarks/wiki#7115] [Error / Bug Report]
When I am in the editor view (markdown) and want to include a file the file list/explorer etc doesnt  show.

I get this blob:
![grafik](https://github.com/requarks/wiki/assets/63392812/b58618d8-7d8f-4dd1-8107-c1c9ca87c28c)

**Comment by HerHde** [comment]
The element causing it is `<div class="editor-modal-media animated fadeInLeft v-card v-card--flat v-sheet theme--light rounded-0 is-editor-markdown">`, where the following CSS is overwriting the width:

```css
.v-application .rounded-0 {
	border-radius: 0 !important;
	width: 150px !important;
}
```

The Wiki.js version is `2.5.301` (as the package.json states).

Running a fresh container the `width: 150px !important;` is missing from the class. Where could that come from?

(We're using the same instance)
