### DISCUSSION TITLE
Wiki.js + Advanced Search module in one docker-compose.yml

### DISCUSSION THREAD

**Discussion by vawaver** [requarks/wiki#7166] [Help / Questions]
Greetings,

I need some help integrating an advanced search module into my Wiki.js, which I have deployed as a Docker container on an Ubuntu server 22.04. The primary languages for the content on my wiki are **Slovak and Czech**. After adding content, I've noticed that the search function operates only in basic mode.

From my research, it seems that linking it with an advanced search engine like Elasticsearch could solve this issue. I am not an IT professional and have been trying to handle this at an amateur level, but despite several attempts, I haven’t found a solution that allows running Wiki.js and Elasticsearch together in a single docker-compose.yml file.

Would anyone who has a working setup be willing to share their docker-compose.yml file? Alternatively, if there are other functional solutions using Docker, I would greatly appreciate any information on that.

As mentioned, I am an IT amateur and prefer solutions that involve Docker. Below is my basic docker-compose.yml file, which I would like to modify to include an advanced search module. I look forward to your responses.

Thank you!
``` 
version: "3"
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - /home/tony/wikijs/config:/config
      - /home/tony/wikijs/data:/data
    ports:
      - 9150:3000
    restart: unless-stopped
```

**Comment by CharlesRaces** [comment]
I'm using an Elastic Search container and it works well.

You just have to add the following in the docker-compose.yml:

 ```
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    restart: unless-stopped
```

The ES_JAVA_OPTS line is the Java shared memory size, and it is optional but recommended. If not set, ElasticSearch will use half of the System Memory by Default.

Once you have done the docker-compose up, you must go to yout Wiki.js page, into the Administration Dashboard and in Search Engines > Elastic Search:

Version: 7.X
Host: http://elasticsearch:9200
If you use 'container_name: YOUR_CONTAINER_NAME' in the docker-compose file, you must change the value of Host to:
"http://YOUR_CONTAINER_NAME:9200" to let Wiki.js know where to send/receive the data,
I don't use TLS so I can't help you with that as I keep that option unchecked, sorry :(

Notice the port 9200, it is not needed to open it with the docker-compose file, as the two containers exisist in the same docker-compose, they can see each other without the need to open the ports in your localhost/machine.

Hope it works for you 👍 

PS: If I'm not mistaken, in Wiki.js v3 (don't know when it'll be released) the 3rd parties search engines will be depricated as seen here:
https://github.com/requarks/wiki/issues/6844
"External search engines are no longer supported. Replaced with a single native advanced PostgreSQL search engine."
