### DISCUSSION TITLE
Kubernetes Ingress setup in subdirectory

### DISCUSSION THREAD

**Discussion by asazanowicz** [requarks/wiki#7206] [Help / Questions]
## Problem
I have a problem running Wiki.js docker container on Kubernetes under subdirectory:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "test-ingress"
  namespace: "wikijs"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "True"
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      paths:
      - path: "/test-account(/|$)(.*)"
        pathType: Prefix
        backend:
          service:
            name: my-svc
            port:
              number: 80
```
## Result
curl https://example.com/test-wiki

```bash
Request URL:
https://example.com/test-account
Request Method:
GET
Status Code:
200 OK
Remote Address:
54.163.18.15:443
Referrer Policy:
strict-origin-when-cross-origin

Request URL:
https://example.com/_assets/css/setup.144bf2418396de2cf85d.css
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
54.163.18.15:443
Referrer Policy:
strict-origin-when-cross-origin

Request URL:
https://example.com/_assets/js/runtime.js?1716156900
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
54.163.18.15:443
Referrer Policy:
strict-origin-when-cross-origin

Request URL:
https://example.com/_assets/js/setup.js?1716156900
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
54.163.18.15:443
Referrer Policy:
strict-origin-when-cross-origin
```

## Desired 
Assets must be available under relative path: domain/test-account
