### DISCUSSION TITLE
WikiJS locales not loading

### DISCUSSION THREAD

**Discussion by L-Clem** [requarks/wiki#7230] [Help / Questions] [answered]
Hello everyone.

# The problem
I'm hosting a wikijs instance on a Kubernetes cluster with a proxy upfront.
I'm trying to download the locales, but when I install my application using the Helm chart in version **2.2.20** I get an error:
```txt
...:27:53.003Z [MASTER] info: Syncing locales with Graph endpoint...
...:27:53.004Z [MASTER] info: Fetching latest updates from Graph endpoint...
...:27:53.092Z [MASTER] info: Purging orphaned upload files: [ COMPLETED ]

Loading configuration from /wiki/config.yml... OK

...:27:53.241Z [JOB] info: Rebuilding page tree...
...:27:53.819Z [JOB] info: Using database driver pg for postgres [ OK ] 
...:27:54.101Z [JOB] info: Rebuilding page tree: [ COMPLETED ] 
...:28:03.083Z [MASTER] error: Syncing locales with Graph endpoint: [ FAILED ] 
...:28:03.083Z [MASTER] error: fetch failed      
...:28:03.084Z [MASTER] error: Fetching latest updates from Graph endpoint: [ FAILED ]  
...:28:03.084Z [MASTER] error: fetch failed   
```

# What  I tried
## Proxy
The proxy is set into my cluster and my VMs with http_proxy, https_proxy, HTTP_PROXY and HTTPS_PROXY.

- I whitelisted: 
  - graph.requarks.io, 
  - *.js.wiki,
  - github.com.

- I tried adding HTTP_PROXY and HTTPS_PROXY variables to the container (I also added them to the sideloading container using the values file).
- I tried to curl github.com, but it is being time outed.
- When I nslookup GitHub or other website there isn't any problems.

## Sideloading
- I tried mounting an NFS volume inside `/wiki/data/sideload` with the `locales.json` and `en.json` files inside in chmod 777, but it didn't work.
- I tried adding the `sideload.enabled` property of the chart to its values file, nothing.
- I tried combining the volume with the sideload container, same.
- I tried cloning the repo _https://github.com/Requarks/wiki-localization_ inside the containers. It didn't work inside the container but worked inside the sideloading one.

## What I didn't try
- Adding the `git config --global http.proxy` setting to the container.

# Conclusions
So I can't see where the problem could be and why I can't even load those locales using the simplest copy and paste method?
Can you help me? Thanks in advance.

**Comment by fnafox** [comment, marked as answer]
config.yml needs to contain `offline: true` for sideload to work, i suggest creating a configmap with your custom config and mounting it in the deployment. After that your sideload approach should work fine!
```yaml
spec:
  template:
    spec:
      volumes:
        - name: wiki-conf
          configMap:
            name: wiki-conf
      containers:
        - name: wiki
          volumeMounts:
            - name: wiki-conf
              mountPath: /wiki/config.yml
              subPath: config.yml
```
