### DISCUSSION TITLE
Authorization suddenly stopped working

### DISCUSSION THREAD

**Discussion by muflondev** [requarks/wiki#7253] [Error / Bug Report]
Hi, I've been using self-hosted WikiJS for almost a year and today it suddenly stopped working. More specifically, what happens is:

1. It asks me to login and then tells me "login successful".
2. But then it immediately shows "Unauthorized page". Whatever page I try to access I always get the same screen.
3. If I try to log in again, I get exactly the same behaviour.

I have successfully used it for quite a while and never experienced this problem. I guess it might have to do with some password expiry, but I have no clue how to fix it. Any comments/suggestions would be appreciated, thanks :)

![Zrzut ekranu z 2024-07-11 12-54-10](https://github.com/requarks/wiki/assets/168108972/be287a66-2005-40af-94d4-2210947b8eb3)

![Zrzut ekranu z 2024-07-11 12-54-17](https://github.com/requarks/wiki/assets/168108972/33c19d65-aa66-48eb-bc0f-0eef65c6b862)

In case this is relevant, I'm running WikiJS through the standard `docker-compose` file:

```
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
```
