### DISCUSSION TITLE
Deploy WikiJS via Docker with Postgress in host machine

### DISCUSSION THREAD

**Discussion by jhm-ciberman** [requarks/wiki#7260] [Help / Questions]
Hello! I want to deploy WikiJS using Docker, but with Postgress running in the host machine, not in docker. Why? Because I already have a robust system for DB backups that I want to use. 

The problem is that when I try to run the WikiJS container, the app cannot connect to the Database:

```log
$ sudo docker compose up --remove-orphans
[+] Running 2/2
 ✔ Container wiki-update-companion  Created                                                                                                                                                                 0.0s
 ✔ Container wiki                   Recreated                                                                                                                                                               0.1s
Attaching to wiki, wiki-update-companion
wiki                   | Loading configuration from /wiki/config.yml... OK
wiki                   | 2024-07-19T01:24:31.472Z [MASTER] info: =======================================
wiki                   | 2024-07-19T01:24:31.474Z [MASTER] info: = Wiki.js 2.5.303 =====================
wiki                   | 2024-07-19T01:24:31.475Z [MASTER] info: =======================================
wiki                   | 2024-07-19T01:24:31.475Z [MASTER] info: Initializing...
wiki-update-companion  | {"level":30,"time":1721352271676,"pid":1,"hostname":"wiki-update-companion","msg":"Server listening at http://0.0.0.0:80"}
wiki                   | 2024-07-19T01:24:32.277Z [MASTER] info: Using database driver pg for postgres [ OK ]
wiki                   | 2024-07-19T01:24:32.283Z [MASTER] info: Connecting to database...
wiki                   | 2024-07-19T01:25:02.297Z [MASTER] error: Database Connection Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
wiki                   | 2024-07-19T01:25:02.297Z [MASTER] warn: Will retry in 3 seconds... [Attempt 1 of 10]
wiki                   | 2024-07-19T01:25:05.301Z [MASTER] info: Connecting to database...
wiki                   | 2024-07-19T01:25:35.328Z [MASTER] error: Database Connection Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
wiki                   | 2024-07-19T01:25:35.328Z [MASTER] warn: Will retry in 3 seconds... [Attempt 2 of 10]
wiki                   | 2024-07-19T01:25:38.331Z [MASTER] info: Connecting to database...

```

My docker-compose looks like the following:

```yml
networks:
  wikinet:

services:
  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki
    restart: unless-stopped
    hostname: wiki
    networks:
      - wikinet
    ports:
      - "80:3000"
      - "443:3443"
    environment:
      DB_TYPE: postgres
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      UPGRADE_COMPANION: '1'

  wiki-update-companion:
    image: ghcr.io/requarks/wiki-update-companion:latest
    container_name: wiki-update-companion
    restart: unless-stopped
    hostname: wiki-update-companion
    networks:
      - wikinet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

My ENV file looks like this:

```env
DB_HOST=172.17.0.1  # This is my docker0 ip address
DB_PORT=5432
DB_DATABASE=wiki
DB_USERNAME=wiki
DB_PASSWORD=my_secure_password
```

I can connect from [TablePlus](https://tableplus.com/) to my database. But the container cannot connect. 

If I place the DB as another container inside the network, it works fine. But I don't want that since I won't be able to make backups easily using the existing tools I use. 

Thanks. 

## Extra info: 

Ubuntu 24.04 LTS
Postgress 16
Running on Laravel Forge on an AWS EC2 instance (`t4g.micro`)
