### DISCUSSION TITLE
Docker - MSSQL - ETIMEOUT undefined:undefined

### DISCUSSION THREAD

**Discussion by christopherfowers** [requarks/wiki#7301] [Error / Bug Report]
Attempting to set up my docker install for wiki.js version 2.5.303

2024-08-13T23:39:08.545Z [MASTER] info: =======================================
2024-08-13T23:39:08.547Z [MASTER] info: = Wiki.js 2.5.303 =====================
2024-08-13T23:39:08.547Z [MASTER] info: =======================================
2024-08-13T23:39:08.547Z [MASTER] info: Initializing...
2024-08-13T23:39:09.255Z [MASTER] info: Using database driver mssql for mssql [ OK ]
2024-08-13T23:39:09.258Z [MASTER] info: Connecting to database...
2024-08-13T23:39:24.322Z [MASTER] error: Database Connection Error: ETIMEOUT undefined:undefined

```
  wiki:
    image: ghcr.io/requarks/wiki:2.5
    environment:
      DB_TYPE: mssql
      DB_HOST: <my sql host IP address removed for security>
      DB_PORT: 1433
      DB_USER: wikijs
      DB_PASS: '<my password removed for this example>'
      DB_NAME: wiki
    restart: unless-stopped
    ports:
     - "8075:3000"
```

I did access the running container interactive bash to confirm that I can reach the host of the sql server. All was behaving as expected there. By seeing undefined in the error message for host and port used in timeout, it feels like wiki.js is not using my environment variables for the connection attempt. 

I also confirmed in my sql logs that no connection attempt reached my server to fail. 

I am happy to help clarify anything if I left anything out or articulated this poorly.
