### DISCUSSION TITLE
Problem with connection to db

### DISCUSSION THREAD

**Discussion by mukhammart** [requarks/wiki#7388] [Help / Questions]
I've installed wikijs with the help of docker compose. 
**docker-compose.yaml** file looks like:

``` 
version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # need to use env
      POSTGRES_USER: wikijs
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U wikijs']
      interval: 10s
      timeout: 5s
      retries: 5

  wiki:
    image: ghcr.io/requarks/wiki:2.5 #  the latest stable version 
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DB_PASS} # need to use env
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - '127.0.0.1:3080:3000' # Bind to localhost for added security
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthz']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:
    driver: local
```

and **.env** file looks like:

`
POSTGRES_PASSWORD = wikijsrocks,
DB_PASS = wikijsrocks
`

After running the container such error occurs:
2024-10-15 21:21:57 wiki-1  | 2024-10-15T16:21:57.970Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
2024-10-15 21:21:57 wiki-1  | 2024-10-15T16:21:57.970Z [MASTER] warn: Will retry in 3 seconds... [Attempt 9 of 10]
2024-10-15 21:22:00 wiki-1  | 2024-10-15T16:22:00.975Z [MASTER] info: Connecting to database...
2024-10-15 21:22:00 db-1    | 2024-10-15 16:22:00.983 UTC [64] FATAL:  password authentication failed for user "wikijs"

Could you help me with that? The same configuration works on another machine, here it does not.
