### DISCUSSION TITLE
EACCES: permission denied while installing Helm Chart

### DISCUSSION THREAD

**Discussion by Najafov007** [requarks/wiki#7443] [Error / Bug Report]
Hello, so we recently installed wikijs using helm-chart and after registration it gives me EACCES: permission denied, mkdir '/wiki/data/cache'. Here's our manifest
```
containerSecurityContext:
  enabled: false
image:
  repository: requarks/wiki
  tag: '2.5'
ingress:
  enabled: false
persistence:
  enabled: true
  size: 5Gi
  storageClass: thin-csi
podSecurityContext:
  enabled: false
postgresql:
  enabled: false
  postgresqlDatabase: <db-name>
  postgresqlHost: postgresql
  postgresqlPassword: <password>
  postgresqlPort: 5432
  postgresqlUser: <user>
service:
  port: 3000
  type: ClusterIP
```
  
 When I type runAs 1000 it says it must be in range [1000950000 - 1000959999]. How can I solve this problem
