### DISCUSSION TITLE
Environment variable for log levels does not work

### DISCUSSION THREAD

**Discussion by washeeeq** [requarks/wiki#7472] [Error / Bug Report] [answered]
We tried to change log level to verbose|debug in order to debug Keycloak integration but it appears the log level did not change at all.

Steps:
1. We checked where default config is to be found in docker container:
```
cat config.yml
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: letsencrypt
  domain: $(LETSENCRYPT_DOMAIN)
  subscriberEmail: $(LETSENCRYPT_EMAIL)
logLevel: $(LOG_LEVEL:info)
logFormat: $(LOG_FORMAT:default)
ha: $(HA_ACTIVE)
```
2. Changed our dokcker-compose file to include LOG_LEVEL set to debug.
3. Restarted docker container with new LOG_LEVEL
4. Verified entering docker container using printenv we can see
```
LOG_LEVEL=debug
```
6. Still see no debug lines logged, it appears that either config is wrong or application ignores it

RUNTIME: Docker
VM: Ubuntu 24 LTS
