### DISCUSSION TITLE
Connection to MySQL server fails with `ER_ACCESS_DENIED_ERROR undefined:undefined`

### DISCUSSION THREAD

**Discussion by ColinTimBarndt** [requarks/wiki#7501] [Help / Questions]
I'm trying to get Wiki JS to connect to my database. I have already verified that I can connect to the database using the same credentials using `mariadb -h mysql.home.kat -u wikijs -p wikijs` (port 3306 is inferred via DNS SRV entry)

```
OS: Alpine 3.18 
Wiki.js version: v2.5.305
Database engine: 10.11.8-MariaDB Alpine Linux
```

<details><summary>Relevant Configuration</summary>

```yml
db:                                                                                                                 
  type: mysql                                                                                                       
                                                                                                                    
  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:                                                              
  host: mysql.home.kat                                                                                              
  port: 3306                                                                                                        
  user: wikijs 
  pass: "REDACTED" # openssl rand -hex 32
  db: wikijs                                                                                                        
  ssl: false                                                                                                        
                                                                                                                    
  # Optional - PostgreSQL / MySQL / MariaDB only:                                                                   
  # -> Uncomment lines you need below and set `auto` to false                                                       
  # -> Full list of accepted options: https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options           
  sslOptions:                                                                                                       
    auto: true                                                                                                      
    # rejectUnauthorized: false                                                                                     
    # ca: path/to/ca.crt                                                                                            
    # cert: path/to/cert.crt                                                                                        
    # key: path/to/key.pem                                                                                          
    # pfx: path/to/cert.pfx                                                                                         
    # passphrase: xyz123
```

</details>

To make sure that the password length is not the problem, I also changed it to `openssl rand -hex 16` (32 characters). _Edit: I've also used just 12 a-z characters now._ Exact same issue. I also modified `core/db.js` to get more info:
```
Database Connection Error: ER_ACCESS_DENIED_ERROR undefined:undefined, Access denied for user 'wikijs'@'10.8.10.37' (using password: YES)
```
I've also verified that `Knex` is receiving the correct db config data.

Am I doing something wrong or is this a bug in `Knex`?

Edit: I could replicate the problem using only Knex, leading me to the assumption that this is not the fault of WikiJS'.
https://github.com/knex/knex/issues/6168
