### DISCUSSION TITLE
Helmchart - Postgresql integration not working as expected

### DISCUSSION THREAD

**Discussion by seraphblade2010** [requarks/wiki#7517] [Help / Questions]
Hey there, I have tried to install wiki.js via your provided helmchart but it seems your helmchart is not up-to-date.
When using the following key:
- postgresql.postgresqlUser

The user does not get created but instead it just uses the default postgres user, regardless if a custom value is supplied.
Furthermore the following keys listed in the readme do not exist in the helmchart values and thus cant be used:
- postgresql.existingSecretKey

Please update the helmchart to reflect these issues or tell me whats wrong with my values listed below, thanks :) :

```
    postgresql:
      enabled: true
      postgresqlUser: wikijs # Not working
      existingSecret: sealed-secret-wiki-js-passwords
      postgresqlDatabase: wiki
      persistence:
        enabled: true
        size: 8Gi
        storageClass: "proxmox-data-infrastructure"
```
