### DISCUSSION TITLE
ingressClassName not being set

### DISCUSSION THREAD

**Discussion by jseiser** [requarks/wiki#7540] [Error / Bug Report]
This worked previously, but appears to have died during the upgrade to the latest stable image.

```
❯ helm -n wikijs get values wikijs     
USER-SUPPLIED VALUES:
image:
  tag: 2.5.306
ingress:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-r53-prod
    nginx.ingress.kubernetes.io/service-upstream: "true"
  className: nginx-external
  enabled: true
```

```
❯ kubectl get ingress -n wikijs        
NAME     CLASS    HOSTS                    ADDRESS   PORTS     AGE
wikijs   <none>   wiki.domain.com             80, 443   6m18s
```

```
 kubectl version    
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.9-eks-8cce635
```
