### DISCUSSION TITLE
[Bug] "warn: DB Configuration is empty or incomplete. Switching to Setup mode" even if config is complete

### DISCUSSION THREAD

**Discussion by benjamsf** [requarks/wiki#7547] [Error / Bug Report] [answered]
Hello! So I'm trying to run Wikijs under docker with the goal of providing configs so, that I don't have to click on gui installer. 

What I'm persistently getting is this:

```
wikijs   | Loading configuration from /wiki/config.yml... OK
wikijs   | 2025-02-20T23:28:46.000Z [MASTER] info: =======================================
wikijs   | 2025-02-20T23:28:46.001Z [MASTER] info: = Wiki.js 2.5.306 =====================
wikijs   | 2025-02-20T23:28:46.001Z [MASTER] info: =======================================
wikijs   | 2025-02-20T23:28:46.001Z [MASTER] info: Initializing...
wikijs   | 2025-02-20T23:28:46.244Z [MASTER] info: Using database driver pg for postgres [ OK ]
wikijs   | 2025-02-20T23:28:46.246Z [MASTER] info: Connecting to database...
wikijs   | 2025-02-20T23:28:46.267Z [MASTER] info: Database Connection Successful [ OK ]
wikijs   | 2025-02-20T23:28:46.294Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
wikijs   | 2025-02-20T23:28:46.294Z [MASTER] info: Starting setup wizard...
wikijs   | 2025-02-20T23:28:46.382Z [MASTER] info: Starting HTTP server on port 3000...
wikijs   | 2025-02-20T23:28:46.382Z [MASTER] info: HTTP Server on port: [ 3000 ]
wikijs   | 2025-02-20T23:28:46.383Z [MASTER] info: HTTP Server: [ RUNNING ]
wikijs   | 2025-02-20T23:28:46.383Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
wikijs   | 2025-02-20T23:28:46.383Z [MASTER] info: 
wikijs   | 2025-02-20T23:28:46.383Z [MASTER] info: Browse to http://YOUR-SERVER-IP:3000/ to complete setup!
wikijs   | 2025-02-20T23:28:46.384Z [MASTER] info: 
wikijs   | 2025-02-20T23:28:46.384Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
```
I have double checked that config.yml populates exactly as the example one in docs shows:

```
#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full documentation + examples:
# https://docs.requarks.io/install

# ---------------------------------------------------------------------
# Port the server should listen to
# ---------------------------------------------------------------------
port: 3000

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
db:
  type: postgres
  host: wiki_db
  port: 5432
  user: wikijs
  pass: wikijs_pass
  db: wikijsdb
  ssl: false

  # Optional - PostgreSQL / MySQL / MariaDB only:
  sslOptions:
    auto: true

  # Optional - PostgreSQL only:
  schema: public

#######################################################################
# ADVANCED OPTIONS                                                    #
#######################################################################
# Do not change unless you know what you are doing!

# ---------------------------------------------------------------------
# SSL/TLS Settings
# ---------------------------------------------------------------------
ssl:
  enabled: false
  port: 3443
  provider: custom
  format: pem

# ---------------------------------------------------------------------
# IP address the server should listen to
# ---------------------------------------------------------------------
bindIP: 0.0.0.0

# ---------------------------------------------------------------------
# Log Level
# ---------------------------------------------------------------------
logLevel: info

# ---------------------------------------------------------------------
# Offline Mode
# ---------------------------------------------------------------------
offline: false

# ---------------------------------------------------------------------
# High-Availability
# ---------------------------------------------------------------------
ha: false

# ---------------------------------------------------------------------
# Data Path
# ---------------------------------------------------------------------
dataPath: ./data
```

And here is my docker-compose.yml:

```
version: "3.8"

services:
  wiki_db:
    image: postgres:14
    container_name: wiki_db
    environment:
      POSTGRES_DB: ${WIKI_DB_NAME:-wikijsdb}
      POSTGRES_USER: ${WIKI_DB_USER:-wikijs}
      POSTGRES_PASSWORD: ${WIKI_DB_PASS:-wikijs_pass}
      PGSSLMODE: disable
    networks:
      - intranet
    volumes:
      - wiki_db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "ssl=off"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${WIKI_DB_USER:-wikijs} -d ${WIKI_DB_NAME:-wikijsdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  wikijs:
    image: requarks/wiki:2.5
    container_name: wikijs
    depends_on:
      wiki_db:
        condition: service_healthy
    environment:
      CONFIG_FILE: "/wiki/config.yml"  # Ensure Wiki.js uses this path
    networks:
      - intranet
    volumes:
      - wikijs_data:/wiki/data
      - ./wikijs/config/config.yml:/wiki/config.yml  # Corrected volume mount!
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  wiki_db_data:
  wikijs_data:

networks:
  intranet:
```
