### DISCUSSION TITLE
Running in a high available cluster

### DISCUSSION THREAD

**Discussion by Tockra** [requarks/wiki#7629] [General]
Hello,

I wanted to ask which requirements I need to fulfill to run wikijs with multiple replicas, without session problems if a user use different pods for its requests. 

ChatGPT says I need to set:
```
replicaCount: 3

env:
  - name: SESSION_STORE_TYPE
    value: redis
  - name: SESSION_STORE_HOST
    value: redis.default.svc.cluster.local
  - name: SESSION_STORE_PORT
    value: "6379"
```

But I'm not sure, because I see no docs about it.
is it really necessary to use a redis and there is no possiblity to deploy one with the existing helm chart?

T
