### DISCUSSION TITLE
Failed to obtain access token

### DISCUSSION THREAD

**Discussion by EBS-DarkD** [requarks/wiki#7667] [Help / Questions]
OS: Debian 12
Docker: 20.10.4
Portainer: BE 2.27.6 LTS
Authentik: 2025.6.0

I'm running the wiki as a portainer stack as outlined below

```
services:

  wik-db:
    <<: *common-keys-apps
    image: postgres:15-alpine3.22
    container_name: wik-db
    networks:
      t2_proxy:
    volumes:
      - ./wikijs/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wiki11
      POSTGRES_PASSWORD: ${WIK_DB_PW}
      POSTGRES_USER: wikijs
    env_file:
      - stack.env

  wik11:
    <<: *common-keys-apps
    image: ghcr.io/requarks/wiki:2
    container_name: wik11-app
    networks:
      t2_proxy:
    ports:
      - "3000:3000"
    volumes:
      - ./wikijs/sideload:/wiki/data/sideload
      - ./wikijs/config.yml:/wiki/config.yml
      - ./certs:/certs
    environment:
      DB_TYPE: postgres
      DB_HOST: wik-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${WIK_DB_PW}
      DB_NAME: wiki11
      NODE_EXTRA_CA_CERTS: /certs/cert.pem
    env_file:
      - stack.env
```
my config.yml is

```
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: custom
  format: pem
  key: /certs/cert-k.pem
  cert: /certs/cert.pem
logLevel: $(LOG_LEVEL:info)
logFormat: $(LOG_FORMAT:default)
ha: $(HA_ACTIVE)
offline: false
```

Local login is working ok but I'm trying to get login through authentik working using OAuth2

I've followed the authentik guide here https://docs.goauthentik.io/integrations/services/wiki-js/ to configure both ends of the OAuth but I'm getting "Failed to obtain access token"

I'm looking for a bit of advice on fault finding on the wiki.js side of the authentication. Note that I did have this working about 2-3 weeks ago but I upgraded both the authentik and wiki js and i've not been able to get it working since!
