### DISCUSSION TITLE
New docker installation fails to start: Cannot find module '/wiki/server'

### DISCUSSION THREAD

**Discussion by dcolley** [requarks/wiki#7686] [Error / Bug Report]
Attempting to install wiki.js from https://docs.requarks.io/install/docker

Here is my docker-compose.yml

```yml
services:

  wiki:
    image: ghcr.io/requarks/wiki:2
    ports:
      - 8080:8080
    volumes:
      - ./data/wiki:/wiki
      # - ./wiki-config.yml:/wiki/config.yml
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=wiki
      - DB_USER=wiki
      - DB_PASS=wiki
      - DB_ROOT_USER=root
      - SSL_ACTIVE=false
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wiki
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=wiki
```
logs from container:

```bash
node:internal/modules/cjs/loader:1215

  throw err;

  ^


Error: Cannot find module '/wiki/server'

    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)

    at Module._load (node:internal/modules/cjs/loader:1043:27)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)

    at node:internal/main/run_main_module:28:49 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}


Node.js v20.19.0
```
