### ISSUE TITLE
Invalid DB type

### ISSUE THREAD

**Issue by deadbird99** [Requarks/wiki#1038]
I know there is another Issue with this exact name, but this one is weird...at least to me.
I use a slightly customized version of docker-compose file found [here](https://docs.requarks.io/en/install/docker)  but beautified to avoid errors:

```
version: '3'
services:
  db:
    image: 'postgres:9-alpine'
    environment:
      - 'POSTGRES_DB: wiki'
      - 'POSTGRES_PASSWORD: wikijsrocks'
      - 'POSTGRES_USER: wikijs'
    logging:
      driver: none
    volumes:
      - 'db-data:/var/lib/postgresql/data'
  wiki:
    image: 'requarks/wiki:beta'
    depends_on:
      - db
    environment:
      - 'DB_TYPE: postgres'
      - 'DB_HOST: db'
      - 'DB_PORT: 5432'
      - 'DB_USER: wikijs'
      - 'DB_PASS: wikijsrocks'
      - 'DB_NAME: wiki'
      - VIRTUAL_HOST=monitor.x99.fr
      - VIRTUAL_PORT=19998
      - LETSENCRYPT_HOST=monitor.x99.fr
      - LETSENCRYPT_EMAIL=x99@x99.fr
    ports:
      - '19998:3000'
networks:
  default:
    external:
      name: mynet
volumes:
  db-data:
```

and each time I get this error:

```
db_1    | WARNING: no logs are available with the 'none' log driver
wiki_1  | Loading configuration from /wiki/config.yml... OK
wiki_1  | 2019-09-17T13:16:16.436Z [MASTER] info: =======================================
wiki_1  | 2019-09-17T13:16:16.438Z [MASTER] info: = Wiki.js 2.0.0-beta.303 ==============
wiki_1  | 2019-09-17T13:16:16.438Z [MASTER] info: =======================================
wiki_1  | 2019-09-17T13:16:16.438Z [MASTER] info: Initializing...
wiki_1  | 2019-09-17T13:16:16.580Z [MASTER] error: Invalid DB Type
wiki2_wiki_1 exited with code 1
```

Am I missing something?

**Comment by NGPixel** [comment]
That's not a valid way to declare env vars. Remove the quotes around the var names. Refer to the example.

**Comment by deadbird99** [comment]
Still the same with this one:

```
version: '3'
services:
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: none
    volumes:
      - db-data:/var/lib/postgresql/data
  wiki:
    image: requarks/wiki:beta
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    environment:
      - VIRTUAL_HOST=xxxxxxxxxx.fr
      - VIRTUAL_PORT=19998
      - LETSENCRYPT_HOST=xxxxxxxxxx.fr
      - LETSENCRYPT_EMAIL=xxxxxxxxxx@xxxxxxxxxx.fr
    ports:
      - '19998:3000'
networks:
  default:
    external:
      name: mynet
volumes:
  db-data:
```
