### ISSUE TITLE
Raise upload limit (maxFileSize)

### ISSUE THREAD

**Issue by Rijswijker** [Requarks/wiki#1060]
**Question**
Is there a way to increase the upload size?
I am using the docker-compose install method, i want to raise the upload limit to 10MB instead of 5MB.
Can I do this by giving a parameter in the docker-compose.yml file?
 
**Host Info (please complete the following information):**
OS: Qnap NAS with Linux 4.2.8 and Docker version 17.09.1-ce, build 0a5102e
Wiki.js version: [e.g. 2.0.0-beta.303]
Database engine: [postgres]

**Comment by NGPixel** [comment]
https://github.com/Requarks/wiki/blob/master/config.sample.yml#L105

**Comment by Rijswijker** [comment]
Hi NGPixel,

How can i modify this setting within the docker-compose file?

**docker-compose.yml**
```
version: "3"
services:

  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - wikinet

  wiki:
    image: requarks/wiki:beta
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    networks:
      - wikinet
    ports:
      - "82:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example

networks:
  wikinet:

volumes:
  db-data:
```

**Comment by Rijswijker** [comment]
Found the solution

```
version: "3"
services:

  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - wikinet

  wiki:
    image: requarks/wiki:beta
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    volumes:
      - ./config.yml:/wiki/config.yml:rw  # <--- Path to config file
    user: 0:0  # <--- uid:gid otherwise you have permission issues, and docker thinks it is a folder instead of a file.

    networks:
      - wikinet
    ports:
      - "82:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example

networks:
  wikinet:

volumes:
  db-data:
```

**Comment by Chibald** [comment]
Using above example it was trying to map the config.yml to a folder. The "user:0:0" bit didn't seem to fix this. The solution is to make sure a config.yml exists at the mapped location. 

for example:

docker-compose.yml
```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2.1-arm
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    volumes:
    volumes:
      - ./config.yml:/wiki/config.yml:rw
    restart: unless-stopped
    ports:
      - "8080:3000"

volumes:
  db-data:

```


Make sure you have the config.yml locally where you run docker-compose.

config.yml
```
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: $(DB_HOST)
  port: $(DB_PORT)
  user: $(DB_USER)
  pass: $(DB_PASS)
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: $(SSL_ACTIVE)
  port: 3443
  provider: letsencrypt
  domain: $(LETSENCRYPT_DOMAIN)
  subscriberEmail: $(LETSENCRYPT_EMAIL)
logLevel: info
uploads:
  # Maximum upload size in bytes per file (default: 5242880 (5 MB))
  maxFileSize: 15242880
  # Maximum file uploads per request (default: 10)
  maxFiles: 10

```
