### ISSUE TITLE
Not syncing automatically to GitHub with ssh

### ISSUE THREAD

**Issue by wmayner** [Requarks/wiki#1110]
**Question**
The repo is not syncing automatically with GitHub. I believe I've configured `ssh` correctly in the `config.yml` file, since I can push directly from the command line (without being prompted for a password) without issue.

I'm deploying with `docker-compose` (file below).

I've reviewed similar issues but they don't seem to apply to my case (I'm using v1, rather than the v2 beta).

**config.yml**:
```
title: IIT
host: 'http://localhost:3000'
port: 3000
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: en
langRtl: false
public: true
auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: true
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: true
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: SLACK_CLIENT_ID
    clientSecret: SLACK_CLIENT_SECRET
  ldap:
    enabled: false
    url: 'ldap://serverhost:389'
    bindDn: cn='root'
    bindCredentials: BIND_PASSWORD
    searchBase: 'o=users,o=example.com'
    searchFilter: '(uid={{username}})'
    tlsEnabled: false
    tlsCertPath: 'C:\example\root_ca_cert.crt'
  azure:
    enabled: false
    clientId: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: 00000002-0000-0000-c000-000000000000
    tenant: YOUR_TENANT.onmicrosoft.com
  oauth2:
    enabled: false
    clientId: OAUTH2_CLIENT_ID
    clientSecret: OAUTH2_CLIENT_SECRET
    authorizationURL: OAUTH2_AUTH_URL
    tokenURL: OAUTH2_TOKEN_URL
  oidc:
    enabled: false
    clientId: OPENID_CONNECT_CLIENT_ID
    clientSecret: OPENID_CONNECT_CLIENT_SECRET
    issuer: OPENID_CONNECT_ISSUER
    userInfoUrl: OPENID_CONNECT_USER_INFO_URL
    authorizationURL: OPENID_CONNECT_AUTHORIZATION_URL
    tokenURL: OPENID_CONNECT_TOKEN_URL
    emailClaim: OPENID_CONNECT_EMAIL_CLAIM_PATH
    usernameClaim: OPENID_CONNECT_USERNAME_CLAIM_PATH
sessionSecret: 2adcecc0911425cb0fddb1fd91695eef7af1ab7fbce542dc503eccc9f537ae84
db: 'mongodb://wikidb:27017/wiki'
git:
  url: git@github.com:wmayner/wiki.js-test.git
  branch: master
  auth:
    # Type: basic or ssh
    type: ssh
    # Only for SSH authentication:
    privateKey: /etc/wiki/keys/wiki.js_rsa
    sslVerify: true
    signature:
      name: Will Mayner
      email: wmayner@gmail.com
  # Default email to use as commit author
  serverEmail: wmayner@gmail.com
  # Whether to use user email as author in commits
  showUserEmail: true
features:
  linebreaks: true
  mathjax: false
externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false
theme:
  primary: indigo
  alt: blue-grey
  viewSource: all
  footer: blue-grey
  code:
    dark: true
    colorize: true
```

**docker-compose.yml**:
```
version: '3.7'
services:
  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '3000:3000'
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
      - ./wiki.js_rsa:/etc/wiki/keys/wiki.js_rsa
      - ./repo:/var/wiki/repo
```

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: 1.0.117
Database engine: Mongodb v3.6.14
