### ISSUE TITLE
Default Authentication strategy on Login page

### ISSUE THREAD

**Issue by seafre** [Requarks/wiki#1214]
**Describe the bug**
"...the default Local strategy cannot be disabled as it is required for root administrator login" which results in a non-intuitive user experience at login.

Administrator should be able to select the "Primary/Default Authentication strategy".

**To Reproduce**
1. Configure new Auth strategy
2. Login page

**Expected behavior**
The username/password prompt should be replaced with, as an example, "Sign in with   [GitHub Enterprise]" as the main login item.

This decreases the user's likelihood they attempt to use another user/password to gain access, and the Local is shown only under "or login using..." because this is  always required.

**Screenshots**
![image](https://user-images.githubusercontent.com/1815807/68847103-feb7be00-06c5-11ea-9b36-c13586617648.png)

**Comment by githubdave2020** [comment]
I had to walk nearly every user through this same situation. It should be prioritized!

**Comment by signalkraft** [comment]
In my case I wanted users to always pick Keycloak and I wanted to avoid showing the regular login form altogether. Accomplished this with a simple rewrite rule from `/login` to `/login/keycloak` (in our case in Helm on Kubernetes):

```yaml
[...]
      - ingress:
          tls: true
          annotations:
            nginx.ingress.kubernetes.io/configuration-snippet: |
              rewrite ^/login$ https://{{ requiredEnv "HOSTNAME" }}/login/keycloak redirect;
```
Works like a charm, users don't even see the login screen anymore. Obviously give your SSO user admin access first, you won't be able to use local sign in anymore.

Hope this helps somebody in the meantime.
