### ISSUE TITLE
UX/UI: make Table of contents column fixed

### ISSUE THREAD

**Issue by carloposo** [Requarks/wiki#1230]
### Actual behavior
Table of contents scrolls with content

### Expected behavior
Table of contents should stay always visible. In long entries, it's time consuming to go back to top of page to select another Chapter.

**Comment by UnlimitedCookies** [comment]
This should be optional.

**Comment by takashi1kun** [comment]
I think this would be accomplished by simply adding this class to the element:
```css
.stickyToc {
    position: sticky;
    top: 120px;
    z-index: 2;
}
```
