### ISSUE TITLE
setup not working, windows, from zip

### ISSUE THREAD

**Issue by AaronNGray** [Requarks/wiki#1249]
**Describe the bug**
Setup on Windows is not working. Getting a blank window on http://localhost:3000.
F12 reveals a <head> with content and a body with <div id="root"><setup wiki-version="2.0.0-beta"></setup></div>

**To Reproduce**
    
    wget https://github.com/Requarks/wiki/releases/download/2.0.1/wiki-js-windows.tar.gz

-- unzip --
-- setup PostgreSQL
```
create database wikijs;
create user wikijs with encrypted password 'xxxxxxxx';
grant all privileges on database wikijs to wikijs;
```
-- edit config.yaml --

C:\Users\aaron\Test\wiki-js-2>node server
Loading configuration from C:\Users\aaron\Test\wiki-js-2\config.yml... OK
2019-11-22T01:36:25.437Z [MASTER] info: =======================================
2019-11-22T01:36:25.441Z [MASTER] info: = Wiki.js 2.0.1 =======================
2019-11-22T01:36:25.443Z [MASTER] info: =======================================
2019-11-22T01:36:25.444Z [MASTER] info: Initializing...
2019-11-22T01:36:27.204Z [MASTER] info: Connecting to database...
2019-11-22T01:36:27.354Z [MASTER] info: Database Connection Successful [ OK ]
2019-11-22T01:36:27.421Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-11-22T01:36:27.422Z [MASTER] info: Starting setup wizard...
2019-11-22T01:36:28.425Z [MASTER] info: Starting HTTP server on port 3000...
2019-11-22T01:36:28.428Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-11-22T01:36:28.443Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-11-22T01:36:28.445Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2019-11-22T01:36:28.447Z [MASTER] info:
2019-11-22T01:36:28.449Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2019-11-22T01:36:28.452Z [MASTER] info:
2019-11-22T01:36:28.455Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺

**Expected behavior**
setup should appear not a blank window

**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
Windows 10
 - Wiki.js version: [e.g. 2.0.0-beta.115]
2.0.1
 - Database engine: [e.g. postgres 9.7, mysql 5.7]
PostgreSQL 12.0
**Additional context**
```
C:\Users\aaron\Test\wiki-js-2>dir
 Volume in drive C has no label.
 Volume Serial Number is D470-3FC2

 Directory of C:\Users\aaron\Test\wiki-js-2

22/11/2019  01:32    <DIR>          .
22/11/2019  01:32    <DIR>          ..
22/11/2019  01:19    <DIR>          assets
18/11/2019  01:05             4,021 config.sample.yml
18/11/2019  00:54            35,181 LICENSE
22/11/2019  01:32    <DIR>          node_modules
18/11/2019  00:54            11,125 package.json
22/11/2019  01:32    <DIR>          server
               3 File(s)         50,327 bytes
               5 Dir(s)  223,255,322,624 bytes free
```
config.yml
```
#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full documentation + examples:
# https://docs.requarks.io/install

# ---------------------------------------------------------------------
# Port the server should listen to
# ---------------------------------------------------------------------

port: 3000

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Supported Database Engines:
# - postgres = PostgreSQL 9.5 or later
# - mysql = MySQL 8.0 or later (5.7.8 partially supported, refer to docs)
# - mariadb = MariaDB 10.2.7 or later
# - mssql = MS SQL Server 2012 or later
# - sqlite = SQLite 3.9 or later

db:
  type: postgres
  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: localhost
  port: 5432
  user: wikijs
  pass: reallynicepassphrase
  db: wikijs
  ssl: false
  # SQLite only:
  storage: path/to/database.sqlite

#######################################################################
# ADVANCED OPTIONS                                                    #
#######################################################################
# Do not change unless you know what you are doing!

# ---------------------------------------------------------------------
# SSL/TLS Settings
# ---------------------------------------------------------------------
# Consider using a reverse proxy (e.g. nginx) if you require more
# advanced options than those provided below.

ssl:
  enabled: false

  # Certificate format, either 'pem' or 'pfx':
  format: pem
  # Using PEM format:
  key: path/to/key.pem
  cert: path/to/cert.pem
  # Using PFX format:
  pfx: path/to/cert.pfx
  # Passphrase when using encrypted PEM / PFX keys (default: null):
  passphrase: null
  # Diffie Hellman parameters, with key length being greater or equal
  # to 1024 bits (default: null):
  dhparam: null

  # Listen on this HTTP port and redirect all requests to HTTPS.
  # Set to false to disable (default: 80):
  redirectNonSSLPort: 80

# ---------------------------------------------------------------------
# Database Pool Options
# ---------------------------------------------------------------------
# Refer to https://github.com/vincit/tarn.js for all possible options

pool:
  # min: 2
  # max: 10

# ---------------------------------------------------------------------
# IP address the server should listen to
# ---------------------------------------------------------------------
# Leave 0.0.0.0 for all interfaces

bindIP: 0.0.0.0

# ---------------------------------------------------------------------
# Log Level
# ---------------------------------------------------------------------
# Possible values: error, warn, info (default), verbose, debug, silly

logLevel: info

# ---------------------------------------------------------------------
# Upload Limits
# ---------------------------------------------------------------------
# If you're using a reverse-proxy in front of Wiki.js, you must also
# change your proxy upload limits!

uploads:
  # Maximum upload size in bytes per file (default: 5242880 (5 MB))
  maxFileSize: 5242880
  # Maximum file uploads per request (default: 20)
  maxFiles: 10

# ---------------------------------------------------------------------
# Offline Mode
# ---------------------------------------------------------------------
# If your server cannot access the internet. Set to true and manually
# download the offline files for sideloading.

offline: false

# ---------------------------------------------------------------------
# Data Path
# ---------------------------------------------------------------------
# Writeable data path for Wiki.js, mainly for cache and user uploads.
dataPath: ./data
```
