### ISSUE TITLE
How to use Local Storage for backup

### ISSUE THREAD

**Issue by Schnuecks** [Requarks/wiki#1288]
Hello,

how could i use the local storage for backup?
i ran the docker-compose.yml from docs.

how do i need to modify the docker-compose.yml to set a volume or path so wikijs could backup in it and copy to the host.

OS: CentOS 7, docker-compose
Wiki.js version:  2.0.12
Database engine: postgres 9

**Comment by NGPixel** [comment]
You would need to mount a folder, e.g.:

```yaml
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - /host/backup/path:/backups

volumes:
  db-data:
```

Then specify `/backups` at the path in Wiki.js admin
