### ISSUE TITLE
Wiki is ignoring git ssh auth

### ISSUE THREAD

**Issue by nullpixel1** [Requarks/wiki#13]
**Logs:**

`
0|wiki     | { code: 128,
0|wiki     |   message: '`git --git-dir=repo/.git --work-tree=repo push origin master` failed with code 128',
0|wiki     |   stderr: 'fatal: could not read Username for \'https://github.com\': No such device or address\n',
0|wiki     |   stdout: '' }`

**Config:**

```yaml
git:
  url: git@github.com:WumpusPrime/wiki.git
  branch: master
  auth:

    # Type: basic or ssh
    type: ssh

    # Only for Basic authentication:
    username: // DiscordWiki
    password: // yayayaa

    # Only for SSH authentication:
    privateKey: /home/wiki/.ssh/id_rsa
```
