### ISSUE TITLE
Error while fetching page. Duplicate entry detected. Reload the page to try again.

### ISSUE THREAD

**Issue by athenawisdoms** [Requarks/wiki#1367]
**Describe the bug**
After installing Wiki.js using the [provided docker-compose.yml](https://docs.requarks.io/install/docker), logging in and creating the first Home post, we are faced with the page that says

> Error while fetching page. Duplicate entry detected. Reload the page to try again.

![image](https://user-images.githubusercontent.com/6615285/72224427-8ac05780-3548-11ea-8f25-48d98d3d43ef.png)

**To Reproduce**
1. Create a `docker-compose.yml` file using [the contents provided here](https://docs.requarks.io/install/docker).
2. `docker-compose up -d`
3. Visit *localhost:3000*, fill up the form and click the *Install* button
4. Redirected to the login screen. Enter credentials and log in.
![image](https://user-images.githubusercontent.com/6615285/72224503-4f725880-3549-11ea-9a9c-d8a889b55b74.png)
5. Arrived at welcome screen. Click on *Create Homepage* button
![image](https://user-images.githubusercontent.com/6615285/72224532-8e081300-3549-11ea-8c1f-1a6642dd7dfc.png)
6. Click on *Markdown* icon button
![image](https://user-images.githubusercontent.com/6615285/72224548-ac6e0e80-3549-11ea-9d4a-6961726bca61.png)
7. Click on the *OK* button
![image](https://user-images.githubusercontent.com/6615285/72224557-c27bcf00-3549-11ea-8efe-d73fed1863dd.png)
Modal is automatically closed
![image](https://user-images.githubusercontent.com/6615285/72224567-d6273580-3549-11ea-9230-eb2ae11104b8.png)
8. Click on the *Create* button.
9. We now get the error page
![image](https://user-images.githubusercontent.com/6615285/72224579-02db4d00-354a-11ea-80b4-f869d2335ce3.png)
10. Refreshing the page brings us back to the same error page 

**Expected behavior**
On clicking the *Create* button in Step 8 above, it should show us the created page (I think, have not used Wiki.js before).

**Screenshots**
See above

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.0.12
 - Database engine: Postgres 11-alpine

**Additional context**
Rebuild the docker 5X, encountered the same error.

**docker-compose.yml**

Obtained from [official docs](https://wiki.dannychua.io/en/home).

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
```
