### ISSUE TITLE
Docker with sqlite

### ISSUE THREAD

**Issue by karandashek** [Requarks/wiki#1399]
**Question**
Hi!
I'm trying to build wiki.js local copy via docker and sqlite, but i can't find correct way to configure sqlite file inside container.

i'm using this to build wiki
```yml
version: "3.7"
services:
  wiki:
    image: requarks/wiki:2
    environment:
        DB_TYPE: sqlite
    restart: unless-stopped
    ports:
      - "80:3000"
```

and it seems wiki js works correctly. 
As i understood requarks/wiki:2 image already has installed sqlite inside and generates db file (i can create/save pages), but i'm not sure what file is db, is it "undefined" file? And if it is, hope i can rename it to something like db.db and use this custom name by env var DB_FILEPATH=/wiki/db.db to sync db outside container?

Thanks!

**Host Info (please complete the following information):**
OS: [Docker]
Wiki.js version: [e.g. 2.0.12]
Database engine: [sqlite]
