### ISSUE TITLE
container - HTTPS runs on what should be the HTTP port

### ISSUE THREAD

**Issue by pavemina** [Requarks/wiki#1422]
**Describe the bug**
When configuring the docker container to run with HTTPS enabled and a custom certificate, it ends up running with HTTPS on what should be the HTTP port.

**To Reproduce**
sample docker-compose.yml used:
```
version: "3"

services:

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - macvlan_wiki

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    networks:
      - macvlan_wiki
    volumes:
     - /path/to/config.yml:/wiki/config.yml
     - /path/to/certificate.pfx:/wiki/cert.pfx

volumes:
  db-data:

networks:
  macvlan_wiki:
    external: true

```
This is mostly "vanilla" compose file, except the macvlan network and volume-binding of config and certificate file.

sample config.yml used (most of this is the default, so I will only show the changes):
```
port: 5000
[...]
db:
  type: postgres

  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: db
[...]
ssl:
  enabled: true
  port: 5443
  provider: custom
  format: pfx
  pfx: /wiki/cert.pfx
  passphrase: <cert-file-passphrase>
  dhparam: null
[...]
```

Reproduction steps
1. docker-compose up -d

2. Observe the wiki container logs, notice the line claiming that HTTPS is running on the HTTP port
```
2020-01-30T20:23:29.837Z [MASTER] info: Starting setup wizard...
2020-01-30T20:23:29.949Z [MASTER] info: Starting HTTP server on port 5000...
2020-01-30T20:23:29.949Z [MASTER] info: HTTPS Server on port: [ 5000 ] ##<=== why is this identical to HTTP?
2020-01-30T20:23:29.965Z [MASTER] info: HTTP Server: [ RUNNING ]
2020-01-30T20:23:29.965Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2020-01-30T20:23:29.965Z [MASTER] info:
2020-01-30T20:23:29.965Z [MASTER] info: Browse to http://localhost:5000/ to complete setup!
2020-01-30T20:23:29.965Z [MASTER] info:
2020-01-30T20:23:29.965Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺

```
3. Verify access:
http://wiki-ip:5000 => TCP session established, but empty response to the HTTP GET request
https://wiki-ip:5000 => opens OK over HTTPS
http://wiki-ip:5443 => server sends an RST packet to our SYN

**Expected behavior**
HTTP should run on port defined by "port", HTTPS should run on port defined by "ssl/port".

**Screenshots**
[screenshot demonstrating the end result in Chrome](https://i.imgur.com/bvL5EIc.png)

**Host Info (please complete the following information):**
 - Arch linux, kernel  5.4.15-arch1-1
- Docker version 19.03.5-ce, build 633a0ea838
 - Wiki.js version 2.0.12

I hope I haven't missed anything obvious?
I know barely anything about node and javascript, but looking at server/setup.js, it seems to me like HTTPS just re-uses the same port when starting up?:
```WIKI.logger.info(`HTTPS Server on port: [ ${WIKI.config.port} ]`)```
