### ISSUE TITLE
color theme settings are not persistent

### ISSUE THREAD

**Issue by bitworm** [Requarks/wiki#162]
theme settings return to default after restarting the wiki.  I assume this is not intended behavior.

**Comment by NGPixel** [comment]
Yes, this is a known issue. I had to release Beta 13 quickly to fix the major bug in Beta 12, so the settings persist function didn't make it's way into that release.

In the meantime, you can set the color settings permanently in the config.yml:

```yaml
# ---------------------------------------------------------------------
# Color Theme
# ---------------------------------------------------------------------

theme:
  primary: indigo
  alt: blue-grey
  footer: blue-grey
  code:
    dark: true
    colorize: true
```

**Comment by bitworm** [comment]
No problem, just wanted to raise the problem.  I can mark this as closed if you wish.

**Comment by choicky** [comment]
@NGPixel @bitworm 
I installed beta 13 last night (because of failed upgrading).  

I found my `config.yml` has included the follwing settings:

```yml
theme:
  primary: indigo
  alt: blue-grey
  footer: blue-grey
  code:
    dark: true
    colorize: true
```
