### ISSUE TITLE
Changes for media upload limits in config.yml are in effect, but not reflected on UI level

### ISSUE THREAD

**Issue by eehrhardt** [Requarks/wiki#1721]
Changes for media upload limits in config.yml are in effect, but not reflected on UI level.
![media_upload](https://user-images.githubusercontent.com/1568882/79253475-8d9e5180-7e83-11ea-8a71-65a17e8cb003.JPG)

The values are hardcoded in file `client/components/editor/editor-modal-media.vue on line 153`.

Great project btw =)

**Comment by sbonaime** [comment]
And also in 
server/middlewares/upload.js

**Comment by eehrhardt** [comment]
> 
> 
> And also in
> server/middlewares/upload.js

Good catch.

Both should reference the values in `config.yml` as defined in `config.sample.yml`
```yaml
uploads:
  # Maximum upload size in bytes per file (default: 5242880 (5 MB))
  maxFileSize: 5242880
  # Maximum file uploads per request (default: 10)
  maxFiles: 10
```
