### ISSUE TITLE
Increase the Upload Size on my Digital Ocean Droplet

### ISSUE THREAD

**Issue by mattlundstrom** [Requarks/wiki#1791]
**Question**
I'm trying to increase the upload size on my Digital Ocean Droplet. 

I have no Node.js or Docker experience. All I have is SSH, SFTP, and the sample config.yml file. Can someone please guide me on how to do this? 

**Host Info (please complete the following information):**
OS: Docker Container
Wiki.js version: 2.3.77
Database engine:  postgres 11.7

**Comment by Smankusors** [comment]
You can follow [this guide](https://docs.requarks.io/install/config#upload-limits)

**Comment by mattlundstrom** [comment]
Thanks, but where do I put the config.yml it in the Digital Ocean Droplet?

**Comment by mattlundstrom** [comment]
Resolved by doing the following:

- Copy current config from Docker container to host:
`docker cp wiki:/wiki/config.yml /config.yml`

- Open config.yml and add custom lines for:
```
uploads:
  # Maximum upload size in bytes per file (default: 5242880 (5 MB))
  maxFileSize: 5242880
  # Maximum file uploads per request (default: 10)
  maxFiles: 10
```

- Copy config from host back to Docker container:
`docker cp /config.yml wiki:/wiki/config.yml`

- Restart Wiki JS
`docker restart wiki`

UI Does not update, but functionality is there.
