### ISSUE TITLE
Comment section can't be disabled in canary.

### ISSUE THREAD

**Issue by toonsevrin** [Requarks/wiki#1942]
You're probably still working on this but for anyone that wishes to disable the upcoming comments feature, you can just add the following to your css code-injection (in theme settings):
```css
.comments-container {
  display: none
}
```
Please update and close this issue once the comments disabling flag is working and we no longer have to use css.
