### ISSUE TITLE
DB Configuration is empty or incomplete. Switching to Setup mode...

### ISSUE THREAD

**Issue by snoop2head** [Requarks/wiki#2003]
## **Describe the bug**
* When accessed to http://localhost:3000/ the message "This site can’t be reached" error appears
* Error messages are following:
> wiki_1  | 2020-06-06T10:52:03.303Z [MASTER] error: Database Connection Error: ECONNREFUSED 172.22.0.2:5432
> wiki_1  | 2020-06-06T10:52:06.487Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...

##  **To Reproduce**
* Using docker-compose, following instructions for documentations described in https://docs.requarks.io/install/docker
* Local device is running on Mac OS, opened the page with Google Chrome Browser.

1. Follow instructions on https://docs.requarks.io/install/docker
2. On local device, make docker-compose.yml file on folder, as
``` yml
version: "3"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
```
3. On that directory, run the following
> docker-compose up --build
4. See the error of the following
```
Status: Downloaded newer image for requarks/wiki:2
Creating wiki-js-docker-demo_db_1 ... done
Creating wiki-js-docker-demo_wiki_1 ... done
Attaching to wiki-js-docker-demo_db_1, wiki-js-docker-demo_wiki_1
db_1    | WARNING: no logs are available with the 'none' log driver
wiki_1  | Loading configuration from /wiki/config.yml... OK
wiki_1  | 2020-06-06T10:52:03.061Z [MASTER] info: =======================================
wiki_1  | 2020-06-06T10:52:03.063Z [MASTER] info: = Wiki.js 2.4.105 =====================
wiki_1  | 2020-06-06T10:52:03.063Z [MASTER] info: =======================================
wiki_1  | 2020-06-06T10:52:03.063Z [MASTER] info: Initializing...
wiki_1  | 2020-06-06T10:52:03.292Z [MASTER] info: Using database driver pg for postgres [ OK ]
wiki_1  | 2020-06-06T10:52:03.296Z [MASTER] info: Connecting to database...
wiki_1  | 2020-06-06T10:52:03.303Z [MASTER] error: Database Connection Error: ECONNREFUSED 172.22.0.2:5432
wiki_1  | 2020-06-06T10:52:03.303Z [MASTER] warn: Will retry in 3 seconds... [Attempt 1 of 10]
wiki_1  | 2020-06-06T10:52:06.310Z [MASTER] info: Connecting to database...
wiki_1  | 2020-06-06T10:52:06.326Z [MASTER] info: Database Connection Successful [ OK ]
wiki_1  | 2020-06-06T10:52:06.487Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
wiki_1  | 2020-06-06T10:52:06.487Z [MASTER] info: Starting setup wizard...
wiki_1  | 2020-06-06T10:52:06.574Z [MASTER] info: Starting HTTP server on port 3000...
wiki_1  | 2020-06-06T10:52:06.574Z [MASTER] info: HTTP Server on port: [ 3000 ]
wiki_1  | 2020-06-06T10:52:06.577Z [MASTER] info: HTTP Server: [ RUNNING ]
wiki_1  | 2020-06-06T10:52:06.577Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
wiki_1  | 2020-06-06T10:52:06.577Z [MASTER] info: 
wiki_1  | 2020-06-06T10:52:06.577Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
wiki_1  | 2020-06-06T10:52:06.577Z [MASTER] info: 
wiki_1  | 2020-06-06T10:52:06.577Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
```

##  **Expected behavior**
* When accessed to http://localhost:3000/ the message "This site can’t be reached" error appears
* Error messages are following:
> wiki_1  | 2020-06-06T10:52:03.303Z [MASTER] error: Database Connection Error: ECONNREFUSED 172.22.0.2:5432
> wiki_1  | 2020-06-06T10:52:06.487Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...

##  **Host Info (please complete the following information):**
 - OS: Docker Virtual Machine running on Mac OS (10.15.5)
 - Docker image: requarks/wiki:2
 - Database engine: postgres:11-alpine
