### ISSUE TITLE
Error: Error: Failed HTTP-01 Pre-Flight / Dry Run. 

### ISSUE THREAD

**Issue by Milan991** [Requarks/wiki#2019]
**Question**
The final step of WikiJS installation is returning the following error. Letsencrypt certificate is issued using the plugin in Plesk dashboard. 

```
wiki_1  | 2020-06-08T14:52:04.588Z [MASTER] info: (LETSENCRYPT) Removing HTTP challenge: [ OK ]
wiki_1  | 2020-06-08T14:52:04.589Z [MASTER] info: (LETSENCRYPT) Removing HTTP challenge: [ OK ]
wiki_1  | 2020-06-08T14:52:04.589Z [MASTER] warn: (LETSENCRYPT) Error: Error: Failed HTTP-01 Pre-Flight / Dry Run.
wiki_1  | curl 'http://my.wiki.page/.well-known/acme-challenge/test-23abd43ecb04a894132a777e9ee01cee-0'
wiki_1  | Expected: 'test-23abd43ecb04a894132a777e9ee01cee-0.ceBngDiRHsG1hxbHH5_GM2IkINOMOOjSGQOUPPTdmjo'
wiki_1  | Got: '<html>
wiki_1  | <head><title>404 Not Found</title></head>
wiki_1  | <body>
wiki_1  | <center><h1>404 Not Found</h1></center>
wiki_1  | <hr><center>nginx</center>
wiki_1  | </body>
wiki_1  | </html>
wiki_1  | '
wiki_1  | See https://git.rootprojects.org/root/acme.js/issues/4
wiki_1  | 2020-06-08T14:52:04.590Z [MASTER] error: Error: Failed HTTP-01 Pre-Flight / Dry Run.
wiki_1  | curl 'http://my.wiki.page/.well-known/acme-challenge/test-23abd43ecb04a894132a777e9ee01cee-0'
wiki_1  | Expected: 'test-23abd43ecb04a894132a777e9ee01cee-0.ceBngDiRHsG1hxbHH5_GM2IkINOMOOjSGQOUPPTdmjo'
wiki_1  | Got: '<html>
wiki_1  | <head><title>404 Not Found</title></head>
wiki_1  | <body>
wiki_1  | <center><h1>404 Not Found</h1></center>
wiki_1  | <hr><center>nginx</center>
wiki_1  | </body>
wiki_1  | </html>
wiki_1  | '
wiki_1  | See https://git.rootprojects.org/root/acme.js/issues/4

```

It looks like some step in Plesk certification is missing. Can anyone help me with this issue?

**Host Info (please complete the following information):**
OS: Linux xeon132 4.15.0-101-generic
Wiki.js version: 2.4.105
Database engine: postgres 11.0

**Comment by NGPixel** [comment]
If Plesk is already handling the certificate, why are you requesting one from Wiki.js as well? Use one or the other, not both. Plesk should be handling the SSL termination.

**Comment by Milan991** [comment]
@NGPixel If Plesk is handling the certificate, how should I change my current Docker compose file in order to let only Plesk handle the certification? My Docker compose file is shown below:

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password!
      POSTGRES_USER: postgres
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password!
      DB_NAME: postgres
      SSL_ACTIVE: 1
      LETSENCRYPT_DOMAIN: my.wiki.page
      LETSENCRYPT_EMAIL: milan@wiki.com


    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3443:3443"

volumes:
  db-data:
```
