### ISSUE TITLE
Error when using docker

### ISSUE THREAD

**Issue by ChristianAEDev** [Requarks/wiki#204]
First of all: Thank you for providing a way to deploy to Docker!!!

### Actual behavior
When trying to deploy wiki.js using Docker I get the following error:
```
wikijs_1          | { Error: EISDIR: illegal operation on a directory, read
wikijs_1          |     at Object.fs.readSync (fs.js:681:18)
wikijs_1          |     at tryReadSync (fs.js:542:20)
wikijs_1          |     at Object.fs.readFileSync (fs.js:585:19)
wikijs_1          |     at module.exports (/var/wiki/server/libs/config.js:28:12)
wikijs_1          |     at Object.<anonymous> (/var/wiki/server/index.js:23:39)
wikijs_1          |     at Module._compile (module.js:573:30)
wikijs_1          |     at Object.Module._extensions..js (module.js:584:10)
wikijs_1          |     at Module.load (module.js:507:32)
wikijs_1          |     at tryModuleLoad (module.js:470:12)
wikijs_1          |     at Function.Module._load (module.js:462:3) errno: -21, code: 'EISDIR', syscall: 'read' }
```

### Expected behavior
No error on start up using docker.

### Steps to reproduce the behavior
1. Create `docker-compose.yml`:
```
wikijs:
  image: "requarks/wiki:latest"
  restart: always
  links:
   - wikijs-mongodb
  ports:
   - "8033:80"
  environment:
   - WIKI_ADMIN_EMAIL=XXXXX@gmail.com
  volumes:
   - /mnt/data/programs/wikijs/config.yml:/var/wiki/config.yml

wikijs-mongodb:
  image: mongo
  container_name: "mongodb"
  restart: always
  volumes:
    - /mnt/data/programs/wikijs-mongodb/data/db:/data/db
```

2. Execute `docker-compose up`

Searching for the error I found [this](https://stackoverflow.com/a/25907463) stackoverflow article descriping that this error occurs when then code tries to open a file but the given path is a directory.
