### ISSUE TITLE
Allow user name config for default commit author

### ISSUE THREAD

**Issue by bcdxn** [Requarks/wiki#205]
### Actual behavior

Currently only the commit author email is configurable. The username is hardcoded to `Wiki` (As seen here: https://github.com/Requarks/wiki/blob/master/server/libs/git.js#L108).

**For Example (from the config.sample.yml)**

```yml
# ...
# ---------------------------------------------------------------------
# Git Connection Info
# ---------------------------------------------------------------------

git:
  url: https://github.com/Organization/Repo
  branch: master
  auth:
    
    # Type: basic or ssh
    type: ssh

    # Only for SSH authentication:
    privateKey: /etc/wiki/keys/git.pem

    sslVerify: true

  # Default email to use as commit author
  serverEmail: marty@example.com

  # Whether to use user email as author in commits
  showUserEmail: true
  
  signature:
    # Used as the commiter email
    email: 'marty@example.com'
    # This value is ignored when the repo is initialized
    user: 'Marty'
# ...
```

### Proposed behavior

Allow the default committer username to be configurable in the same way that the email is. The property could be named `serverUser` as shown below to follow the existing convention. We could also have the name be configurable via the signature block (also shown below).

**For Example**
```yml
# ...
# ---------------------------------------------------------------------
# Git Connection Info
# ---------------------------------------------------------------------

git:
  url: https://github.com/Organization/Repo
  branch: master
  auth:

    # Type: basic or ssh
    type: ssh

    # Only for SSH authentication:
    privateKey: /etc/wiki/keys/git.pem

    sslVerify: true

  # Default email to use as commit author
  serverEmail: marty@example.com
  # Default name to use as commit author (proposed syntax)
  serverUser: Marty

  # Whether to use user email as author in commits
  showUserEmail: true
  
  signature:
    # Used as the committer email
    email: 'marty@example.com'
    # Used as the committer name
    user: 'Marty'
# ...
```

Love the project and Thanks!
