### ISSUE TITLE
Authentication Not Working

### ISSUE THREAD

**Issue by alexculea** [Requarks/wiki#22]
Hi guys!

Your project looked very promising to me so I gave it a go. Unfortunately I wasn't able to do the first admin login. By submitting the login form, the request hangs. No response is written.

Here's what I see in the logs:

> pm2 logs wiki

```
/var/www/wikijs/logs/wiki-error-0.log last 15 lines:
0|wiki     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|wiki     | [object Object]
0|wiki     | Unhandled rejection (<{"message":"Cannot increment request c...>, no stack trace)
0|wiki     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|wiki     | [object Object]
0|wiki     | Unhandled rejection (<{"message":"Cannot increment request c...>, no stack trace)
0|wiki     | Unhandled rejection (<{"message":"Cannot increment request c...>, no stack trace)
0|wiki     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|wiki     | [object Object]
0|wiki     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|wiki     | [object Object]
```

### Config File
```
title: <removed>
host: https://<removed>

port: 2017

paths:
  repo: ./repo
  data: ./data

uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100

lang: en

public: false

auth:
  local:
    enabled: true
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: false
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET


sessionSecret: <removed>
admin: <removed>
db: mongodb://localhost:27017/wiki
git:
  url: <removed>
  branch: master
  auth:

    # Type: basic or ssh
    type: basic

    # Only for Basic authentication:
    username: <removed>
    password: <removed>

    # Only for SSH authentication:
    #privateKey: /etc/wiki/keys/git.pem

    sslVerify: true
  signature:
    name: <removed>
    email: <removed>
```
### Environment
> node -v
`v7.6.0`

> netstat -tulpn
`tcp        0      0 127.0.0.1:28017         0.0.0.0:*               LISTEN      17276/mongod`
`tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      17276/mongod`

> git --version
`git version 2.11.0`

> node wiki --version
`1.0.0-beta.8`

I'm sure this is not enough information for the issue to be found. But it's a start with I thought to include. I'm more than willing to provide anything you could need.

Thanks in advance.
