### ISSUE TITLE
User validation failed (in Docker container)

### ISSUE THREAD

**Issue by exos** [Requarks/wiki#239]
Using the official docker image, I can't login in with the default admin user, reading logs:

    Sep 18 18:16:12 ****** docker[13013]: 2017-09-18T21:16:12.302Z - info: [SERVER] [AUTH] Guest account created successfully!
    Sep 18 18:16:12 ****** docker[13013]: 2017-09-18T21:16:12.311Z - error: [SERVER] [AUTH] An error occured while creating root admin account:
    Sep 18 18:16:12 ****** docker[13013]: 2017-09-18T21:16:12.311Z - error: [SERVER]  ValidationError: User validation failed
    Sep 18 18:16:12 ****** docker[13013]: at ValidationError (/var/wiki/node_modules/mongoose/lib/error/validation.js:28:11)
    Sep 18 18:16:12 ****** docker[13013]: at model.Document.invalidate (/var/wiki/node_modules/mongoose/lib/document.js:1612:32)
    Sep 18 18:16:12 ****** docker[13013]: at /var/wiki/node_modules/mongoose/lib/document.js:1484:17
    Sep 18 18:16:12 ****** docker[13013]: at validate (/var/wiki/node_modules/mongoose/lib/schematype.js:760:7)
    Sep 18 18:16:12 ****** docker[13013]: at /var/wiki/node_modules/mongoose/lib/schematype.js:805:11
    Sep 18 18:16:12 ****** docker[13013]: at Array.forEach (<anonymous>)
    Sep 18 18:16:12 ****** docker[13013]: at SchemaString.SchemaType.doValidate (/var/wiki/node_modules/mongoose/lib/schematype.js:765:19)
    Sep 18 18:16:12 ****** docker[13013]: at /var/wiki/node_modules/mongoose/lib/document.js:1482:9
    Sep 18 18:16:12 ****** docker[13013]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
    Sep 18 18:16:12 ****** docker[13013]: at process._tickCallback (internal/process/next_tick.js:180:9)
    Sep 18 18:16:12 ****** docker[13013]: 2017-09-18T21:16:12.317Z - info: [AGENT] Running all jobs...

I start with:

    # /usr/bin/docker run --rm --name=kak-wiki \
        -v /srv/kak-wiki/wiki/config.yml:/var/wiki/config.yml \
        -v /srv/kak-wiki/wiki:/data \
        --link kak-mongo:mongo \
        -p 4577:3000 \
        requarks/wiki

And have in the config.yml:

```yaml
# ---------------------------------------------------------------------
# Site Authentication
# ---------------------------------------------------------------------

public: true 

auth:
  defaultReadAccess: false
  local:
    enabled: true
```

The docker image is latest (today), the image id is `a7ebcc57f341`.
