### ISSUE TITLE
Provide Dockerfile

### ISSUE THREAD

**Issue by martialblog** [Requarks/wiki#24]
Hi, 

would be nice if there was a Docker Container for wiki.js
I've forked the repository and I'll try to get a Container running.

Cheers

**Comment by NGPixel** [comment]
There was some work done already for a dockerfile. See https://github.com/Requarks/wiki-docker

It's not ready but most of it is done if you want to take a look.

**Comment by martialblog** [comment]
Thanks, I'll have a look.

**Comment by gravufo** [comment]
You should probably look into using docker-compose in order to have the DB separated from the frontend!

**Comment by Isotop7** [comment]
Just a headsup for everyone:

I'm using this dockerfile:

```
FROM node:7.5-wheezy

ENV DOWNLOAD_URL https://github.com/Requarks/wiki/releases/download/v1.0.0-beta.8/wiki-js.tar.gz

RUN \
	mkdir -p /var/www/wiki \
	&& mkdir -p /etc/wiki/keys \
	&& wget ${DOWNLOAD_URL} -O wiki-js.tar.gz \
	&& mv wiki-js.tar.gz /var/www/wiki \
	&& cd /var/www/wiki \
	&& tar xfz wiki-js.tar.gz \
	&& rm wiki-js.tar.gz \
	&& npm install --only=production && npm rebuild

COPY config.yml /var/www/wiki/config.yml

WORKDIR /var/www/wiki

EXPOSE 80
CMD ["node", "server.js"]
```

Right now I'm copying my config file when building a new image but in the future I'll be using a volume mount for this.

My docker-compose looks like this (I'm using rancher to manage my docker containers):

```
wiki-mongo:
  image: mongo
  stdin_open: true
  tty: true
  labels: 
    io.rancher.container.pull_image: always
  command: mongod --smallfiles --oplogSize 128
  volumes:
    - /local/dir/mongo:/data/db
wiki-js:
  image: <path/to/custom-image>
  stdin_open: true
  tty: true
  labels: 
    io.rancher.container.pull_image: always
  volumes:
    - /local/dir/wiki-js/data:/var/www/wiki/data
    - /local/dir/wiki-js/repo:/var/www/wiki/repo
    - /local/dir/wiki-js/keys:/etc/wiki/keys
  links:
    - wiki-mongo:mongo
  expose: 
    - "80"
```

In addition I'm using a load-balancer in front of wiki.js but you could easily expose to a host port.
