### ISSUE TITLE
docker-compose: config.yml file not mounting

### ISSUE THREAD

**Issue by samuele-artuso** [Requarks/wiki#242]
I'm trying to run wiki.js with docker-compose.

I have created a `config.yml` file in the same directory where my `docker-compose.yml` file is.

Upon running `docker-compose up` I get this error:

```
ERROR: for f2adea891bfc_wikijs_wikijs_1  Cannot start service wikijs: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/home/kyuzz/Projects/wiki.js/config.yml\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/31f21efbed605dfa8ca525bb35008986830950c86ef9f019117e57696500b17e\\\" at \\\"/var/lib/docker/aufs/mnt/31f21efbed605dfa8ca525bb35008986830950c86ef9f019117e57696500b17e/var/wiki/config.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

How can I fix this issue?

**Comment by samuele-artuso** [comment]
@NGPixel any clues?

**Comment by samuele-artuso** [comment]
```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87
$ docker-compose --version                
docker-compose version 1.16.1, build 6d1ac21
```

**Comment by NGPixel** [comment]
I was able to run docker-compose without any issues, so you must likely have a wrong path in your docker-compose.yml.

In my test, I used the following `docker-compose.yml`:
```yaml
version: '3'
services:
  wikidb:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --logpath=/dev/null'
    volumes:
      - /home/nick/test/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    ports:
      - '8000:3000'
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - /home/nick/test/config.yml:/var/wiki/config.yml
```

and for the `config.yml`, I simply copied the sample file and changed the `db` param to match the docker compose name:
```yaml
db: mongodb://wikidb:27017/wiki
```
