### ISSUE TITLE
Mongo issue with the docker-compose file

### ISSUE THREAD

**Issue by Nicolab** [Requarks/wiki#243]
Hello,

> first, thanks the author and contributors, I have been waiting for a long time for a good wiki!

I trying to install with docker-compose but I have an issue:

```
error: [AGENT] Failed to connect to MongoDB instance.
wikijs_1  | Unhandled rejection MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
wikijs_1  |     at Pool.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/topologies/server.js:336:35)
wikijs_1  |     at emitOne (events.js:115:13)
wikijs_1  |     at Pool.emit (events.js:210:7)
wikijs_1  |     at Connection.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/pool.js:280:12)
wikijs_1  |     at Object.onceWrapper (events.js:318:30)
wikijs_1  |     at emitTwo (events.js:125:13)
wikijs_1  |     at Connection.emit (events.js:213:7)
wikijs_1  |     at Socket.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/connection.js:187:49)
wikijs_1  |     at Object.onceWrapper (events.js:316:30)
wikijs_1  |     at emitOne (events.js:115:13)
wikijs_1  |     at Socket.emit (events.js:210:7)
wikijs_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
wikijs_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
wikijs_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)
```

docker-compose.yml
```yml
version: '3'
services:
  wikidb:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --logpath=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    ports:
      - '8088:3000'
    environment:
      WIKI_ADMIN_EMAIL: contact@me.local
    volumes:
      - ./config.yml:/var/wiki/config.yml
```

config.yml:

```yml
#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full explanation + examples in the documentation:
# https://docs.requarks.io/wiki/install

# ---------------------------------------------------------------------
# Title of this site
# ---------------------------------------------------------------------

title: Nico Wiki

# ---------------------------------------------------------------------
# Full public path to the site, without the trailing slash
# ---------------------------------------------------------------------
# INCLUDE CLIENT PORT IF NOT 80/443!

host: http://localhost:8088

# ---------------------------------------------------------------------
# Port the main server should listen to (80 by default)
# ---------------------------------------------------------------------
# To use process.env.PORT, comment the line below:

port: 8088

# ---------------------------------------------------------------------
# Data Directories
# ---------------------------------------------------------------------

paths:
  repo: ./repo
  data: ./data

# ---------------------------------------------------------------------
# Upload Limits
# ---------------------------------------------------------------------
# In megabytes (MB)

uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100

# ---------------------------------------------------------------------
# Site Language
# ---------------------------------------------------------------------
# Possible values: en, de, es, fa, fr, ko, nl, pt, ru, sr, tr or zh

lang: fr

# Enable for right to left languages (e.g. arabic):
langRtl: false

# ---------------------------------------------------------------------
# Site Authentication
# ---------------------------------------------------------------------

public: false

auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: false
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: SLACK_CLIENT_ID
    clientSecret: SLACK_CLIENT_SECRET
  ldap:
    enabled: false
    url: ldap://serverhost:389
    bindDn: cn='root'
    bindCredentials: BIND_PASSWORD
    searchBase: o=users,o=example.com
    searchFilter: (uid={{username}})
    tlsEnabled: false
    tlsCertPath: C:\example\root_ca_cert.crt
  azure:
    enabled: false
    clientId: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: '00000002-0000-0000-c000-000000000000'
    tenant: 'YOUR_TENANT.onmicrosoft.com'

# ---------------------------------------------------------------------
# Secret key to use when encrypting sessions
# ---------------------------------------------------------------------
# Use a long and unique random string (256-bit keys are perfect!)

sessionSecret: jhvfjhvjvebfcé7a2966_a820f8268àcedabc-81amcmc7b4221!49aafcef71hdkdhe0248507

# ---------------------------------------------------------------------
# Database Connection String
# ---------------------------------------------------------------------
# You can also use an ENV variable by using $ENV_VAR_NAME as the value

db: mongodb://localhost:27017/nicowiki

# ---------------------------------------------------------------------
# Git Connection Info
# ---------------------------------------------------------------------

git: false
  # url: https://github.com/Organization/Repo
  # branch: master
  # auth:
  #
  #   # Type: basic or ssh
  #   type: ssh
  #
  #   # Only for Basic authentication:
  #   username: marty
  #   password: MartyMcFly88
  #
  #   # Only for SSH authentication:
  #   privateKey: /etc/wiki/keys/git.pem
  #
  #   sslVerify: true
  #
  # # Default email to use as commit author
  # serverEmail: marty@example.com
  #
  # # Whether to use user email as author in commits
  # showUserEmail: true

# ---------------------------------------------------------------------
# Features
# ---------------------------------------------------------------------
# You can enable / disable specific features below

features:
  linebreaks: true
  mathjax: true

# ---------------------------------------------------------------------
# External Logging
# ---------------------------------------------------------------------

externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false

# ---------------------------------------------------------------------
# Color Theme
# ---------------------------------------------------------------------

theme:
  primary: indigo
  alt: blue-grey
  viewSource: all # all | write | false
  footer: blue-grey
  code:
    dark: true
    colorize: true

```

If someone has an idea?
