### ISSUE TITLE
How to disable animation?

### ISSUE THREAD

**Issue by darkblaze69** [Requarks/wiki#2434]
**Question**
How to disable all those gorgeous animations? It slows down the workflow (waiting for finishing that spectacular transition and sliding of all the elements when opening another page) and distracts from the main purpose of writing or reading articles.
There should be a way to disable it, just cannot figure out how to do this.

**Comment by NGPixel** [comment]
There's no animation when reading pages or when loading / saving pages in the editor. Which animations are you referring to precisely?

As for disabling all animations, follow this topic: https://requarks.canny.io/wiki/p/un-animate-user-interface

**Comment by shriker** [comment]
@darkblaze69, from what I can tell, there are things like fade in animations on the buttons for the editor view, and a lot of slide animations inside of the Administration Area. 

There aren't _many_ animations while viewing, but to make things seem snappier you can disable the ripple effect, as well as make animations stop interfering with pointer events.

Administration Area -> Theme -> CSS Override

```css
.v-ripple__container {
  display: none !important;
}
.v-list-item:not(.v-clickable),
.v-open-menu-container:not(.v-clickable),
.v-select-menu-container:not(.v-clickable),
.v-select-value.v-select-placeholder {
  pointer-events: all !important
}
```

Pasting that in will make your wiki's navigation feel quicker, but it won't do anything for the Admin or editing views.
