### ISSUE TITLE
Cannot read property 'index' of undefined on page save

### ISSUE THREAD

**Issue by wojciech-skowronek** [Requarks/wiki#2494]
**Describe the bug**
On save a page I'm getting following error: `Cannot read property 'index' of undefined`.

It happens for all saves, but page is saved successfully.

I also get information about conflicts. I'm 100% sure no one else has access to my wiki. I work on a single tab and no other session is active. I believe those two issues may be connected.

**To Reproduce**
1. Edit page.
2. Change one letter.
3. Click save button
4. Getting the error, although the change is saved.

**Expected behavior**
There should e no error.

Save request payload:
```
[{"operationName":null,"variables":{"id":68,"content":"<h1>Title</h1>\n\n<p>Some text here x</p>","description":"","editor":"code","locale":"pl","isPrivate":false,"isPublished":true,"path":"home","publishEndDate":"","publishStartDate":"","scriptCss":"","scriptJs":"","tags":[],"title":"Untitled Page"},"extensions":{},"query":"mutation ($id: Int!, $content: String, $description: String, $editor: String, $isPrivate: Boolean, $isPublished: Boolean, $locale: String, $path: String, $publishEndDate: Date, $publishStartDate: Date, $scriptCss: String, $scriptJs: String, $tags: [String], $title: String) {\n  pages {\n    update(id: $id, content: $content, description: $description, editor: $editor, isPrivate: $isPrivate, isPublished: $isPublished, locale: $locale, path: $path, publishEndDate: $publishEndDate, publishStartDate: $publishStartDate, scriptCss: $scriptCss, scriptJs: $scriptJs, tags: $tags, title: $title) {\n      responseResult {\n        succeeded\n        errorCode\n        slug\n        message\n        __typename\n      }\n      page {\n        updatedAt\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}]
```
Save request response:
```
[{"data":{"pages":{"update":{"responseResult":{"succeeded":false,"errorCode":1,"slug":"TypeError","message":"Cannot read property 'index' of undefined","__typename":"ResponseStatus"},"page":null,"__typename":"PageResponse"},"__typename":"PageMutation"}}}]
```

Conflict check payload:
```
[{"operationName":null,"variables":{"id":68,"checkoutDate":"2020-09-24T12:17:17.824Z"},"extensions":{},"query":"query ($id: Int!, $checkoutDate: Date!) {\n  pages {\n    checkConflicts(id: $id, checkoutDate: $checkoutDate)\n    __typename\n  }\n}\n"}]
```
Conflict check response:
```
[{"data":{"pages":{"checkConflicts":true,"__typename":"PageQuery"}}}]
```

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.144 - but also all previous
 - Database engine: Postgres 11

docker-compose.yml:

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER:
      DB_PASS: 
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "8060:3000"
    volumes:
      - wikijs-backup:/home/backup

volumes:
  db-data:
  wikijs-backup:
```
