### ISSUE TITLE
logLevel in config.yml has no effect

### ISSUE THREAD

**Issue by mbotmcc** [Requarks/wiki#2497]
Changing the **logLevel** from **info** to any of the other possible options (verbose, debug, silly etc) doesn't seem to have any effect. I get the same amount of logs and info with all options.

**Expected behavior**
Logging level should actually change

**Host Info (please complete the following information):**
 - docker image

image build using

```
FROM requarks/wiki:2.5.144

COPY --chown=node:node ./config/config.yml /wiki/config.yml
```

config.yml

```
port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: '$(DB_HOST)'
  port: $(DB_PORT)
  user: '$(DB_USER)'
  pass: '$(DB_PASS)'
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
ssl:
  enabled: false
  port: 3443
  provider: custom
  format: pem
  key: ...
  cert: ...

logLevel: debug
ha: $(HA_ACTIVE)
offline: false
```
