### ISSUE TITLE
Helm chart ingress documentation out of date with template

### ISSUE THREAD

**Issue by ChipWolf** [Requarks/wiki#2648]
The helm chart docs state to use `ingress.hostname` (i.e. `hostname: wiki.local`), however the ingress template and the values.yaml require this:
```yaml
  hosts:
    - host: wiki.local
      paths: ["/"]
```
