### ISSUE TITLE
Error uploading a file

### ISSUE THREAD

**Issue by dan-burt** [Requarks/wiki#2764]
**Question**
Deploying in a localhost Docker instance. Container is deployed. Initial setup completes. When creating first page, I try to upload and use an image. I get "An unexpected error occurred".

```
version: "3"
services:
  wiki:
    image: requarks/wiki:2
    environment:
      DB_TYPE: mysql
      DB_HOST: localserver.local
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: pass
      DB_NAME: database
      VIRTUAL_HOST: wiki.domain.com
      LETSENCRYPT_HOST: wiki.domain.com
      LETSENCRYPT_EMAIL: user@domain.com
    volumes:
      - ./data:/data
    restart: unless-stopped
    ports:
      - "3000:3000"

```

I had to enable the Local Storage option. I have tried putting values in the "Path" variable, including the above bind volume, none seem to work.

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: requarks/wiki:2
Database engine: mysql 5.7
