### ISSUE TITLE
Bad gateway - Nginx + Docker

### ISSUE THREAD

**Issue by oxodao** [Requarks/wiki#2770]
**Describe the bug**
I have a non-dockerized nginx that is acting as my reverse proxy with a SSL cert. I have a dockerized Wiki.js in a docker-compose file (Pretty much the same setup as what's in the doc).

Accessing Wiki.js from the ip+port is working.
Accessing Wiki.js from the domain name gives me a 502 - Bad Gateway after the long timeout (So it clearly detects that something is listening on the port).

My nginx config is working correctly with my projects or other softwares.

According to [issue 923](https://github.com/Requarks/wiki/issues/923) the problem could be the port but it doesn't seems so since I've tried running on port 300 (< 1024) and port 3000 (> 1024) with the same issue. I've tried both with and without SSL on my nginx server just in case this could interfere.

Here's my config:

**docker-compose.ym**
```
version: "3"
services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    volumes:
        - ./data/postgres:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    user: "${UID}:${GID}"  # Something something that allows port 300 to be used (Not needed for > 1024), even if those vars are empty for some reasons
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./data/config.yml:/wiki/config.yml
    ports:
        - "3000:3000"
```

**nginx**
```
server {
    listen      80;
    server_name subdomain.domain.tld;

    charset utf-8;
    client_max_body_size 10M;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }
}
```

**wiki.js**
```
bindIP: 0.0.0.0
port: 3000

db:
  type: postgres
  host: db
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki
  ssl: false
```

**Expected behavior**
Accessing the wiki should work even when behind nginx

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: 2.5.170
 - Database engine: postgres-11

**Additional context**
Never had any issue running any other software through nginx & my current config

Thanks!
