### ISSUE TITLE
Reduce vertical spacing in MD tables

### ISSUE THREAD

**Issue by stefaanMLB** [Requarks/wiki#2910]
Tables in markdown pages have a large vertical spacing that I would like to have reduced over my entire wiki.
Is there a smart way of doing that for the whole wiki at once ?
By the way, I love wikijs !

**Comment by stefaanMLB** [comment]
I tried to add this css in the Administration > Theme > code injection > Css Override
```css
.contents td {
  padding: 0
}
```
But it has no effect.

**Comment by fs86** [comment]
```css
.contents th, .contents td {
    padding: 3px !important;
}
```
