### ISSUE TITLE
Helm deployment with external Postgres server

### ISSUE THREAD

**Issue by amnk** [Requarks/wiki#2911]
**Describe the bug**
When deploying Helm chart with `postgresql.enabled: false`, setup fails with `Error: secret "wiki" not found`

**To Reproduce**
Deploy Helm chart with `postgresql.enabled: false`

**Expected behavior**
Wiki should be deployed

**Additional context**
I was able to finish deployment by adding another Helm template:
```
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "wiki.postgresql.secret" . }}
data:
  {{ template "wiki.postgresql.secretKey" . }}: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"
```

Is this something that really needs fixing, or I just didn't finish the setup properly?

**Comment by dpap-qs** [comment]
I just got the same problem.

**Comment by mnpenner** [comment]
+1. Let us change the db type too. Seems to work fine with MariaDB after I hacked `deployment.yaml` to look like:

```yaml
          env:
            - name: DB_TYPE
              value: mariadb
            - name: DB_HOST
              value: yyyyyyy
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "wikijs"
            - name: DB_USER
              value: "wikijs"
            - name: DB_PASS
              value: "xxxxxxx"
```
