### ISSUE TITLE
Custom CSS is injected before the theme's css

### ISSUE THREAD

**Issue by sk22** [Requarks/wiki#3091]
**Describe the bug**
In the theming code injection section, custom CSS is stated to be injected **after** the standard CSS. It is not, see https://github.com/Requarks/wiki/issues/1809.

**To Reproduce**

Try to override an existing CSS rule, e.g.

```css
.v-application .primary {
  background-color: var(--my-color) !important;
  border-color: var(--my-color) !important
}
```

The properties do not get overridden, as both the theme's CSS and the custom CSS have the same specificity, but the theme CSS gets preferred, because the custom CSS is actually loaded *before* instead of after the theme.

**Expected behavior**
The custom CSS should be loaded after the theme and all other stylesheets.

**Screenshots**
See the existing, closed issue https://github.com/Requarks/wiki/issues/1809

**Host Info (please complete the following information):**
 - OS: Debian 4.19.160-2
 - Wiki.js version: 2.5.170

**Comment by sk22** [comment]
I found two workarounds for this:

a) providing CSS with a higher specificity, e.g. be prepending `html`, `#root`, ...

```css
body .v-application .primary {
  background-color: var(--my-color) !important;
  border-color: var(--my-color) !important
}
```

b) writing the CSS into the HTML injection textbox:

```html
<style>
.v-application .primary {
  background-color: var(--my-color) !important;
  border-color: var(--my-color) !important
}
</style>
```

I prefer the first workaround, because Wiki.js can still handle the CSS the way it wants to.
