### ISSUE TITLE
Letsencrypt ACME fails when there is no DNS A-record, ACME fails. 

### ISSUE THREAD

**Issue by PaulKlumpp** [Requarks/wiki#3092]
**Describe the bug**
I set up Wiki-JS with docker. My virtual machine running the docker host is only reachable via IPv6. 
As Letsencrypt works with IPv6 and fully supports it, it shall be no problem. (https://letsencrypt.org/docs/ipv6-support/)

**To Reproduce**
Docker-Compose:

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
      SSL_ACTIVE: 1
      LETSENCRYPT_DOMAIN: wiki.myipv6aaaarecord.com
      LETSENCRYPT_EMAIL: admin@myipv6aaaarecord.com
    restart: unless-stopped
    ports:
      - "80:3000"
      - "443:3443"

volumes:
  db-data:

```
After starting per docker-compose up it shows:

```
wiki_1  | 2021-02-17T04:10:26.397Z [MASTER] info: HTTP Server: [ RUNNING ]
wiki_1  | 2021-02-17T04:10:26.949Z [MASTER] info: (LETSENCRYPT) Generating certificate signing request (CSR)...
wiki_1  | 2021-02-17T04:10:26.954Z [MASTER] info: (LETSENCRYPT) CSR generated successfully [ OK ]
wiki_1  | 2021-02-17T04:10:26.955Z [MASTER] info: (LETSENCRYPT) Requesting certificate from Let's Encrypt...
wiki_1  | 2021-02-17T04:10:26.957Z [MASTER] info: (LETSENCRYPT) Setting HTTP challenge for wiki.myipv6aaaarecord.com: [ READY ]
wiki_1  | 2021-02-17T04:10:26.958Z [MASTER] info: (LETSENCRYPT) Waiting for challenge to complete...
wiki_1  | 2021-02-17T04:10:31.961Z [MASTER] info: (LETSENCRYPT) Removing HTTP challenge: [ OK ]
wiki_1  | 2021-02-17T04:10:31.961Z [MASTER] info: (LETSENCRYPT) Removing HTTP challenge: [ OK ]
wiki_1  | 2021-02-17T04:10:31.962Z [MASTER] warn: (LETSENCRYPT) Error: getaddrinfo ENOTFOUND wiki.myipv6aaaarecord.com
wiki_1  | 2021-02-17T04:10:31.962Z [MASTER] error: getaddrinfo ENOTFOUND wiki.myipv6aaaarecord.com
``` 

1. Have only an AAAA-record to point to my host.
2. Star

**Expected behavior**

**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: [e.g. 2.0.1]
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**
