### ISSUE TITLE
Github Storage - Permission denied (publickey)

### ISSUE THREAD

**Issue by ikwtif** [Requarks/wiki#3227]
**See Edit below**
Seems to be a permission issue with the wikijs user

**Host Info:**
 - OS: Proxmox Virtual Environment 6.3-4 
 - LXC container with Docker version 20.10.5, build 55c4c88
 - Wiki.js version: 2.5.191
 - Database engine: PostgreSQL 11.11

**Issue**
I can't seem to be able to get Github Storage working. 
1. Created the Docker containers with the example docker-compose file from the wiki.js docs (see below, changed docker-compose to version "2", changed username and passwords)
2. Followed the Github setup from the docs and created the ssh key inside the wikijs_wiki_1 container
3. Added the pub key to my github repo and filled out the Git setup for wikijs

**Error Message**
```
Load key "/wiki/github.pem": Permission denied git@github.com: Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. error: Could not fetch origin
```

**Screenshots**
![image](https://user-images.githubusercontent.com/20071958/111378222-d406bc80-86a1-11eb-8bb1-5ebf45e27cd5.png)
![image](https://user-images.githubusercontent.com/20071958/111378569-48d9f680-86a2-11eb-9236-340b5807f42e.png)
![image](https://user-images.githubusercontent.com/20071958/111378642-64450180-86a2-11eb-8ddc-5d7c0a89dc35.png)
![image](https://user-images.githubusercontent.com/20071958/111378820-a66e4300-86a2-11eb-9efc-6731dcc912d4.png)

**Additional Info**
Not sure what additional info I can provide or how to properly debug this, so if I can do something let me know. While setting this up someone else on version 2.5.170 mentioned his Github storage wasn't working either for 10 days now. 

```
version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:
```
--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------
**Edit**
Seems to be a permission issue with the wikijs user.
I was looking around in the issues and found this [https://github.com/Requarks/wiki/issues/2560](url)
I tried this from the answer

1. Login Docker Container
2. Switch to the Git directory (for me it was cd /wiki/data/repo)
3. Create a file there and push it to the repo (to initialize everything)
   3.1 echo "testfile" > test
   3.2 git add test
   3.3 git commit -m "init"
   3.4 git push origin <branch> (the branch in my case was master)

I logged into the container as Root user and performed those commands, now the files appear in my github repository, but I'm getting a new error when trying to force sync trough wikijs
```
error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/wiki/data/repo/.git/refs/remotes/origin/master.lock': Permission denied error: could not remove reference refs/remotes/origin/master
```
Which from what I found might be because I used the user Root inside the docker container with the git command. So I removed the master file and I'm back to the first error I got. I logged into the container as the wikijs user and that gives the same error as wikijs (see screenshot). I also tried to just enter the private key as content in wikijs and then try a git push with the wikijs user inside the Docker Container, but that still gives me a permission error.

**Screenshots with root user commands**
Repo With Files
![image](https://user-images.githubusercontent.com/20071958/111381303-d2d78e80-86a5-11eb-88dd-1f1694126ea6.png)
Docker Container Commands
![image](https://user-images.githubusercontent.com/20071958/111381414-fac6f200-86a5-11eb-91a1-d4f9b727afd7.png)
**Screenshot wikijs user**
Docker Container Commands
![image](https://user-images.githubusercontent.com/20071958/111382885-cce2ad00-86a7-11eb-92be-7b04fa16ec33.png)
**Screenshot wikijs user with private key content added to wikijs**
![image](https://user-images.githubusercontent.com/20071958/111385700-7a0af480-86ab-11eb-874a-4e909b9fd058.png)
