### ISSUE TITLE
helm chart fails with authentication issue for user postgres

### ISSUE THREAD

**Issue by Freundschaft** [Requarks/wiki#3235]
It seems like theres an authentication issue with postgres on the chart found at https://github.com/Requarks/wiki/tree/dev/dev/helm#configuration

Can someone help out on this? I havent changed the values.yaml apart from ingress configuration (which works)

> 2021-03-18T10:52:53.420Z [MASTER] info: =======================================
> 2021-03-18T10:52:53.422Z [MASTER] info: = Wiki.js 2.5.191 =====================
> 2021-03-18T10:52:53.422Z [MASTER] info: =======================================
> 2021-03-18T10:52:53.422Z [MASTER] info: Initializing...
> 2021-03-18T10:52:53.986Z [MASTER] info: Using database driver pg for postgres [ OK ]
> 2021-03-18T10:52:53.990Z [MASTER] info: Connecting to database...
> 2021-03-18T10:52:54.003Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:52:54.004Z [MASTER] warn: Will retry in 3 seconds... [Attempt 1 of 10]
> 2021-03-18T10:52:57.007Z [MASTER] info: Connecting to database...
> 2021-03-18T10:52:57.011Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:52:57.011Z [MASTER] warn: Will retry in 3 seconds... [Attempt 2 of 10]
> 2021-03-18T10:53:00.014Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:00.018Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:53:00.018Z [MASTER] warn: Will retry in 3 seconds... [Attempt 3 of 10]
> 2021-03-18T10:53:03.019Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:03.024Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:53:03.024Z [MASTER] warn: Will retry in 3 seconds... [Attempt 4 of 10]
> 2021-03-18T10:53:06.028Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:06.032Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:53:06.032Z [MASTER] warn: Will retry in 3 seconds... [Attempt 5 of 10]
> 2021-03-18T10:53:09.034Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:09.038Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:53:09.038Z [MASTER] warn: Will retry in 3 seconds... [Attempt 6 of 10]
> 2021-03-18T10:53:12.039Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:12.043Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:53:12.044Z [MASTER] warn: Will retry in 3 seconds... [Attempt 7 of 10]
> 2021-03-18T10:53:15.047Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:15.052Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:53:15.052Z [MASTER] warn: Will retry in 3 seconds... [Attempt 8 of 10]
> 2021-03-18T10:53:18.056Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:18.059Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:53:18.060Z [MASTER] warn: Will retry in 3 seconds... [Attempt 9 of 10]
> 2021-03-18T10:53:21.063Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:21.068Z [MASTER] error: Database Connection Error: 28P01 undefined:undefined
> 2021-03-18T10:53:21.068Z [MASTER] warn: Will retry in 3 seconds... [Attempt 10 of 10]
> 2021-03-18T10:53:24.071Z [MASTER] info: Connecting to database...
> 2021-03-18T10:53:24.076Z [MASTER] error: Database Initialization Error: password authentication failed for user "postgres"

> 2021-03-18 10:52:25.273 GMT [337] FATAL:  password authentication failed for user "postgres"
> 2021-03-18 10:52:25.273 GMT [337] DETAIL:  Password does not match for user "postgres".
>         Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"

**Comment by hWorblehat** [comment]
@Freundschaft Did you work out what was wrong here? I'm hitting this issue after a Kubernetes upgrade. Was working fine before, and helm release was not touched. After kubernetes rescheduled pods on the upgraded nodes, it can no longer connect to postgres.

**Comment by Freundschaft** [comment]
unfortunately not entirely, I ended up setting the password manually, but also suspected an issue with domain names in kubernetes

**Comment by hWorblehat** [comment]
I've done some investigation, and I agree this issue is essentially caused by not explicitly setting the `postgres.postgresPassword` value. For the benefit of anyone else who ends up here, setting this value will prevent data loss.

It's actually cause by what I believe is a bug in the postgresql chart. For the details of how the problem occurs: see bitnami/charts#6121

I've also raised a bug against this Helm chart: #3844

**Comment by gangstead** [comment]
This same issue just cost me many hours of headache.  I had a 19 day old release and everything was working until I rolled all my k8s worker nodes to change instance types, when the wiki pods started up on the new nodes they started getting the above error.  I saved the secret that was created and the volume and claim were also still there. I was tricked for a while into thinking that the 19 day old secret & volume & claim would all work together.  I really didn't want to have to start with a fresh volume since I'd already spent a while configuring the wiki for our organization (although the actual pages were backed to github so they were safe).

Here's the steps I did to reuse the original database (using k9s unless otherwise noted): 
- I modified the volume reclaim policy to `retain` so it wouldn't actually get deleted
  - I ended up deleting the helm release in the process, which would have deleted the volume.  That wasn't necessary, I just tried all the wrong things before fixing it with the following instructions:
- Shell into the postgres container (`wikijs-postgresql-0` for me)
  - `env | grep POSTGRES_PASSWORD` Verify the password was what I thought it was
  - `psql -U postgres` Entered the above password to verify it wasn't working any more
  - `echo "local all all trust" > /bitnami/postgresql/conf/pg_hba.conf && pg_ctl restart`
  - Shell will terminate. Verify in the pod logs that it found the new `pg_hba.conf` file
- Shell into postgres container again
  - `psql -U postgres` You should be signed in without being asked for a password
  - `ALTER USER postgres WITH PASSWORD 'new_password';` and exit psql. 
  - `rm /bitnamic/postgresql/conf/pg_hba.conf && pg_ctl restart` to require passwords again
- Shell in one more time and verify `psql -U postgres` works with the expected password

In the end I don't fully understand the "works as designed" response from the bitnami maintainers, this seems like a big pitfall for wikijs chart users who want to keep this running long term.  I initially hadn't worried about the database because I figured having the important bits backed up to github made the database kind of ephemeral, but there's a lot of configuration in there so best practice for this project is to pass in a postgres password or secret.

Here's the relevant part of my flux setup for anyone who is interested:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wikijs
  namespace: wiki
spec:
  interval: 999h
  ref:
    branch: latest
  url: https://github.com/Requarks/wiki
---
# This volume claimed here was created by an earlier version of the chart
# You probably don't need this if you are setting it up correctly the first time with a password
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-wikijs-postgresql-pvc
  namespace: wiki
spec:
  volumeName: pvc-1234-uuid-67890-previously-autogenerated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
# override values from https://github.com/Requarks/wiki/blob/dev/dev/helm/values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikijs
  namespace: wiki
spec:
  chart:
    spec:
      chart: dev/helm
      sourceRef:
        kind: GitRepository
        name: wikijs
  interval: 99h
  releaseName: wikijs
  values:
    postgresql:
      existingSecret: wikijs-postgresql
      persistence: #omit this if not reusing a claim
        existingClaim: data-wikijs-postgresql-pvc
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wikijs-postgresql
  namespace: wiki
spec:
  encryptedData:
    postgresql-password: YOUR_LONG_SEALED_SECRET_OUTPUT_HERE
  template:
    metadata:
      creationTimestamp: null
      name: wikijs-postgresql
      namespace: wiki
```
