### ISSUE TITLE
Wiki agent dies, but docker container is still running

### ISSUE THREAD

**Issue by hemberger** [Requarks/wiki#328]
I'm getting an out-of-memory error in my logs from time to time:

```
wiki_host  | 2017-11-19T14:55:52.153Z - info: [AGENT] Performing pull from remote Git repository...
wiki_host  | internal/child_process.js:325
wiki_host  |     throw errnoException(err, 'spawn');
wiki_host  |     ^
wiki_host  | 
wiki_host  | Error: spawn ENOMEM
wiki_host  |     at _errnoException (util.js:1021:11)
wiki_host  |     at ChildProcess.spawn (internal/child_process.js:325:11)
wiki_host  |     at Object.exports.spawn (child_process.js:494:9)
wiki_host  |     at spawn (/var/wiki/node_modules/git-wrapper2-promise/node_modules/child-process-promise/lib/index.js:81:23)
wiki_host  |     at module.exports.Git.spawn (/var/wiki/node_modules/git-wrapper2-promise/git.js:54:10)
wiki_host  |     at module.exports.exports.pull (/var/wiki/node_modules/git-wrapper2-promise/commands.js:48:15)
wiki_host  |     at Object.resync (/var/wiki/server/libs/git.js:167:22)
wiki_host  |     at CronJob.onTick (/var/wiki/server/agent.js:108:28)
wiki_host  |     at CronJob.fireOnTick (/var/wiki/node_modules/cron/lib/cron.js:416:22)
wiki_host  |     at Timeout.callbackWrapper (/var/wiki/node_modules/cron/lib/cron.js:481:9)
wiki_host  |     at ontimeout (timers.js:471:11)
wiki_host  |     at tryOnTimeout (timers.js:306:5)
wiki_host  |     at Timer.listOnTimeout (timers.js:266:5)
```
Certainly figuring out what is causing the OOM would be nice, but I'm actually more interested in finding a way for it to restart itself. If the entire node server died, then my docker container would exit and a `restart: always` policy in my docker-compose.yml would ensure that everything is always up and running. Instead, I feel like my only option is to forcefully restart the container at regular intervals just in case it's down.

Or is there some feature of Wiki.js that I'm missing that would allow the agent to be restarted?

My docker-compose.yml wiki service is pretty bare-bones:
```
    wiki:
        image: requarks/wiki
        container_name: wiki_host
        environment:
            SESSION_SECRET: ${SESSION_SECRET}
            WIKI_ADMIN_EMAIL: ${WIKI_ADMIN_EMAIL}
            HOST: ${HOST}
            FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
            FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
            GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
            GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        volumes:
            - ./config.yml:/var/wiki/config.yml:ro
            - ./github.pem:/github.pem
        links:
            - wiki-db
```
Thanks!
