### ISSUE TITLE
Unable to get running from docker-compose

### ISSUE THREAD

**Issue by RayBB** [Requarks/wiki#340]
Hello,

I've spent a while trying to get this running but I just can't seem to get it off the ground.
I don't need git syncing right now just trying to get the basic bits running.

Here's what I've done
git clone https://github.com/Requarks/wiki.git
copy config.sample.yml to tools folder

edit config.sample.yml such that:
```
#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full explanation + examples in the documentation:
# https://docs.requarks.io/wiki/install
# You can use an ENV variable by using $(ENV_VAR_NAME) as the value

# ---------------------------------------------------------------------
# Title of this site
# ---------------------------------------------------------------------

title: Wiki

# ---------------------------------------------------------------------
# Full public path to the site, without the trailing slash
# ---------------------------------------------------------------------
# INCLUDE CLIENT PORT IF NOT 80/443!

host: http://localhost:8080

# ---------------------------------------------------------------------
# Port the main server should listen to (80 by default)
# ---------------------------------------------------------------------
# To use process.env.PORT, comment the line below:

port: 8080

# ---------------------------------------------------------------------
# Data Directories
# ---------------------------------------------------------------------

paths:
  repo: ./repo
  data: ./data

# ---------------------------------------------------------------------
# Upload Limits
# ---------------------------------------------------------------------
# In megabytes (MB)

uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100

# ---------------------------------------------------------------------
# Site Language
# ---------------------------------------------------------------------
# Possible values: en, de, es, fa, fr, ja, ko, nl, pt, ru, sr, tr or zh

lang: en

# Enable for right to left languages (e.g. arabic):
langRtl: false

# ---------------------------------------------------------------------
# Site Authentication
# ---------------------------------------------------------------------

public: false

auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: true
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: true
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: 'SLACK_CLIENT_ID'
    clientSecret: 'SLACK_CLIENT_SECRET'
  ldap:
    enabled: false
    url: ldap://serverhost:389
    bindDn: cn='root'
    bindCredentials: BIND_PASSWORD
    searchBase: o=users,o=example.com
    searchFilter: (uid={{username}})
    tlsEnabled: false
    tlsCertPath: C:\example\root_ca_cert.crt
  azure:
    enabled: false
    clientId: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: '00000002-0000-0000-c000-000000000000'
    tenant: 'YOUR_TENANT.onmicrosoft.com'

# ---------------------------------------------------------------------
# Secret key to use when encrypting sessions
# ---------------------------------------------------------------------
# Use a long and unique random string (256-bit keys are perfect!)

sessionSecret: 1234567890abcdefghijklmnopqrstuvxyz

# ---------------------------------------------------------------------
# Database Connection String
# ---------------------------------------------------------------------

db: mongodb://wikidb:27017/wiki

# ---------------------------------------------------------------------
# Git Connection Info
# ---------------------------------------------------------------------

git:
  url: https://github.com/Organization/Repo
  branch: master
  auth:

    # Type: basic or ssh
    type: ssh

    # Only for Basic authentication:
    username: marty
    password: MartyMcFly88

    # Only for SSH authentication:
    privateKey: /etc/wiki/keys/git.pem

    sslVerify: true

  # Default email to use as commit author
  serverEmail: marty@example.com

  # Whether to use user email as author in commits
  showUserEmail: true

# ---------------------------------------------------------------------
# Features
# ---------------------------------------------------------------------
# You can enable / disable specific features below

features:
  linebreaks: true
  mathjax: true

# ---------------------------------------------------------------------
# External Logging
# ---------------------------------------------------------------------

externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false

# ---------------------------------------------------------------------
# Color Theme
# ---------------------------------------------------------------------

theme:
  primary: indigo
  alt: blue-grey
  viewSource: all # all | write | false
  footer: blue-grey
  code:
    dark: true
    colorize: true
```

edit docker-compose.yml such that:
```
version: '2'
services:
  wikidb:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --logpath=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    ports:
      - '8080:3000'
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./config.sample.yml:/var/wiki/config.yml
```

run docker-compose up
and I get this:
```
Starting tools_wikidb_1
Starting tools_wikijs_1
Attaching to tools_wikidb_1, tools_wikijs_1
wikijs_1  | 2017-11-30 23:00:37,873 CRIT Supervisor running as root (no user in config file)
wikijs_1  | 2017-11-30 23:00:37,882 INFO RPC interface 'supervisor' initialized
wikijs_1  | 2017-11-30 23:00:37,882 CRIT Server 'unix_http_server' running without any HTTP authentication checking
wikijs_1  | 2017-11-30 23:00:37,883 INFO supervisord started with pid 1
wikijs_1  | 2017-11-30 23:00:38,886 INFO spawned: 'wikijs' with pid 7
wikijs_1  | 2017-11-30 23:00:40,878 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
wikijs_1  | 2017-11-30 23:00:44,703 INFO reaped unknown pid 40
```

If I try to go to localhost:8080 or the local ip address on port 8080 I just get nothing.

I changed the docker-compose.yml from version 3 to 2 because if I don't I get this:
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

I get the same result if I don't change the port.
Any idea what I'm doing wrong?
