### ISSUE TITLE
MongoDB Docker Compose

### ISSUE THREAD

**Issue by ddulic** [Requarks/wiki#347]
I seem to have a problem starting the service via Docker.

docker-compose.yml
```yml
version: '3'
services:
  wikidb:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --logpath=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    ports:
      - '8080:3000'
    environment:
      WIKI_ADMIN_EMAIL: me@example.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
      - ./logs:/logs
```
config.yml
```yml
title: Wiki
host: http://localhost:3000
port: 3000
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: en
langRtl: false
public: false
auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: false
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: SLACK_CLIENT_ID
    clientSecret: SLACK_CLIENT_SECRET
  ldap:
    enabled: false
    url: 'ldap://serverhost:389'
    bindDn: cn='root'
    bindCredentials: BIND_PASSWORD
    searchBase: 'o=users,o=example.com'
    searchFilter: '(uid={{username}})'
    tlsEnabled: false
    tlsCertPath: 'C:\example\root_ca_cert.crt'
  azure:
    enabled: false
    clientId: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: 00000002-0000-0000-c000-000000000000
    tenant: YOUR_TENANT.onmicrosoft.com
sessionSecret: ca0b6c0e681a436ed4d2ea996efab66982d54136fabd51bc87721f1a7fbd0494
db: mongodb://wikidb:27017/wiki
git: false
features:
  linebreaks: true
  mathjax: true
externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false
theme:
  primary: indigo
  alt: blue-grey
  viewSource: all
  footer: blue-grey
  code:
    dark: true
    colorize: true
```

supervisord.log
```
2017-12-07 13:26:24,541 CRIT Supervisor running as root (no user in config file)
2017-12-07 13:26:24,572 INFO RPC interface 'supervisor' initialized
2017-12-07 13:26:24,573 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-12-07 13:26:24,573 INFO supervisord started with pid 1
2017-12-07 13:26:25,577 INFO spawned: 'wikijs' with pid 7
2017-12-07 13:26:26,700 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

wiki-stderr.log
```
2017-12-07T13:26:37.224Z - error: [AGENT] Failed to connect to MongoDB instance.
Unhandled rejection MongoError: failed to connect to server [wikidb:27017] on first connect [MongoError: connect ECONNREFUSED 172.18.0.2:27017]
    at Pool.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/var/wiki/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

`docker ps -a`
> Note that I shutdown the containers here
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS                    NAMES
9578e5c1273f        requarks/wiki:latest   "supervisord --nod..."   8 minutes ago       Exited (0) 2 seconds ago                            wiki_wikijs_1
975fa413dae6        mongo                  "docker-entrypoint..."   8 minutes ago       Exited (0) 2 seconds ago                            wiki_wikidb_1
```

`docker logs wiki_wikidb_1` returns nothing.

I tried replacing the `expose` with `ports: 27017:27017` but that also didn't help, however the port was when visible via `netstat`

Any suggestions?

Thanks in advance.

**Comment by brian80122** [comment]
get the same issue

**Comment by ZhaoTianze** [comment]
I get the same issue on my cloud server.

I have test these files on my host, and every thing is fine.

After that, I copy these files to my cloud server, then exec `sudo docker-compose up`.

The wiki-stderr.log show the same issue.

**Comment by ZhaoTianze** [comment]
I try to remove the `command: '--smallfiles --logpath=/dev/null'`

It is work now. Why?

**Comment by ddulic** [comment]
@ZhaoTianze I can confirm this also works. Removing the command successfully runs the container.

After a bit of testing, it seems that docker doesn't like the `--logpath` command, whatever the value is.
Might I suggest changing the mongodb docker-compose config to use env variables to set the log path, which seems to work.

```yml
  wikidb:
    image: mongo:latest
    expose:
      - '27017'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    command: 'mongod --smallfiles'
    volumes:
      - ./data/mongo:/data/db
```

On a side note, while we are at the docker-compose topic, it seems I needed to set my `config.yml` and `docker-compose.yml` file options to the following in order to get the static files to work.

`config.yml`
```yml
title: Wiki
host: http://example.com:8080
port: 3000
```

`docker-compose.yml`
```yml
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    ports:
      - '8080:3000'
    environment:
      WIKI_ADMIN_EMAIL: me@example.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
      - ./logs:/logs
```

**Comment by ZhaoTianze** [comment]
Hi, @ddulic 
When all containers work well, I found another issue. 

After I stop these containers by use `docker-compse stop`，I try to restart them by use `docker-compse start`.  

I also get the error: Failed to connect to MongoDB instance.

I think the reason is that, when you restart the two containers, the wiki.js is restart faster than the mongo. So the wiki.js can`t connect to the mongo and it don`t have any attempt to reconnect.

If I restart the wiki.js container again after the mongo is running, it will work well.

Bad English, sorry， Hope you understand.

**Comment by nziermann** [comment]
@ZhaoTianze I don't have the same issue. But you may find [depends_on](https://docs.docker.com/compose/compose-file/#depends_on) helpful in your case.

**Comment by Arbyy** [comment]
I added something like 
```yaml
networks:
  internal:
     external: false
```
to my docker-compose.yml, and added
```yaml
networks:
  - internal
```
to my mongodb and wikijs services and that solved this issue for me.

I also find that removing `--logpath=/dev/null` as well as using `docker-compose up` without a `-d` switch better allows you to debug the mongo container.
