### ISSUE TITLE
Wiki does not respond on requests from  time to time 

### ISSUE THREAD

**Issue by efimlosev** [Requarks/wiki#353]
### Actual behavior
Pretty often the  wiki does not respond at all
### Expected behavior
it should respond all the time 
### Steps to reproduce the behavior
CentOS 7
```
cat /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core)

````
```
node -v
v8.9.3
```
mongo -version
MongoDB shell version v3.4.10
git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64

```
```
 git --version
git version 2.9.5

```
cat /home/wiki/config.yml
title: Wiki
host: http://wiki.routerhosting.com:3001
port: 3001
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 100
  maxOtherFileSize: 5000
lang: en
langRtl: false
public: false
auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: false
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: SLACK_CLIENT_ID
    clientSecret: SLACK_CLIENT_SECRET
  ldap:
    enabled: false
    url: 'ldap://serverhost:389'
    bindDn: cn='root'
    bindCredentials: BIND_PASSWORD
    searchBase: 'o=users,o=example.com'
    searchFilter: '(uid={{username}})'
    tlsEnabled: false
    tlsCertPath: 'C:\example\root_ca_cert.crt'
  azure:
    enabled: false
    clientId: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: 00000002-0000-0000-c000-000000000000
    tenant: YOUR_TENANT.onmicrosoft.com
sessionSecret:123456789wqwz
db: 'mongodb://user:pass@localhost:27017/wiki'
git:
  url: 'https://gitlab.com/efim345/rep.git'
  branch: master
  auth:
    type: basic
    username: efim345
    password: 'passwd'
    privateKey: /etc/wiki/keys/git.pem
    sslVerify: true
  showUserEmail: true
  serverEmail: efimius@XXX.com
features:
  linebreaks: true
  mathjax: true
externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false
theme:
  primary: indigo
  alt: blue-grey
  viewSource: all
  footer: blue-grey
  code:
    dark: true
    colorize: true
```
 whoami 
wiki
```
$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version (cpu64-rhel6)
stepping	: 3
microcode	: 0x1
cpu MHz		: 3200.022
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips	: 6400.04
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```
```
cat /proc/meminfo 
MemTotal:        2050172 kB
MemFree:           83804 kB
MemAvailable:    1524056 kB
Buffers:           97592 kB
Cached:           176996 kB
SwapCached:          176 kB
Active:           350812 kB
Inactive:         222236 kB
Active(anon):     209276 kB
Inactive(anon):   112088 kB
Active(file):     141536 kB
Inactive(file):   110148 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       1047548 kB
SwapFree:        1040924 kB
Dirty:               160 kB
Writeback:             0 kB
AnonPages:        298288 kB
Mapped:            34132 kB
Shmem:             22904 kB
Slab:            1366024 kB
SReclaimable:    1357504 kB
SUnreclaim:         8520 kB
KernelStack:         984 kB
PageTables:         5140 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2072632 kB
Committed_AS:     831144 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        5084 kB
VmallocChunk:   34359733191 kB
HardwareCorrupted:     0 kB
AnonHugePages:     69632 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       30708 kB
DirectMap2M:     2066432 kB
```

![screenshot from 2017-12-14 19-58-51](https://user-images.githubusercontent.com/11035141/34026273-aeb8dfd0-e109-11e7-8266-5fb29690b8e3.png)
