### ISSUE TITLE
cannot get ldap working

### ISSUE THREAD

**Issue by justinhelmer** [Requarks/wiki#360]
### Actual behavior

Logging in through web interface fails with users that exist in ldap

### Expected behavior

Login should succeed

### Steps to reproduce the behavior

This works:

```
ldapsearch -x -h 192.168.1.2 -b "dc=ldap,dc=justin,dc=network" -D "uid=root,cn=users,dc=ldap,dc=justin,dc=network" -W "(uid=foo)"
```
(returns user foo after entering root password)

However, entering the same config into `config.yml` does not:

```yml
  ldap:
    enabled: true
    url: ldap://192.168.1.2:389
    bindDn: uid=root,cn=users,dc=ldap,dc=justin,dc=network
    bindCredentials: <ACTUAL_PASSWORD_INSERTED>
    searchBase: dc=ldap,dc=justin,dc=network
    searchFilter: (uid={{username}})
    tlsEnabled: false
```

I have also successfully connected with multiple other LDAP clients without issue.

Any help would be greatly appreciated.
