### ISSUE TITLE
installation problem of docker

### ISSUE THREAD

**Issue by ifreyr** [Requarks/wiki#392]
### Actual behavior

Home page seems not work

### Expected behavior

Show beautiful html

### Steps to reproduce the behavior

I run wiki.js by docker-compose, and modify the cong.yml. But when I open my Chrome, just show:

![image](https://user-images.githubusercontent.com/11648367/35717269-17aa8fc6-0819-11e8-82d5-4ee2e15373d6.png)

And I try to click the "create home page", But I cannot do anything for no OK menu found.

What happend? the config.yml? docker-compose file?

**Comment by NGPixel** [comment]
Your `host` parameter in your config.yml is wrong. It must match the host you're accessing your wiki with.

**Comment by ifreyr** [comment]
Very thanks for your tips, I forget to add port to my config.yml.

Now everything seems ok, except : 

When I new a wiki, but I cannot found everything in my repo and remote git repo, my config like this:

```
git:
  url: https://gitee.com/ifreyr/wiki.git
  branch: master
  auth:

    # Type: basic or ssh
    type: ssh

    # Only for Basic authentication:
    username: xxxx
    password: xxxx

    # Only for SSH authentication:
    privateKey: /Users/freyr/.ssh/id_rsa

    sslVerify: true

  # Default email to use as commit author
  serverEmail: xxxx

  # Whether to use user email as author in commits
  showUserEmail: true
```
