### ISSUE TITLE
Local environment trying to load resources from port 80

### ISSUE THREAD

**Issue by aero31aero** [Requarks/wiki#393]
### Actual behavior

I set domain as the default http://localhost and port to serve on as 4000

Visiting localhost:4000 gives: 
![image](https://user-images.githubusercontent.com/8033238/35740955-6d708fd0-085c-11e8-8b60-66291e05b444.png)

Also, when I clicked on go to wiki button, it redirected me to port 80 where I was greeted by my Apache server.

### Expected behavior

WikiJS should honor the port while fetching static resources and in the configuration UI's redirect button.

### Steps to reproduce the behavior

Already told above. Here's the relevant part of the generated config:

```
title: Bits Wiki
host: 'http://localhost'
port: 4000
paths:
  repo: ./repo
  data: ./data
```

I also tried restarting with `node wiki restart` to see if that solves the problem of some initial configuration or first run issue.
