### ISSUE TITLE
Unable to use LDAP authentication

### ISSUE THREAD

**Issue by MargauxG** [Requarks/wiki#428]
Hello, 

I don't know if I'm doing something wrong but I can't setup the LDPA authentication. One of the main problem being that we have multiple LDAP hosts and there's no way to configure that in the config.yml
Also, after trying debugging with help of the answer in issue 360, I've got the following error when trying to log in with another account than the admin one : "Failed to serialize user into session"

Our LDPA config:
```
ldap:
    enabled: true
    url: ldap://<one of our host>:389
    bindDn: "cn=<an account>"
    bindCredentials: "<the password>"
    searchBase: "DC=<something>,DC=<something else>"
    searchFilter: "(uid={{sAMAccountName}})"
    tlsEnabled: false
```

Thank you for your help
