### ISSUE TITLE
Unable to use LDAP authentication

### ISSUE THREAD

**Issue by kopax** [Requarks/wiki#473]
I am trying to find the good value for connecting to LDAP.

```yml
  ldap:
    enabled: false
    url: ldap://serverhost:389
    bindDn: cn='root'
    bindCredentials: BIND_PASSWORD
    searchBase: o=users,o=example.com
    searchFilter: (uid={{username}})
    tlsEnabled: false
    tlsCertPath: C:\example\root_ca_cert.crt
```

I haven't found a way to log in the LDAP, I usually do like this

```yml
  ldap:
    url: ldap://openldap-test
    base: dc=org-test,dc=com
    username: cn=admin,dc=org-test,dc=com
    password: testing
    user-search-base: ou=users,o=org-test
    user-search-filter: (uid={0})
    group-search-base: o=org-test
    group-search-filter: (member={0})
```

So I think my configuration should be : 

```yml
  ldap:
    enabled: true
    url: ldap://192.168.2.4:389
#    bindDn: cn='root'
    bindDn: cn=admin,o=org-test,dc=com
    bindCredentials: testing
    searchBase: ou=users,o=org-test,dc=com
    searchFilter: (uid={{username}})
    tlsEnabled: false
    tlsCertPath: /etc/ssl/GandiStandardSSLCA2.pem
```

The value from the demo is confising because it doesn't include the fullDn.

Ho can I connect to my ldap ?
