### ISSUE TITLE
New docker user, sync with gitlab fail on restart

### ISSUE THREAD

**Issue by kopax** [Requarks/wiki#476]
### Actual behavior

1. I have started  a gitlab sync wiki once, and recreated my container, the sync is gone and we have to start over the wiki. Repo will remain unsync.
1. I have also disabled mathjax and I can't list uploaded file.

Is there anything else to configure in order to use docker ? This is my docker-compose:

```yml
version: '3'
services:
  wikidb:
    image: mongo
    ports:
      - 27017:27017
    command: '--smallfiles --bind_ip wikidb'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - 80:3000
    environment:
      WIKI_ADMIN_EMAIL: postmaster@example.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
      - ./git.pem:/etc/wiki/keys/git.pem
      - ./repo:/repo
      - ./data:/data
      - ./logs:/logs
```
