### ISSUE TITLE
LDAP Blank "Login Required" Page

### ISSUE THREAD

**Issue by garethwarry** [Requarks/wiki#495]
### Actual behavior
Blank page saying "Login required" but without a prompt.

### Expected behavior
Login prompt to enter username and password.

### Steps to reproduce the behavior
1. Followed instructions here: https://docs.requarks.io/wiki/install/authentication#ldap-active-directory
2. Disabled local authentication, enabled ldap

```
public: false
auth:
  defaultReadAccess: false
  local:
    enabled: false
  ldap:
    enabled: true
    url: 'ldap://<LDAP Endpoint>:389'
    bindDn: cn='<Service Username>'
    bindCredentials: '<Service Password>'
    searchBase: 'o=Users,o=<Domain Name>'
    searchFilter: '(uid={{username}})'
    tlsEnabled: false
    tlsCertPath: 'C:\example\root_ca_cert.crt'
```
