### ISSUE TITLE
config.yml - allow getting mongo db URI from environment

### ISSUE THREAD

**Issue by naseer** [Requarks/wiki#51]
Some containers like apcera provide the mongo url in an environment variable.

**Comment by NGPixel** [comment]
Option added for Beta 9 (191f00cc89005b8def923da4029a35e11684aa49)

Usage:
```yaml
# Using URI:
db: mongodb://localhost:27017/wiki

# Using ENV variable:
db: $ENV_VARIABLE_NAME
```
