### ISSUE TITLE
Only one user can authenticate/login via LDAP

### ISSUE THREAD

**Issue by hellfirehd** [Requarks/wiki#517]
First of all, I'm really impressed with Wiki.js!  It's easily the best Wiki solution I've come across.  I spent the weekend porting our docs from MediaWiki and I have to say, it was a great, painless experience.

But now that I want to show what I've got to the other users in our org, I can't get it to let them login with LDAP.  I'm completely stumped and would appreciate any help/insight/advice you can provide.

### Actual behavior
One user (me) can successfully authenticate and login via LDAP. No other users can even though they have they same AD group memberships as me.

### Expected behavior
All users should be able to authenticate via LDAP.

### Environment
Running in a docker container based on the instructions [here](https://docs.requarks.io/wiki/install/docker).  Everything works flawlessly for local logins and a single LDAP login.  The rest of the LDAP logins will not work at all.  

No errors appear in the logs (`NODE_ENV=development`). This returns the expected results for each of the users that need access:
```
`ldapsearch -H ldap://10.xxx.xxx.xxx:389 -D "CN=MCP,CN=Users,DC=PDSI,DC=local" -w sanitizedpassword -b "OU=PDSI,DC=PDSI,DC=local" "(samaccountname=dougw)"
```
config.yml (sanitized)
```yaml
#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full explanation + examples in the documentation:
# https://docs.requarks.io/wiki/install
# You can use an ENV variable by using $(ENV_VAR_NAME) as the value

# ---------------------------------------------------------------------
# Title of this site
# ---------------------------------------------------------------------

title: PDSI Wiki

# ---------------------------------------------------------------------
# Full public path to the site, without the trailing slash
# ---------------------------------------------------------------------
# INCLUDE CLIENT PORT IF NOT 80/443!

host: http://wiki.example.com

# ---------------------------------------------------------------------
# Port the main server should listen to (80 by default)
# ---------------------------------------------------------------------
# To use process.env.PORT, comment the line below:

port: 3000

# ---------------------------------------------------------------------
# Data Directories
# ---------------------------------------------------------------------

paths:
  repo: ./repo
  data: ./data

# ---------------------------------------------------------------------
# Upload Limits
# ---------------------------------------------------------------------
# In megabytes (MB)

uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100

# ---------------------------------------------------------------------
# Site Language
# ---------------------------------------------------------------------
# Possible values: en, de, es, fa, fr, ja, ko, nl, pt, ru, sr, sv, tr or zh

lang: en

# Enable for right to left languages (e.g. arabic):
langRtl: false

# ---------------------------------------------------------------------
# Site Authentication
# ---------------------------------------------------------------------

public: false

auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: false
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: 'SLACK_CLIENT_ID'
    clientSecret: 'SLACK_CLIENT_SECRET'
  ldap:
    enabled: true
    url: ldap://10.250.0.5:389
    bindDn: CN=MCP,CN=Users,DC=PDSI,DC=local
    bindCredentials: sanitizedcredentials
    searchBase: OU=PDSI,DC=PDSI,DC=local
    searchFilter: (&(memberOf=CN=Wiki Editor,CN=Users,DC=PDSI,DC=local)(sAMAccountName={{username}}))
    tlsEnabled: false
    tlsCertPath: C:\example\root_ca_cert.crt
  azure:
    enabled: false
    clientId: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: '00000002-0000-0000-c000-000000000000'
    tenant: 'YOUR_TENANT.onmicrosoft.com'
  oauth2:
    enabled: false
    clientId: OAUTH2_CLIENT_ID
    clientSecret: OAUTH2_CLIENT_SECRET
    authorizationURL: OAUTH2_AUTH_URL
    tokenURL: OAUTH2_TOKEN_URL

# ---------------------------------------------------------------------
# Secret key to use when encrypting sessions
# ---------------------------------------------------------------------
# Use a long and unique random string (256-bit keys are perfect!)

sessionSecret: sanitized

# ---------------------------------------------------------------------
# Database Connection String
# ---------------------------------------------------------------------

db: mongodb://mongo:27017/wiki

# ---------------------------------------------------------------------
# Git Connection Info
# ---------------------------------------------------------------------

git:
  url: http://gitea:3000/PDSI/Wiki.git
  branch: master
  auth:

    # Type: basic or ssh
    type: basic

    # Only for Basic authentication:
    username: wiki
    password: sanitized

    # Only for SSH authentication:
    privateKey: /etc/wiki/keys/git.pem

    sslVerify: true

  # Default email to use as commit author
  serverEmail: wiki@example.com

  # Whether to use user email as author in commits
  showUserEmail: true

# ---------------------------------------------------------------------
# Features
# ---------------------------------------------------------------------
# You can enable / disable specific features below

features:
  linebreaks: true
  mathjax: true

# ---------------------------------------------------------------------
# External Logging
# ---------------------------------------------------------------------

externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false

# ---------------------------------------------------------------------
# Color Theme
# ---------------------------------------------------------------------

theme:
  primary: indigo
  alt: blue-grey
  viewSource: all # all | write | false
  footer: blue-grey
  code:
    dark: true
colorize: true
```

My working LDAP account from mongo:
```json
{
    "_id" : ObjectId("5aee5b393406660001286b0f"),
    "updatedAt" : ISODate("2018-05-07T22:06:56.233Z"),
    "createdAt" : ISODate("2018-05-06T01:32:41.805Z"),
    "email" : "doug@example.com",
    "provider" : "ldap",
    "providerId" : "CN=Doug,OU=PDSI,DC=PDSI,DC=local",
    "password" : "",
    "name" : "Doug",
    "rights" : [ 
        {
            "role" : "admin",
            "path" : "/",
            "exact" : false,
            "deny" : false,
            "_id" : ObjectId("5af0b5f046939f00010e0dad")
        }
    ],
    "__v" : 1
}
```
Another user who's account isn't work with LDAP:
```json
{
    "_id" : ObjectId("5af0b62246939f00010e0dae"),
    "updatedAt" : ISODate("2018-05-07T20:25:19.921Z"),
    "createdAt" : ISODate("2018-05-07T20:25:06.147Z"),
    "email" : "ian@example.com",
    "provider" : "ldap",
    "providerId" : "CN=Ian,OU=PDSI,DC=PDSI,DC=local",
    "password" : "",
    "name" : "Ian",
    "rights" : [ 
        {
            "role" : "admin",
            "path" : "/",
            "exact" : false,
            "deny" : false,
            "_id" : ObjectId("5af0b62f46939f00010e0db0")
        }
    ],
    "__v" : 1
}
```

1. Is there anything obviously wrong with my config?
2. How can I turn on more detailed logging?
3. When adding new users the DropDownList doesn't have an option for LDAP.  Should it?
 * If not, what is the correct way to add new LDAP users?

This is a make or break issue for us.  If we can't get the LDAP working reliably then we won't be able to use this solution.
