### ISSUE TITLE
Edit Button not pulling latest copy

### ISSUE THREAD

**Issue by garethwarry** [Requarks/wiki#519]
### Versions
Wiki.js: v1.0.78
Node.js: v8.11.1
OS: Windows 10.0.15063 x64
IIS: v10.0.15063.0

### Summary
After editing a page, clicking on "Edit" again will not pull the latest change for several minutes. I would like to try flushing the cache and rebuilding indexes, but I'm not sure how (the button for that just returns "Coming soon!". 

### Actual behavior
After editing a page, clicking "Edit" again will not pull the latest change. Logs seem to show that git pushes are only happening every 5 minutes. Maybe there's a way to increase that to immediate on-change?

### Expected behavior
"Edit" should return the latest change.

### Configuration
LDAP authentication is active and working. Configured to write changes to TFS 2013 Git repo (confirmed working for service user and all LDAP users). IIS is configured to provide HTTPS via reverse proxy (URL rewrite rule aimed at HTTP on port 3000). Cache is disabled through IIS ("Prevent all caching" for user-mode and kernel-mode caching). 

```
title: Wiki
host: https://companywiki
port: 3000
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: en
langRtl: false
public: false
auth:
  defaultReadAccess: false
  local:
    enabled: true
  ldap:
    enabled: true
    url: 'ldap://ipaddress:389'
    bindDn: 'cn=serviceuser,ou=Users,ou=Org,dc=corp,dc=company,dc=com'
    bindCredentials: 'password'
    searchBase: 'dc=corp,dc=company,dc=com'
    searchFilter: '(&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))'
    tlsEnabled: false
sessionSecret: secrethere
db: 'mongodb://wikiuser:password@localhost:27017/wiki'
git:
  url: 'http://mytfs:8080/tfs/DefaultCollection/wiki/_git/Wiki'
  branch: master
  auth:
    type: basic
    username: 'company\serviceuser'
    password: 'password'
    sslVerify: false
  showUserEmail: false
  serverEmail: myemail@company.com
features:
  linebreaks: true
  mathjax: true
externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false
theme:
  primary: indigo
  alt: blue-grey
  viewSource: all
  footer: blue-grey
  code:
    dark: true
    colorize: true
```

### Steps to reproduce the behavior
1. Edit a page and lick "Save Changes"
2. Try editing the page again after a few seconds (fails to load most recent)
3. Try editing the page after a few minutes (succeeds)

Any advice would be highly appreciated. Let me know if I should provide anything else. Thanks!
