### ISSUE TITLE
Girt synchronizing using SSH doesn't work with git 2.7.4

### ISSUE THREAD

**Issue by fpagnoux** [Requarks/wiki#578]
### Actual behavior

With git 2.7.4, I get an error when starting the wiki: 

```
{ code: 1,
  message: '`git --git-dir=repo/.git --work-tree=repo pull origin master` failed with code 1',
  stderr: 'Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n',
  stdout: '' }
```

### Expected behavior

I expect the `repo` directory to be synchronized with my repository

### Steps to reproduce the behavior

Try to synchronise with a distant repository using SSH with git 2.7.4.

Extract from my config:

```yaml
git:
  url: "git@github.com:xxx/yyy-wiki.git"
  branch: master
  auth:
    type: ssh
    privateKey: "/path/to/private.key"
    sslVerify: true
```

Upgrading git to `2.15.1` solves the issue, but the documentation indicates "Git 2.7.4 or later". I don't know exactly which git version is the first one to work, but `2.7.4` for sure causes issues 🙂.

Thanks for the good work!
