### ISSUE TITLE
LDAP Auth against Active Directory results in "unable to verify the first certificate" error

### ISSUE THREAD

**Issue by marketconnections** [Requarks/wiki#606]
### Actual behavior

Followed this tutorial's section on setting up LDAP to add my AD Certificate to the Ubuntu server's CA chain. [https://www.theo-andreou.org/?p=1744](https://www.theo-andreou.org/?p=1744)  
Configured the ldap section:  

```
  ldap:
    enabled: true
    url: ldaps://my-dc.my.addomain.com:636
    bindDn: "CN=LDAP Bind Account,OU=users,DC=my,DC=addomain,DC=com"
    bindCredentials: secret
    searchBase: "DC=my,DC=addomain,CD=com"
    searchFilter: "(samaccountname={{username}})"
    tlsEnabled: true
    tlsCertPath: '/etc/ssl/certs/ca-certificates.crt'
```

Restarted Wiki.js and attempted to login as a users, and got this error message at the login screen:
"Login error
unable to verify the first certificate"  

### Expected behavior

Login should have succeeded.  I have multiple services on my network querying over ldaps for authentication that do work.  Typically, because my AD CA Cert is self-signed, I do not validate the CA certificate.

### Question:

Is there an option that can be added to the config.yaml to ignore problems with the certificate chain?  I've looked at passport-ldapauth and node-ldapauth-fork projects to see if there are config options in the submodules, and it seems that the TLS module of Node.js 8.x supports an option: 
[https://nodejs.org/docs/latest-v8.x/api/tls.html#tls_tls_connect_options_callback](https://nodejs.org/docs/latest-v8.x/api/tls.html#tls_tls_connect_options_callback)

`rejectUnauthorized <boolean> If not false, the server certificate is verified against the list of supplied CAs. An 'error' event is emitted if verification fails; err.code contains the OpenSSL error code. Defaults to true.`

Can a config.yaml parameter be added that will set the rejectUnauthorized to `false`?
