### ISSUE TITLE
Startup page missing after container is restarted

### ISSUE THREAD

**Issue by gerbsen** [Requarks/wiki#623]
### Actual behavior
I've installed wiki.js with docker and every time I kill/restart the wikijs container the GUI says I should create a start/home page. The db table entries is also empty, but the users db contains users from a previous run. Where are the pages actually stored? 

### Expected behavior
Pages should persist over the lifetime of a docker container. And I should not need to create a start page every time a stop & start the container

### Steps to reproduce the behavior
```
docker run --name mongodb -v /home/gerber/wiki.js/data/mongodb:/data/db -d mongo
docker run -p 8007:3000 -e "WIKI_ADMIN_EMAIL=xxxxx@xxxx.xy" -v /home/gerber/wiki.js/config.yml:/var/wiki/config.yml --name wikijs --link mongodb:mongodb requarks/wiki
----
title: 'What a Wiki'
host: 'https://wiki.domain.com'
port: 3000
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: de
langRtl: false
public: false
auth:
  defaultReadAccess: false
  local:
    enabled: true
sessionSecret: SECRET_THING
db: 'mongodb://mongodb:27017/wiki'
git: false

```
