### ISSUE TITLE
Auth configuration not taken into account - cannot mount LDAP

### ISSUE THREAD

**Issue by TitoVince35** [Requarks/wiki#625]
## Symptoms
- **Login Page** : only 3 authentication providers can be enabled : local, Microsoft Account, Google. I can play with their configuration, enable/disable them, but the other providers never show up.
- **Users Page** : when I add a new user, the provider selector offers : Local Database, Microsoft, Google, Facebook, Github, Slack... never LDAP. But in my configuration only "local" and "ldap" are enabled.
- When I set **public** to `true` I still must login.
## Context
- Using Docker image `FROM requarks/wiki:latest`
- Mongodb container on the side linked in a `docker-compose.yml` file.
## Configuration
```yaml
public: false
auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: false
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: 'SLACK_CLIENT_ID'
    clientSecret: 'SLACK_CLIENT_SECRET'
  ldap:
    enabled: true
    url: 'ldap://amadc1.in.ama.bzh:389'
    # (my AD settings...)
    tlsEnabled: false
    tlsCertPath: C:\example\root_ca_cert.crt
  azure:
    enabled: false
    clientId: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: '00000002-0000-0000-c000-000000000000'
    tenant: 'YOUR_TENANT.onmicrosoft.com'
  oauth2:
    enabled: false
    clientId: OAUTH2_CLIENT_ID
    clientSecret: OAUTH2_CLIENT_SECRET
    authorizationURL: OAUTH2_AUTH_URL
    tokenURL: OAUTH2_TOKEN_URL
  oidc:
    enabled: false
    clientId: OPENID_CONNECT_CLIENT_ID
    clientSecret: OPENID_CONNECT_CLIENT_SECRET
    issuer: OPENID_CONNECT_ISSUER
    userInfoUrl: OPENID_CONNECT_USER_INFO_URL
    authorizationURL: OPENID_CONNECT_AUTHORIZATION_URL
    tokenURL: OPENID_CONNECT_TOKEN_URL
    emailClaim: OPENID_CONNECT_EMAIL_CLAIM_PATH
    usernameClaim: OPENID_CONNECT_USERNAME_CLAIM_PATH
```
