### ISSUE TITLE
How to invoke wiki content from another application as a link

### ISSUE THREAD

**Issue by singhcl** [Requarks/wiki#654]
### Actual behavior
I am not finding a way to open a wiki doc page from another application
### Expected behavior
I should be able to open a wiki page from my main application to show this page as a help information
### Steps to reproduce the behavior

1. I want to show a help button in my application.
2. As I click on help icon, I want to open the respective wiki page
3. I dont know how to get access to this page. If I provide direct URL it asks for user login info

**Comment by saucepleez** [comment]
Did you set defaultReadAccess in **config.yml**?  That was in the docs...
```

auth:
  defaultReadAccess: true

```

**Comment by NGPixel** [comment]
Make sure the `public` option is set to true in your `config.yml`.

**Comment by singhcl** [comment]
Hi both,

thanks for your suggestions but it did not work.

1. Upon setting defaultReadAccess, it still takes to login page
2. Upon making public : true, it shows a forbidden page with link to login
3. and yes, i restarted wiki server post the changes.

Here is the updated config.yaml
```
title: Wiki
host: <host>
port: <port>
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: en
langRtl: false
public: true
auth:
  defaultReadAccess: true
  local:
    enabled: true
  google:
    enabled: true
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: true
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
```
