### ISSUE TITLE
github ssh sync is broken

### ISSUE THREAD

**Issue by bitworm** [Requarks/wiki#655]
### Expected behavior
local changes are reflected on remote (github) repo in ~5min
### Observed behavior
No changes are observed to move from local to remote (github) after ~30 min

Github integration otherwise works:
- ./repo was populated with existing remote repo contents on installation
- `git remote -v` returns sensible output: 
```
origin	git@github.com:<user>/<repo>.git (fetch)
origin	git@github.com:<user>/<repo>.git (push)
```
- if the wiki is restarted, changes are pushed

### other info
`git --version` = 2.19.1

section in config.yml:
```
git:
  url: 'git@github.com:<user>/<repo>.git'
  branch: master
  auth:
    type: ssh
    privateKey: /Users/<username>/.ssh/<private_key_file>
    sslVerify: true
  signature:
    name: <gh username>
    email: <github email associated with acct>
  showUserEmail: true
  serverEmail: <github email associated with acct>

```
