### ISSUE TITLE
Not pushing to git?

### ISSUE THREAD

**Issue by madchap** [Requarks/wiki#688]
Using latest docker image, through docker-compose. Site works fine.

### Actual behavior
Upon saving, nothing gets pushed.
Nothing in the container logs.

If I exec into the container, git works (eventually after a `git pull --allow-unrelated-histories`), I can `git push` and all. Local git changes are well there, as a `git log` can attest.

There seems to be no action whatsoever with git backend.

```
git:                                                                                                                           
  url: git@gitlab.com:myrepo/wikijs.git
  branch: master               
  auth: 
        
    # Type: basic or ssh
    type: ssh          
        
    # Only for SSH authentication:
    privateKey: /etc/wiki/keys/git.pem
        
    sslVerify: true  
        
  # Default email to use as commit author
  serverEmail: xxxxxxx@gmail.com
        
  # Whether to use user email as author in commits
  showUserEmail: true  
        
  signature:         
    name: Fred Blaise
    email: xxxxxxx@gmail.com
```

### Expected behavior
Upon saving, my changes are pushed.

**Comment by madchap** [comment]
So it seems to now be automagically work now? hmmm. Looks like halloween did its thing.

**Comment by madchap** [comment]
Actually, re-opening -- maybe for a feature request?

Is it really doing its thing every 5mn, and not being event-based on save?

**Comment by NGPixel** [comment]
No, this is by design. While all commits are event based, the sync is done periodically as it's a network intensive operation.

v2 will likely have a setting to set the sync delay, but doing a sync on every event is not a good idea.

**Comment by johnshumon** [comment]
Is it mandatory for private key to be in `.pem` extension/format? Following is my configuration but it doesn't push anything to git. Also deploy key is added in the repository with write permission 
```
git:
  url: git@gitlab.com:myrepo/wiki.git
  branch: master
  auth:
    # Type: basic or ssh
    type: ssh
    privateKey: ./keys/wikijs_rsa
    sslVerify: true

  signature:
    name: 'John Doe'
    email: info@domain.com

  # Default email to use as commit author
  serverEmail: info@domain.com

  # Whether to use user email as author in commits
  showUserEmail: true
```
