### ISSUE TITLE
Network Error: Unexpected token '<', "<html> <h"... is not valid JSON

### ISSUE THREAD

**Issue by wreidlinger** [requarks/wiki#6938]
Just saw exact same error on my side. Happens If I want to edit some pages.

![image](https://github.com/requarks/wiki/assets/100240865/4a41ab0c-3cef-4514-940d-a070d3383d6b)

From the Chrome DEV Tool:
![image](https://github.com/requarks/wiki/assets/100240865/1fa535e4-99b0-4fb7-baf5-ae46a8428802)

I'm having this docker compose running since a long time. First time I see a error like this.
This is the docker compose config:

```
version: "3"
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: *****
      POSTGRES_USER: wiki
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki
      DB_PASS: ******
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
volumes:
  db-data:
```

Running the latest version and also seeing the problems in the Admin panel.

![image](https://github.com/requarks/wiki/assets/100240865/b14ddf16-cc36-4d99-a910-b46aa3b16be7)

In front to the docker I have a nginx reverse proxy running with the following config. This worked so fare for a long time.

```
/upstream docs {
  server 127.0.0.1:3000;
}

server {
  listen 80;

  if ($scheme != "https") {
      return 301 https://$host$request_uri;
  }

  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/docs.domain.something/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/docs.domain.something/privkey.pem;

  server_name docs.domain.something;

  add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";

  location / {
    proxy_pass         http://docs;
    proxy_http_version 1.1;

    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto http;
    proxy_redirect     http:// $scheme://;

    proxy_set_header   Host $http_host;

    proxy_connect_timeout   1m;
    proxy_send_timeout      1m;
    proxy_read_timeout      1m;
  }
}
```

_Originally posted by @wreidlinger in https://github.com/requarks/wiki/discussions/6589#discussioncomment-8072182_

**Comment by wreidlinger** [comment]
After digging some more I found this nginx error `413 Request Entity Too Large`

```
Request URL: https://docs.domainexample.net/graphql
Request Method: POST
Status Code: 413 Request Entity Too Large
Remote Address: 10.1.99.18:443
Referrer Policy: same-origin
```

![image](https://github.com/requarks/wiki/assets/100240865/2482c328-d3cd-41c5-a8e8-d848cc8949ec)


Fast it was obvious that the misconfiguration will be found in the nginx config.
By adding / modifying the following parameters in the `/etc/nginx/nginx.conf` file I was able to fix the error.

```
        ##buffer policy
        # https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration#buffers
        client_body_buffer_size 1K;
        client_header_buffer_size 1k;
        client_max_body_size 10M;
        large_client_header_buffers 2 1k;
        ##end buffer policy
```

Restart the server and you should be fine.
`sudo systemctl restart nginx.service`

The problem with the placeholder titles in the menu bar of the admin panel could be fixed by adding `SSL_ACTIVE: 0` in the docker compose file. At least it worked for me, even before I fixed the other problem with the `413 Request Entity Too Large` error.

```
version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wiki
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2.5
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki
      DB_PASS: wikijsrocks
      DB_NAME: wiki
      SSL_ACTIVE: 0

    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
volumes:
  db-data:
```

![image](https://github.com/requarks/wiki/assets/100240865/0bdbf132-2c06-4e18-bf8f-6d22a3e702ab)
