### ISSUE TITLE
[Help] Working example of config.yml

### ISSUE THREAD

**Issue by gkoerk** [Requarks/wiki#696]
This is a **help** request.

Is it possible to get a working example of a `config.yml` file which matches/works with a given `docker-compose.yml` file? I'm trying to get this set up behind a reverse proxy (traefik) and can't figure out what is going wrong. The image is running, but I cannot access it. I suspect a problem with the `host:` and `port:` settings in the `config.yml` file. I know it needs to match the address used to access it, but I don't know how to configure my reverse proxy: I don't know which port to use in the reverse proxy because it is specified in the `config.yml` file and in the `docker-compose.yml` file. Please help!

**Comment by winkelement** [comment]
Part of my `config.yml`:
```yaml
# ---------------------------------------------------------------------
# Full public path to the site, without the trailing slash
# ---------------------------------------------------------------------
# INCLUDE CLIENT PORT IF NOT 80/443!

host: http://mydomain.ddns.net:3003

# ---------------------------------------------------------------------
# Port the main server should listen to (80 by default)
# ---------------------------------------------------------------------
# To use process.env.PORT, comment the line below:

port: 3000
```
Part of my `docker-compose.yml`:
```yaml
ports:
    - '3000:3000'
```
I use haproxy as a reverse proxy. It listens on port 3003 and redirects to port 3000 (the docker container):
```cfg
frontend ssl_entry
	bind *:3003 ssl crt /usr/local/etc/certs/cert-combined.pem
	redirect scheme https code 301 if !{ ssl_fc }
	mode http
	acl node dst_port 3003
	use_backend node_server if node

backend node_server
	server servername wiki.local:3000 check
	acl authOk http_auth(users)
	http-request auth realm MyAuthRealm if !authOk
```
I hope this helps.
