### ISSUE TITLE
504 request times out

### ISSUE THREAD

**Issue by johnshumon** [Requarks/wiki#698]
-- I'm trying to run on docker locally in my machine.
-- MacBook pro 2018 with latest docker and docker-compose installed.

I have followed through steps mentioned in the documentation. Only thing I have changed is the port number. Then again tried with default port 80. nothing changed!

### Actual behavior
Following is my `docker-compose.yml` file:
```
version: '3'
services:
  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '3000:3000'
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
```

This is my how my `config.yml` looks like:
```
title: Wiki
host: http://localhost:3000
port: 3000
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: en

# Enable for right to left languages (e.g. arabic):
langRtl: false

public: false
auth:
  defaultReadAccess: false
  local:
    enabled: true
sessionSecret: 1234567890abcdefghijklmnopqrstuvxyz

db: mongodb://localhost:27017/wiki

features:
  linebreaks: true
  mathjax: true

externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false

theme:
  primary: indigo
  alt: blue-grey
  viewSource: all # all | write | false
  footer: blue-grey
  code:
    dark: true
    colorize: true
```
### Expected behavior
Display the landing page.
