### ISSUE TITLE
V2 beta9 not starting, Locales not installed, "Guest user is missing!"

### ISSUE THREAD

**Issue by JeroenAdam** [Requarks/wiki#745]
### Actual behavior
V2 beta9 not starting, CRITICAL ERROR: Guest user is missing!

### Expected behavior
New instance V2 beta9 up and running

### Steps to reproduce the behavior
1. Docker-compose up -d (with the example Docker Compose file)
2. docker exec -it wiki_wiki_1 /bin/bash
3. edit config.yml, here below the content:
```
port: 3000
bindIP: 0.0.0.0
db:
  type: postgres
  host: db
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki
  storage: db-data:/var/lib/postgresql/data
redis:
  host: redis
  port: 6379
  db: 0
  password:
logLevel: info
```
4. Browse to http://localhost:80 (outside the container)
5. Setup wizard accepts input e-mail, password, states 'Finalizing your installation...'
6. Setup wizard stating: Something went wrong.. Cannot find module './locales/default.json'
(I checked the folder server/locales, same as Github repo currently, only one .md file in the dev branch)
7. reboot container and the logs show: 
       warn: No such locale in local store.
       CRITICAL ERROR: Guest user is missing!
