### ISSUE TITLE
Pages -> No pages to display.

### ISSUE THREAD

**Issue by Joci933** [Requarks/wiki#782]
### Actual behavior

I was created some page, but these isn't visible in "pages" menu.
Image: [https://prnt.sc/mwtdod](https://prnt.sc/mwtdod)

I set git storage, but the pages in git repositroy isn't visible in admin panel. :(

Docker-compose.yml:
```
version: "3"
services:

  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    networks:
      - wikinet

  wiki:
    image: requarks/wiki:beta
    depends_on:
      - db
    environment:
      PORT: 3000 # DO NOT CHANGE THIS LINE! Use ports below to specify listening port.
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    volumes:
      - ./volumes/.ssh:/home/node/.ssh
      - ./volumes/repo:/wiki/repo
      - ./volumes/data:/wiki/data
    networks:
      - wikinet
    ports:
      - "3000:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example

networks:
  wikinet:

volumes:
  db-data:
```

config.yml:
```
port: 3000
bindIP: 0.0.0.0
db:
  type: postgres
  host: db
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki
logLevel: info
```

### Expected behavior

List all of the pages.
