### ISSUE TITLE
Applying basic auth on traefik reverse proxy on a docker deployed wikijs instance causes repeated and multiple authentication requests

### ISSUE THREAD

**Issue by aheil** [Requarks/wiki#798]
### Actual behavior

Applying basic auth on reverse proxy ([traefik](https://traefik.io/)) on a docker deployed wikijs instance causes repeated and multiple authentication requests.

When cancelling any of these authentication requests, a message is shown:

![image](https://user-images.githubusercontent.com/509229/55313386-ee6d0e80-5467-11e9-9a9c-653298161ab3.png)

### Expected behavior

When basic auth is used behind the reverse proxy, I would expect a one time password request. 

### Steps to reproduce the behavior

Deploy wiki.js v2 in Docker with traefik reverse proxy.  

Apply the following settings in docker-compose.yml: 

```
wiki:
    image: requarks/wiki:beta
    depends_on:
      - db
    environment:
      PORT: 3000 # DO NOT CHANGE THIS LINE! Use ports below to specify listening port.
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    ports:
      - "3000:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example
    networks:
      wiki:
      reverse_proxy:
    labels:
      traefik.enable: true
      traefik.backend: wikijs
      traefik.docker.network: reverse_proxy
      traefik.frontend.rule: Host:wiki.example.org
      traefik.port: 3000
      traefik.frontend.auth.basic: "username:password"
```
By removing the line  _traefik.frontend.auth.basic: "username:password"_, basic auth is disabled and the wiki works as expected with the reverse poxy.
Also, on the particular traefik installation, other applications work as expected using basic auth.

### Additional Information

For v1 there was an description how to set up nginx as reverse proxy, also I thought I have seen an option to explicitly enable reverse proxy functionality. Unfortunately, I haven't found this information anymore.
