### ISSUE TITLE
Wiki.js 2.0.0-beta.115 starting problems

### ISSUE THREAD

**Issue by muterulo** [Requarks/wiki#839]
### Actual behavior
Hi.
I'am trying to start Wiki.js 2.0.0-beta.115 but then this appears.

### Expected behavior
http://prntscr.com/noz1yw

### Steps to reproduce the behavior
I tried MySQL and MariaDB but both doesn´t work.
System: Windows 10

**Comment by aalmir** [comment]
I have tried with SQLite and there is some missing windows modules.

**Comment by NGPixel** [comment]
You're most likely using a numeric password. You need to put your password inside quotes:

```
db:
  type: mysql
  host: 1.2.3.4
  port: 3306
  user: wikijs
  pass: '12345678'
  db: wiki
```
