### ISSUE TITLE
docker-compose : This server does not support ssl

### ISSUE THREAD

**Issue by dcpc007** [Requarks/wiki#867]
**Question**
Hi, for a quick test, i took the docker-compose example in the doc.
Change only some labels

At start i got this error :
```
$ docker-compose up
Starting wikijs_wikijsdb_1 ... done
Recreating wikijs_wikijs_1 ... done
Attaching to wikijs_wikijsdb_1, wikijs_wikijs_1
wikijsdb_1  | WARNING: no logs are available with the 'none' log driver
wikijs_1    | Loading configuration from /wiki/config.yml... OK
wikijs_1    | 2019-06-04T08:07:57.773Z [MASTER] info: =======================================
wikijs_1    | 2019-06-04T08:07:57.775Z [MASTER] info: = Wiki.js 2.0.0-beta.174 ==============
wikijs_1    | 2019-06-04T08:07:57.775Z [MASTER] info: =======================================
wikijs_1    | 2019-06-04T08:07:57.775Z [MASTER] info: Initializing...
wikijs_1    | 2019-06-04T08:07:58.157Z [MASTER] error: Database Initialization Error: The server does not support SSL connections
wikijs_wikijs_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping wikijs_wikijsdb_1 ... done
```

**Host Info (please complete the following information):**
OS: Debian 9, Docker 18.06.6, docker-compose 1.21.0
Wiki.js version: 2.0.0-beta.174
Database engine: postgres 9.7

**Full D-C file :** 
```
version: "3"
services:

  wikijsdb:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - db-data:/srv/wikijs_v2/postgresql/data
    networks:
      - wikijsnet

  wikijs:
    image: requarks/wiki:beta
    depends_on:
      - wikijsdb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijsdb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    networks:
      - wikijsnet
    ports:
      - "3000:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example

networks:
  wikijsnet:

volumes:
  db-data:
```
