### ISSUE TITLE
HTTP Timeout when using Docker

### ISSUE THREAD

**Issue by It4lik** [Requarks/wiki#923]
Hi, 

OS: Debian 9.9 + Docker
Wiki.js version: beta tag (it's 2.0.0-beta.230)
Database engine: postgres 9.6.14
Node : 10.15.3

I'm trying to setup WikiJS (beta) behind a NGINX reverse proxy.

I'm using the official docker-compose.yml that I tweaked to use a config file.

```
version: "3"
services:
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: bap
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    networks:
      - wikinet

  wiki:
    image: requarks/wiki:beta
    depends_on:
      - db
    networks:
      - wikinet
    ports:
      - "8088:3000" 
    volumes:
      - "./wiki/config.yml:/wiki/config.yml"
    restart: always

networks:
  wikinet:

volumes:
  db-data:
```

And my config.yml : 
```
#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full documentation + examples:
# https://docs-beta.requarks.io/install

# ---------------------------------------------------------------------
# Port the server should listen to
# ---------------------------------------------------------------------

port: 3000

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Supported Database Engines:
# - postgres = PostgreSQL 9.5 or later
# - mysql = MySQL 8.0 or later (5.7.8 partially supported, refer to docs)
# - mariadb = MariaDB 10.2.7 or later
# - mssql = MS SQL Server 2012 or later
# - sqlite = SQLite 3.9 or later

db:
  type: postgres
  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: db
  port: 5432
  user: wikijs
  pass: bap
  db: wiki
  ssl: false

#######################################################################
# ADVANCED OPTIONS                                                    #
#######################################################################
# Do not change unless you know what you are doing!

# ---------------------------------------------------------------------
# Use X-Forwarded-For header
# ---------------------------------------------------------------------
# Enable only if Wiki.js is behind a reverse-proxy (nginx, apache, etc)
# or a cloud proxying services like Cloudflare.

trustProxy: true

# ---------------------------------------------------------------------
# SSL/TLS Settings
# ---------------------------------------------------------------------
# Consider using a reverse proxy (e.g. nginx) if you require more
# advanced options than those provided below.

ssl:
  enabled: false

  # Certificate format, either 'pem' or 'pfx':
  format: pem
  # Using PEM format:
  key: path/to/key.pem
  cert: path/to/cert.pem
  # Using PFX format:
  pfx: path/to/cert.pfx
  # Passphrase when using encrypted PEM / PFX keys (default: null):
  passphrase: null
  # Diffie Hellman parameters, with key length being greater or equal
  # to 1024 bits (default: null):
  dhparam: null

  # Listen on this HTTP port and redirect all requests to HTTPS.
  # Set to false to disable (default: 80):
  redirectNonSSLPort: 80

# ---------------------------------------------------------------------
# Database Pool Options
# ---------------------------------------------------------------------
# Refer to https://github.com/vincit/tarn.js for all possible options

pool:
  # min: 2
  # max: 10

# ---------------------------------------------------------------------
# IP address the server should listen to
# ---------------------------------------------------------------------
# Leave 0.0.0.0 for all interfaces

bindIP: 0.0.0.0

# ---------------------------------------------------------------------
# Log Level
# ---------------------------------------------------------------------
# Possible values: error, warn, info (default), verbose, debug, silly

logLevel: info

# ---------------------------------------------------------------------
# Upload Limits
# ---------------------------------------------------------------------
# If you're using a reverse-proxy in front of Wiki.js, you must also
# change your proxy upload limits!

uploads:
  # Maximum upload size in bytes per file (default: 5242880 (5 MB))
  maxFileSize: 5242880
  # Maximum file uploads per request (default: 20)
  maxFiles: 10

# ---------------------------------------------------------------------
# Offline Mode
# ---------------------------------------------------------------------
# If your server cannot access the internet. Set to true and manually
# download the offline files for sideloading.

offline: false
```

My NGINX config for this app : 
```
server {
    listen 80;
    listen [::]:80 ;
    server_name  bap;

    listen 443 ssl http2;

    # RSA certificate
    ssl_certificate /etc/letsencrypt/live/bap/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bap/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;

    # reverse proxy
    location / {
            proxy_pass http://127.0.0.1:8088;
            include proxy.conf;
    }
 
    include general.conf;

    # Redirect non-https traffic to https
    if ($scheme != "https") {
        return 301 https://bap$request_uri;
    }
}
```
_In the config files excerpts, I replaced the true URL and db password with "bap"._

**Problem is :** 
* going on the full URL using the reverse proxy results in a timeout (`https://wiki.xxx.tld)`
* I can't even `curl localhost:8088` from the host, timeout too
* I can successfully `curl localhost:3000` from inside the container
* nothing changes if I go on the WebUI admin panel and change host address to the full URL (including https scheme) (wiki will be on https://wiki.xxx.tld)

People are talking about a "host" variable in the config.yml but I don't see it in the example config file. (I tried to manually add it, nothing changes).

it4.
