### ISSUE TITLE
V2 Docker install with Managed Digital Ocean Database

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Requarks/wiki#966]
**Question**
I am using a Digital Ocean Managed database and am using traefik as a reverse proxy and am having issues getting wikijs working. 

here's my docker-compose.yml

```yaml
version: "3"

networks:
  web:
    external: true

services:
  wiki:
    image: requarks/wiki:beta
    environment:
      DB_TYPE: postgres
      DB_HOST: digitalocean.com-host
      DB_PORT: 25060
      DB_USER: wikijs
      DB_PASS: super-secret-passwd  
      DB_NAME: wikijs-db
      DB_SSL: 1 
    restart: always
    networks:
      - web
    container_name: wiki
    ports:
      - "3000:3003" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example
    labels:
      - "traefik.docker.network=web"
      - "traefik.enabled=true"
      - "traefik.frontend.rule=Host:wiki.my_domain.com,www.wiki.my_domain.com"
      - "traefik.port=3003"
      - "traefik.backend=wiki"
```

**Host Info (please complete the following information):**
OS: [Debian 10, Docker]
Wiki.js version: [requarks/wiki:beta]
Database engine: [postgres 11]
