### ISSUE TITLE
Installing v2 beta on digitalocean with managed database

### ISSUE THREAD

**Issue by RickCogley** [Requarks/wiki#979]
**Question**

Thank you for wiki.js. I've compared many systems like it, but your app seems to really fit the bill for us, having the right balance of features. We need localized pages and the ability to have both secure areas which are read only for many, open areas which are free for anyone in our group to edit, and integration w/ git and s3, and it seems all of that is possible, so I wanted to install and test more extensively. 

I'm trying to run wiki.js v2 beta, and like the idea of digitalocean's managed database, so I set up a droplet on Ubuntu 18.04.3 LTS and a managed postgres db on my DO account. I'm new to docker, but installed via DO's [tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04) and it seems pretty straightforward. 

Per the instructions for wiki.js, I assembled this string and ran it after logging into my droplet, according to the parameters from my managed db:

```
docker run -d -p 80:3000 --name wiki --restart unless-stopped -e "DB_TYPE=postgres" -e "DB_HOST=private-db-postgresql-sgp1-11111-do-user-11111-0.db.ondigitalocean.com" -e "DB_PORT=22222" -e "DB_USER=doadmin" -e "DB_PASS=abcdefg1234567" -e "DB_NAME=defaultdb" -e "DB_SSL=true" requarks/wiki:beta
```

I tried several iterations of the ports and so on, thinking maybe that was causing but in every case, after starting the container, I cannot attach to it. When I try to, I get: 

```
root@thehost:~# docker attach wiki
2019-08-24T01:08:12.332Z [MASTER] error: Database Initialization Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

I had started with postgres 11 but, on your slack someone mentioned using 9 or 10, so I reinstalled the managed db with 10, but, same error. Additionally, DO lets you create a connection pool, and since the error says "the pool is probably full" I tried creating a pool with the max allowed (for me) number of connections: 22. No change after doing that either. 

I cannot attach to the container, so it is hard to tell what exactly is failing. When I do `docker events` I can see the container is dying, and being restarted repeatedly, giving a lot of this:

```
2019-08-23T23:26:13.253020509Z container die ffb406eef85a21ff4b0bf6ed114b1a08bbd34c969c2e75796cf7e1b23da0ebc0 (exitCode=1, image=requarks/wiki:beta, maintainer=requarks.io, name=wiki)
2019-08-23T23:26:13.363547603Z network disconnect c825652e2cedcda9c56090634066b901f8c4d7da154d8544bac76bbe0dbf75c0 (container=ffb406eef85a21ff4b0bf6ed114b1a08bbd34c969c2e75796cf7e1b23da0ebc0, name=bridge, type=bridge)
2019-08-23T23:26:13.435975227Z network connect c825652e2cedcda9c56090634066b901f8c4d7da154d8544bac76bbe0dbf75c0 (container=ffb406eef85a21ff4b0bf6ed114b1a08bbd34c969c2e75796cf7e1b23da0ebc0, name=bridge, type=bridge)
2019-08-23T23:26:14.156984088Z container start ffb406eef85a21ff4b0bf6ed114b1a08bbd34c969c2e75796cf7e1b23da0ebc0 (image=requarks/wiki:beta, maintainer=requarks.io, name=wiki)
```

I notice that the CI build is now failing, mentioning docker, so maybe that is what is going on. This is as of Sat 24 Aug 2019 10AM in Japan.

A few questions come to mind: 

* am I barking up the wrong tree and is there a recommended environment on digital ocean? For example, using kubernetes rather than docker etc? I'd rather use whatever the wiki.js devs are using, for instance postgres with whatever setup is the best way with the least friction going forward. 
* will v2 work happily with postgres 11? 
* if docker, is it better to use the DO marketplace ubuntu with docker pre-installed, than to install on an OS from scratch? 
* if docker, sorry for the newb question but is docker-compose the way to go, like is mentioned in #966 ?
* can you recommend a good reverse proxy to use? Is traefik the way to go? 

I'm happy to assemble documentation on a "best practice" for merging into the official docs, if someone can share some notes and guidance, and help get me started. 

Thank you in advance. 

**Host Info:**  
  
OS: Ubuntu 18.04.3 LTS x64, Docker
Wiki.js version: 2.0.0-beta.241
Database engine: postgres 11, 10, on a different host via digital ocean hosted db service

**Comment by RickCogley** [comment]
Ok, tried installing direct from the tarball, and I get the same error when running `node server`. 

```
Database Initialization Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

**Comment by Th3Whit3Wolf** [comment]
Hey I am using a managed Postgress database with docker-compose.

here is my docker-compose.yml
```yaml
version: "3"

networks:
  web:
    external: true

services:
  wiki:
    image: requarks/wiki:beta
    environment:
      DB_TYPE: postgres
      DB_HOST: digital_ocean_database_name-0.db.ondigitalocean.com
      DB_PORT: digital_ocean_host_port_number
      DB_USER: db_user
      DB_PASS: db_user_password
      DB_NAME: db_name
      DB_SSL: 1
    restart: always
    networks:
      - web
    container_name: wiki
    ports:
      - "3000:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example
    labels:
      - "traefik.docker.network=web"
      - "traefik.enabled=true"
      - "traefik.frontend.rule=Host:wiki.my_domain.com,www.wiki.my_domain.com"
      - "traefik.port=3000"
      - "traefik.backend=wiki"
      - "traefik.protocol=http"
```

I am using traefik as the reverse proxy, if you're using nginx you'll want to drop everything below labels

I hope this helps!
