### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Requarks/wiki#980]
**Question**
Having Issues using backing up with git on my self hosted gitea server. Is wikijs using anything platform specific that would prevent me from using gitea?

I have selected git module from admin pane and filled it with the information for ssh. That failed so I tried basic which also failed. Then I tried setting volumes with a config.yml and a ssh key, set ssh again but with path instead of content which also failed.

**Host Info:**
OS: [e.g. Debian 10, Docker]
Wiki.js version: [e.g. 2.0.0-beta.241]
Database engine: [e.g. postgres 11.5]

**Comment by knifecake** [comment]
I have not found that Wiki.js uses anything specific that prevents it from interacting with any Git server. At least when using HTTPS for accessing the repository.

Are you running Wiki.js with docker? If so you might check the logs with `docker logs <container name>`. If you are using docker-compose, you can try `docker-compose logs <service name>` from the directory where your `docker-compose.yml` file is located.

I was able to deploy both using docker-compose. The most difficult part was figuring out which port forwarding rules I had to use. Here is a my `docker-compose.yml` file:

```yaml
version: '3'

services:
  gitea:
    image: gitea/gitea:1
    environment:
      - USER_UID=501
      - USER_GID=20
      - 'APP_NAME="My Gitea"'
      - 'SSH_PORT=1452'
      - 'SSH_DOMAIN=your.domain.com'
      - 'ROOT_URL=http://your.domain.com/'
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "1452:22"
  postgres:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: "somepassword"
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
  wikijs:
    image: requarks/wiki:beta
    depends_on:
      - postgres
      - gitea
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: "somepassword"
      DB_NAME: wikijs
    ports:
      - "80:3000"
```
