### ISSUE TITLE
Error: role "wikijs" does not exist

### ISSUE THREAD

**Issue by deadbird99** [Requarks/wiki#988]
When I try deploying Wiki.js 2 (latest beta) using docker, I get this message:

> [MASTER] error: Database Initialization Error: role "wikijs" does not exist

I simply used the docker-compose file provided [here](https://docs.requarks.io/install/docker), changing only a few things relatives to domain name and network.

Here is the full docker-compose log:

```
db_1    | WARNING: no logs are available with the 'none' log driver
wiki_1  | Loading configuration from /wiki/config.yml... OK
wiki_1  | 2019-08-26T12:36:56.658Z [MASTER] info: =======================================
wiki_1  | 2019-08-26T12:36:56.660Z [MASTER] info: = Wiki.js 2.0.0-beta.268 ==============
wiki_1  | 2019-08-26T12:36:56.660Z [MASTER] info: =======================================
wiki_1  | 2019-08-26T12:36:56.660Z [MASTER] info: Initializing...
wiki_1  | 2019-08-26T12:36:56.929Z [MASTER] error: Database Initialization Error: role "wikijs" does not exist
wiki2_wiki_1 exited with code 1
```

And the docker compose file:

```
version: "3"
services:

  db:
    image: postgres:9-alpine
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_PASSWORD=wikijsrocks
      - POSTGRES_USER=wikijs
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:beta
    depends_on:
      - db
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=wikijs
      - DB_PASS=wikijsrocks
      - DB_NAME=wiki
      - VIRTUAL_HOST=xxxxxxxxxxxxxxxxxxxx
      - VIRTUAL_PORT=3280
      - LETSENCRYPT_HOST=xxxxxxxxxxxxxxxxxxxxxx
      - LETSENCRYPT_EMAIL=xxxxxxxxxxxxxxxxx
    expose:
      - 3280
    ports:
      - "3280:3280" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example

networks:
  default:
    external:
      name: mynet

volumes:
  db-data:
```

Can someone help?

Thanks in advance!!
